Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/eoan64"
  config.vm.box_version = "20191016.0.0"
  # config.vm.synced_folder "../vagrantcommon/", "/vagrant", type: "rsync"
  # config.vm.provider "virtualbox" do |vb|
  #   vb.gui = false
  #   vb.memory = "4096"
  # end
  # config.vm.provision "shell", path: "../vagrantcommon/provision_deb.bash"
  # config.ssh.forward_x11 = true
  # config.vm.network :forwarded_port, guest: 22, host: 2411, id: "ssh"
  config.ssh.extra_args = "-tt"
end
