#!/usr/bin/env bash
set -euo pipefail

# Regenerates shared/ios/.xcode.env.local. Xcode script phases run with a stripped
# PATH, so node/go must be resolved here (full login PATH) and baked in as absolute
# paths. This file is gitignored and gets deleted by `yarn ios:pod:clean`.

cd "$(dirname "$0")/.."
OUT="ios/.xcode.env.local"

NODE_BINARY="$(command -v node || true)"
GO_BINARY="$(command -v go || true)"

if [ -z "$NODE_BINARY" ]; then
  echo "warning: node not found on PATH; NODE_BINARY left unset in $OUT" >&2
fi
if [ -z "$GO_BINARY" ]; then
  echo "warning: go not found on PATH; GO_BINARY left unset in $OUT" >&2
fi

{
  echo "# Generated by shared/react-native/write-xcode-env-local.sh. Do not commit."
  [ -n "$NODE_BINARY" ] && echo "export NODE_BINARY=$NODE_BINARY"
  [ -n "$GO_BINARY" ] && echo "export GO_BINARY=$GO_BINARY"
} > "$OUT"

echo "wrote $OUT"
