#!/usr/bin/env bash
set -euox pipefail

systemctl --user daemon-reload

for varname in SECRETS_TEAM SECRETS_REPO CHAT_TEAM CHAT_CHANNEL GNUPGHOME; do
	if [ -z "${!varname}" ]; then
		echo "No $varname found, check environment settings...aborting."
		exit 1
	fi
done

echo Enter tuxbot paperkey next
keybase oneshot -u tuxbot

echo Enter code signing key triplesec password next
if [ -v KEYBASE_TEST_CODE_SIGNING_KEY ]; then
    opts="-b "
    fn=test_code_signing_key.gpg.3sv4
else
    opts="-b --compatibility"
    fn=code_signing_key.gpg.3s
fi
# shellcheck disable=SC2086
triplesec dec $opts < "/keybase/team/$SECRETS_TEAM/.kbfs_autogit/$SECRETS_REPO/$fn" | gpg --import

echo Starting chatbot...
systemctl --user start tuxbot

echo "Done. Try !help in @$CHAT_TEAM#$CHAT_CHANNEL to ensure chatbot is up."
