#!/usr/bin/env bash

echo Enter tuxbot paperkey next
keybase oneshot -u tuxbot

echo Enter code signing key triplesec password next
triplesec dec -b < "/keybase/team/$SECRETS_TEAM/.kbfs_autogit/$SECRETS_REPO/test_code_signing_key.gpg.3s" | gpg --import

echo Starting chatbot...
systemctl --user start tuxbot

echo "Done. Try !help in @$CHAT_TEAM to ensure chatbot is up."
