#!/usr/bin/env bash
set -euox pipefail

# shellcheck disable=SC1090
export $(cat ~/tuxbot.env | xargs)
systemctl --user import-environment
systemctl --user daemon-reload

for varname in SECRETS_TEAM SECRETS_REPO CHAT_TEAM CHAT_CHANNEL GNUPGHOME; do
	if [ -z "${!varname}" ]; then
		echo "No $varname found, check environment settings...aborting."
		exit 1
	fi
done

echo Enter tuxbot paperkey next
keybase oneshot -u tuxbot

echo Enter code signing key triplesec password next
triplesec dec --compatibility -b < "/keybase/team/$SECRETS_TEAM/.kbfs_autogit/$SECRETS_REPO/code_signing_key.gpg.3s" | gpg --import

echo Starting chatbot...
systemctl --user start tuxbot

echo "Done. Try !help in @$CHAT_TEAM#$CHAT_CHANNEL to ensure chatbot is up."
