#!/usr/bin/env bash
set -euox pipefail

export DEBIAN_FRONTEND=noninteractive

apt-get --allow-releaseinfo-change update
apt-get install -yq git curl vim python3-pip jq

GOLANG_VERSION=1.21.6
GOLANG_DOWNLOAD_URL=https://dl.google.com/go/go$GOLANG_VERSION.linux-amd64.tar.gz
GOLANG_DOWNLOAD_SHA256=3f934f40ac360b9c01f616a9aa1796d227d8b0328bf64cb045c7b8c4ee9caea4
wget "$GOLANG_DOWNLOAD_URL" -O /root/go.tar.gz
echo "$GOLANG_DOWNLOAD_SHA256 /root/go.tar.gz" | sha256sum --check --status --strict -
tar -C /usr/local -xzf /root/go.tar.gz
ln -sf /usr/local/go/bin/go /usr/bin/go
rm /root/go.tar.gz

curl --remote-name https://prerelease.keybase.io/keybase_amd64.deb
apt install -yq ./keybase_amd64.deb
rm ./keybase_amd64.deb

pip3 install s3cmd
apt-get -yq install libssl-dev libffi-dev
pip3 install triplesec

usermod -aG systemd-journal vagrant
