Vagrant.configure("2") do |config|
  config.vm.box = "debian/buster64"
  config.vm.provider "virtualbox" do |vb|
    vb.memory = "24576"
  end
  config.vm.provision "file",
    source: "#{ENV['GOPATH']}/src/github.com/keybase/client/packaging/linux/tuxbot/ssh_config",
    destination: "~/.ssh/config",
    run: "always"
  config.vm.provision "file",
    source: "#{ENV['GOPATH']}/src/github.com/keybase/client/packaging/linux/tuxbot/ssh_known_hosts",
    destination: "~/.ssh/known_hosts",
    run: "always"
  config.vm.provision "file",
    source: "~/tuxbot_vagrant_env",
    destination: "~/env",
    run: "always"
  config.vm.provision "shell", path: "provision_tuxbot_env", privileged: true, run: "always"
  config.vm.provision "shell", path: "provision_tuxbot_root", privileged: true
  config.vm.provision "shell", path: "provision_tuxbot_user", privileged: false
end
