Vagrant.configure("2") do |config|
  config.vm.box = "debian/buster64"
  config.vm.provider "virtualbox" do |vb|
    vb.memory = "16384"
  end
  config.vm.provision "shell", path: "provision_tuxbot_root", privileged: true
  config.vm.provision "shell", path: "provision_tuxbot_user", privileged: false
end
