// This file is autogenerated, see tools/release/version.go

package libkbfs

// Version is the current version (should be MAJOR.MINOR.PATCH)
const Version = "1.0.0"

// Build is the current build number
const Build = "32"
