export const initSearch = 'search:initSearch'
export const searchTerm = 'search:searchTerm'
export const searchService = 'search:searchService'
export const searchRunning = 'search:searchRunning'
export const searchResults = 'search:searchResults'
