appId: keybase.ios
---
- runFlow: ../../subflows/escape-to-tabs.yaml

- tapOn:
    text: "Settings"

- extendedWaitUntil:
    visible:
      id: "settings-account"
    timeout: 10000

- assertVisible:
    id: "settings-account"
