//
//  KBFontIcon.m
//  Keybase
//
//  Created by Gabriel on 6/18/15.
//  Copyright (c) 2015 Keybase. All rights reserved.
//

#import "KBFontIcon.h"

#import <CocoaLumberjack/CocoaLumberjack.h>
#import <ObjectiveSugar/ObjectiveSugar.h>

@implementation KBFontIcon

+ (NSFont *)fontWithSize:(CGFloat)size type:(KBFontIconType)type {
  switch (type) {
    case KBFontIconTypeFontAwesome: return [NSFont fontWithName:@"FontAwesome" size:size];
    //case KBFontIconTypeBlackTieLight: return [NSFont fontWithName:@"BlackTie-Light" size:size];
    case KBFontIconTypeBlackTieRegular: return [NSFont fontWithName:@"BlackTie-Regular" size:size];
  }
}

+ (NSAttributedString *)attributedStringForIcon:(NSString *)icon style:(KBTextStyle)style options:(KBTextOptions)options alignment:(NSTextAlignment)alignment lineBreakMode:(NSLineBreakMode)lineBreakMode sender:(id)sender {
  return [self attributedStringForIcon:icon appearance:KBAppearance.currentAppearance style:style options:options alignment:alignment lineBreakMode:lineBreakMode sender:sender];
}

+ (NSAttributedString *)attributedStringForIcon:(NSString *)icon text:(NSString *)text style:(KBTextStyle)style options:(KBTextOptions)options alignment:(NSTextAlignment)alignment lineBreakMode:(NSLineBreakMode)lineBreakMode sender:(id)sender {
  return [self attributedStringForIcon:icon text:text appearance:KBAppearance.currentAppearance style:style options:options alignment:alignment lineBreakMode:lineBreakMode sender:sender];
}

+ (NSAttributedString *)attributedStringForIcon:(NSString *)icon text:(NSString *)text appearance:(id<KBAppearance>)appearance style:(KBTextStyle)style options:(KBTextOptions)options alignment:(NSTextAlignment)alignment lineBreakMode:(NSLineBreakMode)lineBreakMode sender:(id)sender {
  NSAttributedString *iconStr = [self attributedStringForIcon:icon style:style options:options alignment:alignment lineBreakMode:lineBreakMode sender:sender];
  if (!iconStr) {
    return [KBAppearance.currentAppearance attributedString:text style:style options:options alignment:alignment lineBreakMode:lineBreakMode];
  }
  NSMutableAttributedString *str = [[NSMutableAttributedString alloc] init];
  [str appendAttributedString:iconStr];
  if (text) {
    [str appendAttributedString:[KBAppearance.currentAppearance attributedString:NSStringWithFormat(@" %@", text) style:style options:options alignment:alignment lineBreakMode:lineBreakMode]];
  }
  return str;
}

+ (NSAttributedString *)attributedStringForIcon:(NSString *)icon appearance:(id<KBAppearance>)appearance style:(KBTextStyle)style options:(KBTextOptions)options alignment:(NSTextAlignment)alignment lineBreakMode:(NSLineBreakMode)lineBreakMode sender:(id)sender {
  NSColor *color = [appearance textColorForStyle:style options:options];
  CGFloat fontSize = [appearance fontForStyle:style options:options].pointSize;
  return [self attributedStringForIcon:icon color:color size:fontSize alignment:alignment lineBreakMode:lineBreakMode sender:sender];
}

+ (NSAttributedString *)attributedStringForIcon:(NSString *)icon color:(NSColor *)color size:(CGFloat)size alignment:(NSTextAlignment)alignment lineBreakMode:(NSLineBreakMode)lineBreakMode sender:(id)sender {
  NSString *code = [self codeForIcon:icon];
  if (!code) return nil;
  NSMutableParagraphStyle *paragraphStyle = [[NSMutableParagraphStyle alloc] init];
  paragraphStyle.alignment = alignment;
  paragraphStyle.lineBreakMode = lineBreakMode;
  NSDictionary *attributes = @{NSForegroundColorAttributeName: color, NSFontAttributeName: [self fontWithSize:size type:[self fontIconTypeForIcon:icon sender:sender]], NSParagraphStyleAttributeName: paragraphStyle};
  return [[NSAttributedString alloc] initWithString:code attributes:attributes];
}

+ (KBButton *)buttonForIcon:(NSString *)icon text:(NSString *)text style:(KBButtonStyle)style options:(KBButtonOptions)options sender:(id)sender {
  return [KBButton buttonWithAttributedTitle:[KBFontIcon attributedStringForIcon:icon color:KBAppearance.currentAppearance.textColor size:KBAppearance.currentAppearance.buttonFont.pointSize alignment:NSCenterTextAlignment lineBreakMode:NSLineBreakByClipping sender:sender] style:style options:options];
}

+ (KBFontIconType)fontIconTypeForIcon:(NSString *)icon sender:(id)sender {
  //BOOL isRetina = [[sender window] backingScaleFactor] > 1.0;
  if ([icon isEqualTo:@"plus"]) return KBFontIconTypeBlackTieRegular;
  return KBFontIconTypeFontAwesome;
}

+ (NSString *)codeForIcon:(NSString *)icon {
  NSDictionary *aliases = @{
                            @"hackernews": @"hackerNews",
                            @"coinbase": @"bitcoin",
                            @"http": @"link",
                            @"https": @"link",
                            @"dns": @"anchor",
                            @"rooter": @"floppyO",
                            };
  if (aliases[icon]) icon = aliases[icon];

  NSString *blackTieCode = [self blackTieCodes][icon];
  if (blackTieCode) return blackTieCode;

//  NSString *fontAwesomeCode = [self fontAwesomeCodes][icon];
//  if (fontAwesomeCode) return fontAwesomeCode;

  NSString *code = [self otherCodes][icon];
  NSAssert(code, @"No icon for code: %@", code);
  return code;
}

+ (NSDictionary *)blackTieCodes {
  static NSDictionary *icons;
  static dispatch_once_t onceToken;
  dispatch_once(&onceToken, ^{
    icons = @{@"plus": @"\uf01b"};
  });
  return icons;
}

+ (NSDictionary *)fontAwesomeCodes {
  static NSDictionary *icons;
  static dispatch_once_t onceToken;
  dispatch_once(&onceToken, ^{
    icons = @{}; // TODO
  });
  return icons;
}

+ (NSDictionary *)otherCodes {
  static NSDictionary *icons;
  static dispatch_once_t onceToken;
  dispatch_once(&onceToken, ^{
    icons = [NSDictionary dictionaryWithObjectsAndKeys:
           @"\uf042", @"adjust",
           @"\uf170", @"adn",
           @"\uf037", @"alignCenter",
           @"\uf039", @"alignJustify",
           @"\uf036", @"alignLeft",
           @"\uf038", @"alignRight",
           @"\uf0f9", @"ambulance",
           @"\uf13d", @"anchor",
           @"\uf17b", @"android",
           @"\uf209", @"angellist",
           @"\uf103", @"angleDoubleDown",
           @"\uf100", @"angleDoubleLeft",
           @"\uf101", @"angleDoubleRight",
           @"\uf102", @"angleDoubleUp",
           @"\uf107", @"angleDown",
           @"\uf104", @"angleLeft",
           @"\uf105", @"angleRight",
           @"\uf106", @"angleUp",
           @"\uf179", @"apple",
           @"\uf187", @"archive",
           @"\uf1fe", @"areaChart",
           @"\uf0ab", @"arrowCircleDown",
           @"\uf0a8", @"arrowCircleLeft",
           @"\uf01a", @"arrowCircleODown",
           @"\uf190", @"arrowCircleOLeft",
           @"\uf18e", @"arrowCircleORight",
           @"\uf01b", @"arrowCircleOUp",
           @"\uf0a9", @"arrowCircleRight",
           @"\uf0aa", @"arrowCircleUp",
           @"\uf063", @"arrowDown",
           @"\uf060", @"arrowLeft",
           @"\uf061", @"arrowRight",
           @"\uf062", @"arrowUp",
           @"\uf047", @"arrows",
           @"\uf0b2", @"arrowsAlt",
           @"\uf07e", @"arrowsH",
           @"\uf07d", @"arrowsV",
           @"\uf069", @"asterisk",
           @"\uf1fa", @"at",
           @"\uf1b9", @"automobile",
           @"\uf04a", @"backward",
           @"\uf05e", @"ban",
           @"\uf19c", @"bank",
           @"\uf080", @"barChart",
           @"\uf080", @"barChartO",
           @"\uf02a", @"barcode",
           @"\uf0c9", @"bars",
           @"\uf236", @"bed",
           @"\uf0fc", @"beer",
           @"\uf1b4", @"behance",
           @"\uf1b5", @"behanceSquare",
           @"\uf0f3", @"bell",
           @"\uf0a2", @"bellO",
           @"\uf1f6", @"bellSlash",
           @"\uf1f7", @"bellSlashO",
           @"\uf206", @"bicycle",
           @"\uf1e5", @"binoculars",
           @"\uf1fd", @"birthdayCake",
           @"\uf171", @"bitbucket",
           @"\uf172", @"bitbucketSquare",
           @"\uf15a", @"bitcoin",
           @"\uf032", @"bold",
           @"\uf0e7", @"bolt",
           @"\uf1e2", @"bomb",
           @"\uf02d", @"book",
           @"\uf02e", @"bookmark",
           @"\uf097", @"bookmarkO",
           @"\uf0b1", @"briefcase",
           @"\uf15a", @"btc",
           @"\uf188", @"bug",
           @"\uf1ad", @"building",
           @"\uf0f7", @"buildingO",
           @"\uf0a1", @"bullhorn",
           @"\uf140", @"bullseye",
           @"\uf207", @"bus",
           @"\uf20d", @"buysellads",
           @"\uf1ba", @"cab",
           @"\uf1ec", @"calculator",
           @"\uf073", @"calendar",
           @"\uf133", @"calendarO",
           @"\uf030", @"camera",
           @"\uf083", @"cameraRetro",
           @"\uf1b9", @"car",
           @"\uf0d7", @"caretDown",
           @"\uf0d9", @"caretLeft",
           @"\uf0da", @"caretRight",
           @"\uf150", @"caretSquareODown",
           @"\uf191", @"caretSquareOLeft",
           @"\uf152", @"caretSquareORight",
           @"\uf151", @"caretSquareOUp",
           @"\uf0d8", @"caretUp",
           @"\uf218", @"cartArrowDown",
           @"\uf217", @"cartPlus",
           @"\uf20a", @"cc",
           @"\uf1f3", @"ccAmex",
           @"\uf1f2", @"ccDiscover",
           @"\uf1f1", @"ccMastercard",
           @"\uf1f4", @"ccPaypal",
           @"\uf1f5", @"ccStripe",
           @"\uf1f0", @"ccVisa",
           @"\uf0a3", @"certificate",
           @"\uf0c1", @"chain",
           @"\uf127", @"chainBroken",
           @"\uf00c", @"check",
           @"\uf058", @"checkCircle",
           @"\uf05d", @"checkCircleO",
           @"\uf14a", @"checkSquare",
           @"\uf046", @"checkSquareO",
           @"\uf13a", @"chevronCircleDown",
           @"\uf137", @"chevronCircleLeft",
           @"\uf138", @"chevronCircleRight",
           @"\uf139", @"chevronCircleUp",
           @"\uf078", @"chevronDown",
           @"\uf053", @"chevronLeft",
           @"\uf054", @"chevronRight",
           @"\uf077", @"chevronUp",
           @"\uf1ae", @"child",
           @"\uf111", @"circle",
           @"\uf10c", @"circleO",
           @"\uf1ce", @"circleONotch",
           @"\uf1db", @"circleThin",
           @"\uf0ea", @"clipboard",
           @"\uf017", @"clockO",
           @"\uf00d", @"close",
           @"\uf0c2", @"cloud",
           @"\uf0ed", @"cloudDownload",
           @"\uf0ee", @"cloudUpload",
           @"\uf157", @"cny",
           @"\uf121", @"code",
           @"\uf126", @"codeFork",
           @"\uf1cb", @"codepen",
           @"\uf0f4", @"coffee",
           @"\uf013", @"cog",
           @"\uf085", @"cogs",
           @"\uf0db", @"columns",
           @"\uf075", @"comment",
           @"\uf0e5", @"commentO",
           @"\uf086", @"comments",
           @"\uf0e6", @"commentsO",
           @"\uf14e", @"compass",
           @"\uf066", @"compress",
           @"\uf20e", @"connectdevelop",
           @"\uf0c5", @"copy",
           @"\uf1f9", @"copyright",
           @"\uf09d", @"creditCard",
           @"\uf125", @"crop",
           @"\uf05b", @"crosshairs",
           @"\uf13c", @"css3",
           @"\uf1b2", @"cube",
           @"\uf1b3", @"cubes",
           @"\uf0c4", @"cut",
           @"\uf0f5", @"cutlery",
           @"\uf0e4", @"dashboard",
           @"\uf210", @"dashcube",
           @"\uf1c0", @"database",
           @"\uf03b", @"dedent",
           @"\uf1a5", @"delicious",
           @"\uf108", @"desktop",
           @"\uf1bd", @"deviantart",
           @"\uf219", @"diamond",
           @"\uf1a6", @"digg",
           @"\uf155", @"dollar",
           @"\uf192", @"dotCircleO",
           @"\uf019", @"download",
           @"\uf17d", @"dribbble",
           @"\uf16b", @"dropbox",
           @"\uf1a9", @"drupal",
           @"\uf044", @"edit",
           @"\uf052", @"eject",
           @"\uf141", @"ellipsisH",
           @"\uf142", @"ellipsisV",
           @"\uf1d1", @"empire",
           @"\uf0e0", @"envelope",
           @"\uf003", @"envelopeO",
           @"\uf199", @"envelopeSquare",
           @"\uf12d", @"eraser",
           @"\uf153", @"eur",
           @"\uf153", @"euro",
           @"\uf0ec", @"exchange",
           @"\uf12a", @"exclamation",
           @"\uf06a", @"exclamationCircle",
           @"\uf071", @"exclamationTriangle",
           @"\uf065", @"expand",
           @"\uf08e", @"externalLink",
           @"\uf14c", @"externalLinkSquare",
           @"\uf06e", @"eye",
           @"\uf070", @"eyeSlash",
           @"\uf1fb", @"eyedropper",
           @"\uf09a", @"facebook",
           @"\uf09a", @"facebookF",
           @"\uf230", @"facebookOfficial",
           @"\uf082", @"facebookSquare",
           @"\uf049", @"fastBackward",
           @"\uf050", @"fastForward",
           @"\uf1ac", @"fax",
           @"\uf182", @"female",
           @"\uf0fb", @"fighterJet",
           @"\uf15b", @"file",
           @"\uf1c6", @"fileArchiveO",
           @"\uf1c7", @"fileAudioO",
           @"\uf1c9", @"fileCodeO",
           @"\uf1c3", @"fileExcelO",
           @"\uf1c5", @"fileImageO",
           @"\uf1c8", @"fileMovieO",
           @"\uf016", @"fileO",
           @"\uf1c1", @"filePdfO",
           @"\uf1c5", @"filePhotoO",
           @"\uf1c5", @"filePictureO",
           @"\uf1c4", @"filePowerpointO",
           @"\uf1c7", @"fileSoundO",
           @"\uf15c", @"fileText",
           @"\uf0f6", @"fileTextO",
           @"\uf1c8", @"fileVideoO",
           @"\uf1c2", @"fileWordO",
           @"\uf1c6", @"fileZipO",
           @"\uf0c5", @"filesO",
           @"\uf008", @"film",
           @"\uf0b0", @"filter",
           @"\uf06d", @"fire",
           @"\uf134", @"fireExtinguisher",
           @"\uf024", @"flag",
           @"\uf11e", @"flagCheckered",
           @"\uf11d", @"flagO",
           @"\uf0e7", @"flash",
           @"\uf0c3", @"flask",
           @"\uf16e", @"flickr",
           @"\uf0c7", @"floppyO",
           @"\uf07b", @"folder",
           @"\uf114", @"folderO",
           @"\uf07c", @"folderOpen",
           @"\uf115", @"folderOpenO",
           @"\uf031", @"font",
           @"\uf211", @"forumbee",
           @"\uf04e", @"forward",
           @"\uf180", @"foursquare",
           @"\uf119", @"frownO",
           @"\uf1e3", @"futbolO",
           @"\uf11b", @"gamepad",
           @"\uf0e3", @"gavel",
           @"\uf154", @"gbp",
           @"\uf1d1", @"ge",
           @"\uf013", @"gear",
           @"\uf085", @"gears",
           @"\uf1db", @"genderless",
           @"\uf06b", @"gift",
           @"\uf1d3", @"git",
           @"\uf1d2", @"gitSquare",
           @"\uf09b", @"github",
           @"\uf113", @"githubAlt",
           @"\uf092", @"githubSquare",
           @"\uf184", @"gittip",
           @"\uf000", @"glass",
           @"\uf0ac", @"globe",
           @"\uf1a0", @"google",
           @"\uf0d5", @"googlePlus",
           @"\uf0d4", @"googlePlusSquare",
           @"\uf1ee", @"googleWallet",
           @"\uf19d", @"graduationCap",
           @"\uf184", @"gratipay",
           @"\uf0c0", @"group",
           @"\uf0fd", @"hSquare",
           @"\uf1d4", @"hackerNews",
           @"\uf0a7", @"handODown",
           @"\uf0a5", @"handOLeft",
           @"\uf0a4", @"handORight",
           @"\uf0a6", @"handOUp",
           @"\uf0a0", @"hddO",
           @"\uf1dc", @"header",
           @"\uf025", @"headphones",
           @"\uf004", @"heart",
           @"\uf08a", @"heartO",
           @"\uf21e", @"heartbeat",
           @"\uf1da", @"history",
           @"\uf015", @"home",
           @"\uf0f8", @"hospitalO",
           @"\uf236", @"hotel",
           @"\uf13b", @"html5",
           @"\uf20b", @"ils",
           @"\uf03e", @"image",
           @"\uf01c", @"inbox",
           @"\uf03c", @"indent",
           @"\uf129", @"info",
           @"\uf05a", @"infoCircle",
           @"\uf156", @"inr",
           @"\uf16d", @"instagram",
           @"\uf19c", @"institution",
           @"\uf208", @"ioxhost",
           @"\uf033", @"italic",
           @"\uf1aa", @"joomla",
           @"\uf157", @"jpy",
           @"\uf1cc", @"jsfiddle",
           @"\uf084", @"key",
           @"\uf11c", @"keyboardO",
           @"\uf159", @"krw",
           @"\uf1ab", @"language",
           @"\uf109", @"laptop",
           @"\uf202", @"lastfm",
           @"\uf203", @"lastfmSquare",
           @"\uf06c", @"leaf",
           @"\uf212", @"leanpub",
           @"\uf0e3", @"legal",
           @"\uf094", @"lemonO",
           @"\uf149", @"levelDown",
           @"\uf148", @"levelUp",
           @"\uf1cd", @"lifeBouy",
           @"\uf1cd", @"lifeBuoy",
           @"\uf1cd", @"lifeRing",
           @"\uf1cd", @"lifeSaver",
           @"\uf0eb", @"lightbulbO",
           @"\uf201", @"lineChart",
           @"\uf0c1", @"link",
           @"\uf0e1", @"linkedin",
           @"\uf08c", @"linkedinSquare",
           @"\uf17c", @"linux",
           @"\uf03a", @"list",
           @"\uf022", @"listAlt",
           @"\uf0cb", @"listOl",
           @"\uf0ca", @"listUl",
           @"\uf124", @"locationArrow",
           @"\uf023", @"lock",
           @"\uf175", @"longArrowDown",
           @"\uf177", @"longArrowLeft",
           @"\uf178", @"longArrowRight",
           @"\uf176", @"longArrowUp",
           @"\uf0d0", @"magic",
           @"\uf076", @"magnet",
           @"\uf064", @"mailForward",
           @"\uf112", @"mailReply",
           @"\uf122", @"mailReplyAll",
           @"\uf183", @"male",
           @"\uf041", @"mapMarker",
           @"\uf222", @"mars",
           @"\uf227", @"marsDouble",
           @"\uf229", @"marsStroke",
           @"\uf22b", @"marsStrokeH",
           @"\uf22a", @"marsStrokeV",
           @"\uf136", @"maxcdn",
           @"\uf20c", @"meanpath",
           @"\uf23a", @"medium",
           @"\uf0fa", @"medkit",
           @"\uf11a", @"mehO",
           @"\uf223", @"mercury",
           @"\uf130", @"microphone",
           @"\uf131", @"microphoneSlash",
           @"\uf068", @"minus",
           @"\uf056", @"minusCircle",
           @"\uf146", @"minusSquare",
           @"\uf147", @"minusSquareO",
           @"\uf10b", @"mobile",
           @"\uf10b", @"mobilePhone",
           @"\uf0d6", @"money",
           @"\uf186", @"moonO",
           @"\uf19d", @"mortarBoard",
           @"\uf21c", @"motorcycle",
           @"\uf001", @"music",
           @"\uf0c9", @"navicon",
           @"\uf22c", @"neuter",
           @"\uf1ea", @"newspaperO",
           @"\uf19b", @"openid",
           @"\uf03b", @"outdent",
           @"\uf18c", @"pagelines",
           @"\uf1fc", @"paintBrush",
           @"\uf1d8", @"paperPlane",
           @"\uf1d9", @"paperPlaneO",
           @"\uf0c6", @"paperclip",
           @"\uf1dd", @"paragraph",
           @"\uf0ea", @"paste",
           @"\uf04c", @"pause",
           @"\uf1b0", @"paw",
           @"\uf1ed", @"paypal",
           @"\uf040", @"pencil",
           @"\uf14b", @"pencilSquare",
           @"\uf044", @"pencilSquareO",
           @"\uf095", @"phone",
           @"\uf098", @"phoneSquare",
           @"\uf03e", @"photo",
           @"\uf03e", @"pictureO",
           @"\uf200", @"pieChart",
           @"\uf1a7", @"piedPiper",
           @"\uf1a8", @"piedPiperAlt",
           @"\uf0d2", @"pinterest",
           @"\uf231", @"pinterestP",
           @"\uf0d3", @"pinterestSquare",
           @"\uf072", @"plane",
           @"\uf04b", @"play",
           @"\uf144", @"playCircle",
           @"\uf01d", @"playCircleO",
           @"\uf1e6", @"plug",
           @"\uf067", @"plus",
           @"\uf055", @"plusCircle",
           @"\uf0fe", @"plusSquare",
           @"\uf196", @"plusSquareO",
           @"\uf011", @"powerOff",
           @"\uf02f", @"print",
           @"\uf12e", @"puzzlePiece",
           @"\uf1d6", @"qq",
           @"\uf029", @"qrcode",
           @"\uf128", @"question",
           @"\uf059", @"questionCircle",
           @"\uf10d", @"quoteLeft",
           @"\uf10e", @"quoteRight",
           @"\uf1d0", @"ra",
           @"\uf074", @"random",
           @"\uf1d0", @"rebel",
           @"\uf1b8", @"recycle",
           @"\uf1a1", @"reddit",
           @"\uf1a2", @"redditSquare",
           @"\uf021", @"refresh",
           @"\uf00d", @"remove",
           @"\uf18b", @"renren",
           @"\uf0c9", @"reorder",
           @"\uf01e", @"repeat",
           @"\uf112", @"reply",
           @"\uf122", @"replyAll",
           @"\uf079", @"retweet",
           @"\uf157", @"rmb",
           @"\uf018", @"road",
           @"\uf135", @"rocket",
           @"\uf0e2", @"rotateLeft",
           @"\uf01e", @"rotateRight",
           @"\uf158", @"rouble",
           @"\uf09e", @"rss",
           @"\uf143", @"rssSquare",
           @"\uf158", @"rub",
           @"\uf158", @"ruble",
           @"\uf156", @"rupee",
           @"\uf0c7", @"save",
           @"\uf0c4", @"scissors",
           @"\uf002", @"search",
           @"\uf010", @"searchMinus",
           @"\uf00e", @"searchPlus",
           @"\uf213", @"sellsy",
           @"\uf1d8", @"send",
           @"\uf1d9", @"sendO",
           @"\uf233", @"server",
           @"\uf064", @"share",
           @"\uf1e0", @"shareAlt",
           @"\uf1e1", @"shareAltSquare",
           @"\uf14d", @"shareSquare",
           @"\uf045", @"shareSquareO",
           @"\uf20b", @"shekel",
           @"\uf20b", @"sheqel",
           @"\uf132", @"shield",
           @"\uf21a", @"ship",
           @"\uf214", @"shirtsinbulk",
           @"\uf07a", @"shoppingCart",
           @"\uf090", @"signIn",
           @"\uf08b", @"signOut",
           @"\uf012", @"signal",
           @"\uf215", @"simplybuilt",
           @"\uf0e8", @"sitemap",
           @"\uf216", @"skyatlas",
           @"\uf17e", @"skype",
           @"\uf198", @"slack",
           @"\uf1de", @"sliders",
           @"\uf1e7", @"slideshare",
           @"\uf118", @"smileO",
           @"\uf1e3", @"soccerBallO",
           @"\uf0dc", @"sort",
           @"\uf15d", @"sortAlphaAsc",
           @"\uf15e", @"sortAlphaDesc",
           @"\uf160", @"sortAmountAsc",
           @"\uf161", @"sortAmountDesc",
           @"\uf0de", @"sortAsc",
           @"\uf0dd", @"sortDesc",
           @"\uf0dd", @"sortDown",
           @"\uf162", @"sortNumericAsc",
           @"\uf163", @"sortNumericDesc",
           @"\uf0de", @"sortUp",
           @"\uf1be", @"soundcloud",
           @"\uf197", @"spaceShuttle",
           @"\uf110", @"spinner",
           @"\uf1b1", @"spoon",
           @"\uf1bc", @"spotify",
           @"\uf0c8", @"square",
           @"\uf096", @"squareO",
           @"\uf18d", @"stackExchange",
           @"\uf16c", @"stackOverflow",
           @"\uf005", @"star",
           @"\uf089", @"starHalf",
           @"\uf123", @"starHalfEmpty",
           @"\uf123", @"starHalfFull",
           @"\uf123", @"starHalfO",
           @"\uf006", @"starO",
           @"\uf1b6", @"steam",
           @"\uf1b7", @"steamSquare",
           @"\uf048", @"stepBackward",
           @"\uf051", @"stepForward",
           @"\uf0f1", @"stethoscope",
           @"\uf04d", @"stop",
           @"\uf21d", @"streetView",
           @"\uf0cc", @"strikethrough",
           @"\uf1a4", @"stumbleupon",
           @"\uf1a3", @"stumbleuponCircle",
           @"\uf12c", @"subscript",
           @"\uf239", @"subway",
           @"\uf0f2", @"suitcase",
           @"\uf185", @"sunO",
           @"\uf12b", @"superscript",
           @"\uf1cd", @"support",
           @"\uf0ce", @"table",
           @"\uf10a", @"tablet",
           @"\uf0e4", @"tachometer",
           @"\uf02b", @"tag",
           @"\uf02c", @"tags",
           @"\uf0ae", @"tasks",
           @"\uf1ba", @"taxi",
           @"\uf1d5", @"tencentWeibo",
           @"\uf120", @"terminal",
           @"\uf034", @"textHeight",
           @"\uf035", @"textWidth",
           @"\uf00a", @"th",
           @"\uf009", @"thLarge",
           @"\uf00b", @"thList",
           @"\uf08d", @"thumbTack",
           @"\uf165", @"thumbsDown",
           @"\uf088", @"thumbsODown",
           @"\uf087", @"thumbsOUp",
           @"\uf164", @"thumbsUp",
           @"\uf145", @"ticket",
           @"\uf00d", @"times",
           @"\uf057", @"timesCircle",
           @"\uf05c", @"timesCircleO",
           @"\uf043", @"tint",
           @"\uf150", @"toggleDown",
           @"\uf191", @"toggleLeft",
           @"\uf204", @"toggleOff",
           @"\uf205", @"toggleOn",
           @"\uf152", @"toggleRight",
           @"\uf151", @"toggleUp",
           @"\uf238", @"train",
           @"\uf224", @"transgender",
           @"\uf225", @"transgenderAlt",
           @"\uf1f8", @"trash",
           @"\uf014", @"trashO",
           @"\uf1bb", @"tree",
           @"\uf181", @"trello",
           @"\uf091", @"trophy",
           @"\uf0d1", @"truck",
           @"\uf195", @"try",
           @"\uf1e4", @"tty",
           @"\uf173", @"tumblr",
           @"\uf174", @"tumblrSquare",
           @"\uf195", @"turkishLira",
           @"\uf1e8", @"twitch",
           @"\uf099", @"twitter",
           @"\uf081", @"twitterSquare",
           @"\uf0e9", @"umbrella",
           @"\uf0cd", @"underline",
           @"\uf0e2", @"undo",
           @"\uf19c", @"university",
           @"\uf127", @"unlink",
           @"\uf09c", @"unlock",
           @"\uf13e", @"unlockAlt",
           @"\uf0dc", @"unsorted",
           @"\uf093", @"upload",
           @"\uf155", @"usd",
           @"\uf007", @"user",
           @"\uf0f0", @"userMd",
           @"\uf234", @"userPlus",
           @"\uf21b", @"userSecret",
           @"\uf235", @"userTimes",
           @"\uf0c0", @"users",
           @"\uf221", @"venus",
           @"\uf226", @"venusDouble",
           @"\uf228", @"venusMars",
           @"\uf237", @"viacoin",
           @"\uf03d", @"videoCamera",
           @"\uf194", @"vimeoSquare",
           @"\uf1ca", @"vine",
           @"\uf189", @"vk",
           @"\uf027", @"volumeDown",
           @"\uf026", @"volumeOff",
           @"\uf028", @"volumeUp",
           @"\uf071", @"warning",
           @"\uf1d7", @"wechat",
           @"\uf18a", @"weibo",
           @"\uf1d7", @"weixin",
           @"\uf232", @"whatsapp",
           @"\uf193", @"wheelchair",
           @"\uf1eb", @"wifi",
           @"\uf17a", @"windows",
           @"\uf159", @"won",
           @"\uf19a", @"wordpress",
           @"\uf0ad", @"wrench",
           @"\uf168", @"xing",
           @"\uf169", @"xingSquare",
           @"\uf19e", @"yahoo",
           @"\uf1e9", @"yelp",
           @"\uf157", @"yen",
           @"\uf167", @"youtube",
           @"\uf16a", @"youtubePlay",
           @"\uf166", @"youtubeSquare",
                                 nil];
  });
  return icons;
}

@end
