// This file is autogenerated, see tools/release/version.go

package libkb

// Version is the current version (should be MAJOR.MINOR.PATCH)
const Version = "1.0.6"

// DefaultBuild is the current build number
const DefaultBuild = "1"
