'use strict'
/* @flow */

export const CONFIG_LOADING = 'CONFIG_LOADING'
export const CONFIG_ERRORED = 'CONFIG_ERRORED'
export const CONFIG_LOADED = 'CONFIG_LOADED'

export const DEV_CONFIG_LOADING = 'DEV_CONFIG_LOADING'
export const DEV_CONFIG_LOADED = 'DEV_CONFIG_LOADED'
export const DEV_CONFIG_UPDATE = 'DEV_CONFIG_UPDATE'
export const DEV_CONFIG_SAVED = 'DEV_CONFIG_SAVED'
