'use strict'
/* @flow */

export const INIT_PROFILE = 'INIT_PROFILE'
export const PROFILE_LOADING = 'PROFILE_LOADING'
export const PROFILE_RECEIVED_DISPLAY_KEY = 'PROFILE_RECEIVED_DISPLAY_KEY'
export const PROFILE_LOADED = 'PROFILE_LOADED'
export const PROFILE_CHECKING_NETWORKS = 'PROFILE_CHECKING_NETWORKS'
export const PROFILE_NETWORK_UPDATE = 'PROFILE_NETWORK_UPDATE'
