'use strict'
export const FOLDER_TAB = 'FOLDER_TAB'
export const CHAT_TAB = 'CHAT_TAB'
export const PEOPLE_TAB = 'PEOPLE_TAB'
export const DEVICES_TAB = 'DEVICES_TAB'
export const MORE_TAB = 'MORE_TAB'
