#!/usr/bin/env bash

readonly host_name="com.keybase.kbnm"


detect() {
  whoami="$(whoami)"
  if [[ "$(uname -s)" == "Darwin" ]]; then
    # Mac
    if [[ "$whoami" == "root" ]]; then
      echo "/Library/Google/Chrome/NativeMessagingHosts"
    else
      echo "$HOME/Library/Application Support/Google/Chrome/NativeMessagingHosts"
    fi
  else
    # Linux
    if [[ "$whoami" == "root" ]]; then
      echo "/etc/opt/chrome/native-messaging-hosts"
    else
      echo "$HOME/.config/google-chrome/NativeMessagingHosts"
    fi
  fi
}

install() {
  declare target="$1"

  local target_dir="$(dirname target)"
  if [[ ! -d "$target_dir" ]]; then
    mkdir -p "target_dir"
  fi

  local here="$(dirname $(realpath "$BASH_SOURCE"))"
  local host_path="$(which kbnm || echo "$here/kbnm")"

  echo "Writing: $target"
  cat "$here/host_json.template" \
    | sed "s|@@HOST_PATH@@|$host_path|g" \
    > "$target"

  chmod +r "$target"

  echo "Success: Installed Chrome NativeMessaging whitelist: "$host_path" for $host_name"
}

uninstall() {
  declare target="$1"

  rm "$target" && echo "Removed Chrome NativeMessaging whitelist: $target" || echo "Install not found: $target"
}


main() {
  set -eo pipefail; [[ "$TRACE" ]] && set -x

  declare cmd="$1"
  local target="$(detect)/${host_name}.json"

  if [[ "$cmd" == "uninstall" ]]; then
    uninstall "$target"
  else
    install "$target"
  fi
}


[[ "$0" == "$BASH_SOURCE" ]] && main "$@"
