// NOTE: This file is GENERATED from json files in actions/json. Run 'yarn build-actions' to regenerate
import type * as chat1Types from '@/constants/rpc/rpc-chat-gen'
import type * as keybase1Types from '@/constants/rpc/rpc-gen'
import type * as stellar1Types from '@/constants/rpc/rpc-stellar-gen'

export const resetStore = 'common:resetStore' // not a part of engine-gen but is handled by every reducer. NEVER dispatch this
export const typePrefix = 'engine-gen:' as const

type ActionSpec = {
  chat1ChatUiChatBotCommandsUpdateStatus: {readonly params: chat1Types.RpcIn<'chat.1.chatUi.chatBotCommandsUpdateStatus'> , response: chat1Types.RpcResponse<'chat.1.chatUi.chatBotCommandsUpdateStatus'>},
  chat1ChatUiChatClearWatch: {readonly params: chat1Types.RpcIn<'chat.1.chatUi.chatClearWatch'> , response: chat1Types.RpcResponse<'chat.1.chatUi.chatClearWatch'>},
  chat1ChatUiChatCoinFlipStatus: {readonly params: chat1Types.RpcIn<'chat.1.chatUi.chatCoinFlipStatus'> , response: chat1Types.RpcResponse<'chat.1.chatUi.chatCoinFlipStatus'>},
  chat1ChatUiChatCommandMarkdown: {readonly params: chat1Types.RpcIn<'chat.1.chatUi.chatCommandMarkdown'> , response: chat1Types.RpcResponse<'chat.1.chatUi.chatCommandMarkdown'>},
  chat1ChatUiChatCommandStatus: {readonly params: chat1Types.RpcIn<'chat.1.chatUi.chatCommandStatus'> , response: chat1Types.RpcResponse<'chat.1.chatUi.chatCommandStatus'>},
  chat1ChatUiChatConfirmChannelDelete: {readonly params: chat1Types.RpcIn<'chat.1.chatUi.chatConfirmChannelDelete'> , response: chat1Types.RpcResponse<'chat.1.chatUi.chatConfirmChannelDelete'>},
  chat1ChatUiChatGiphySearchResults: {readonly params: chat1Types.RpcIn<'chat.1.chatUi.chatGiphySearchResults'> , response: chat1Types.RpcResponse<'chat.1.chatUi.chatGiphySearchResults'>},
  chat1ChatUiChatGiphyToggleResultWindow: {readonly params: chat1Types.RpcIn<'chat.1.chatUi.chatGiphyToggleResultWindow'> , response: chat1Types.RpcResponse<'chat.1.chatUi.chatGiphyToggleResultWindow'>},
  chat1ChatUiChatInboxConversation: {readonly params: chat1Types.RpcIn<'chat.1.chatUi.chatInboxConversation'> , response: chat1Types.RpcResponse<'chat.1.chatUi.chatInboxConversation'>},
  chat1ChatUiChatInboxFailed: {readonly params: chat1Types.RpcIn<'chat.1.chatUi.chatInboxFailed'> , response: chat1Types.RpcResponse<'chat.1.chatUi.chatInboxFailed'>},
  chat1ChatUiChatInboxLayout: {readonly params: chat1Types.RpcIn<'chat.1.chatUi.chatInboxLayout'> , response: chat1Types.RpcResponse<'chat.1.chatUi.chatInboxLayout'>},
  chat1ChatUiChatInboxUnverified: {readonly params: chat1Types.RpcIn<'chat.1.chatUi.chatInboxUnverified'> , response: chat1Types.RpcResponse<'chat.1.chatUi.chatInboxUnverified'>},
  chat1ChatUiChatLoadGalleryHit: {readonly params: chat1Types.RpcIn<'chat.1.chatUi.chatLoadGalleryHit'> , response: chat1Types.RpcResponse<'chat.1.chatUi.chatLoadGalleryHit'>},
  chat1ChatUiChatMaybeMentionUpdate: {readonly params: chat1Types.RpcIn<'chat.1.chatUi.chatMaybeMentionUpdate'> , response: chat1Types.RpcResponse<'chat.1.chatUi.chatMaybeMentionUpdate'>},
  chat1ChatUiChatSearchBotHits: {readonly params: chat1Types.RpcIn<'chat.1.chatUi.chatSearchBotHits'> , response: chat1Types.RpcResponse<'chat.1.chatUi.chatSearchBotHits'>},
  chat1ChatUiChatSearchConvHits: {readonly params: chat1Types.RpcIn<'chat.1.chatUi.chatSearchConvHits'> , response: chat1Types.RpcResponse<'chat.1.chatUi.chatSearchConvHits'>},
  chat1ChatUiChatSearchDone: {readonly params: chat1Types.RpcIn<'chat.1.chatUi.chatSearchDone'> , response: chat1Types.RpcResponse<'chat.1.chatUi.chatSearchDone'>},
  chat1ChatUiChatSearchHit: {readonly params: chat1Types.RpcIn<'chat.1.chatUi.chatSearchHit'> , response: chat1Types.RpcResponse<'chat.1.chatUi.chatSearchHit'>},
  chat1ChatUiChatSearchInboxDone: {readonly params: chat1Types.RpcIn<'chat.1.chatUi.chatSearchInboxDone'> , response: chat1Types.RpcResponse<'chat.1.chatUi.chatSearchInboxDone'>},
  chat1ChatUiChatSearchInboxHit: {readonly params: chat1Types.RpcIn<'chat.1.chatUi.chatSearchInboxHit'> , response: chat1Types.RpcResponse<'chat.1.chatUi.chatSearchInboxHit'>},
  chat1ChatUiChatSearchInboxStart: {readonly params: chat1Types.RpcIn<'chat.1.chatUi.chatSearchInboxStart'> , response: chat1Types.RpcResponse<'chat.1.chatUi.chatSearchInboxStart'>},
  chat1ChatUiChatSearchIndexStatus: {readonly params: chat1Types.RpcIn<'chat.1.chatUi.chatSearchIndexStatus'> , response: chat1Types.RpcResponse<'chat.1.chatUi.chatSearchIndexStatus'>},
  chat1ChatUiChatSearchTeamHits: {readonly params: chat1Types.RpcIn<'chat.1.chatUi.chatSearchTeamHits'> , response: chat1Types.RpcResponse<'chat.1.chatUi.chatSearchTeamHits'>},
  chat1ChatUiChatShowManageChannels: {readonly params: chat1Types.RpcIn<'chat.1.chatUi.chatShowManageChannels'> , response: chat1Types.RpcResponse<'chat.1.chatUi.chatShowManageChannels'>},
  chat1ChatUiChatStellarDataConfirm: {readonly params: chat1Types.RpcIn<'chat.1.chatUi.chatStellarDataConfirm'> , response: chat1Types.RpcResponse<'chat.1.chatUi.chatStellarDataConfirm'>},
  chat1ChatUiChatStellarDataError: {readonly params: chat1Types.RpcIn<'chat.1.chatUi.chatStellarDataError'> , response: chat1Types.RpcResponse<'chat.1.chatUi.chatStellarDataError'>},
  chat1ChatUiChatStellarDone: {readonly params: chat1Types.RpcIn<'chat.1.chatUi.chatStellarDone'> , response: chat1Types.RpcResponse<'chat.1.chatUi.chatStellarDone'>},
  chat1ChatUiChatStellarShowConfirm: {readonly params: chat1Types.RpcIn<'chat.1.chatUi.chatStellarShowConfirm'> , response: chat1Types.RpcResponse<'chat.1.chatUi.chatStellarShowConfirm'>},
  chat1ChatUiChatThreadCached: {readonly params: chat1Types.RpcIn<'chat.1.chatUi.chatThreadCached'> , response: chat1Types.RpcResponse<'chat.1.chatUi.chatThreadCached'>},
  chat1ChatUiChatThreadFull: {readonly params: chat1Types.RpcIn<'chat.1.chatUi.chatThreadFull'> , response: chat1Types.RpcResponse<'chat.1.chatUi.chatThreadFull'>},
  chat1ChatUiChatThreadStatus: {readonly params: chat1Types.RpcIn<'chat.1.chatUi.chatThreadStatus'> , response: chat1Types.RpcResponse<'chat.1.chatUi.chatThreadStatus'>},
  chat1ChatUiChatWatchPosition: {readonly params: chat1Types.RpcIn<'chat.1.chatUi.chatWatchPosition'> , response: chat1Types.RpcResponse<'chat.1.chatUi.chatWatchPosition'>},
  chat1ChatUiTriggerContactSync: {readonly params: chat1Types.RpcIn<'chat.1.chatUi.triggerContactSync'> , response: chat1Types.RpcResponse<'chat.1.chatUi.triggerContactSync'>},
  chat1NotifyChatChatArchiveComplete: {readonly params: chat1Types.RpcIn<'chat.1.NotifyChat.ChatArchiveComplete'> },
  chat1NotifyChatChatArchiveProgress: {readonly params: chat1Types.RpcIn<'chat.1.NotifyChat.ChatArchiveProgress'> },
  chat1NotifyChatChatAttachmentDownloadComplete: {readonly params: chat1Types.RpcIn<'chat.1.NotifyChat.ChatAttachmentDownloadComplete'> },
  chat1NotifyChatChatAttachmentDownloadProgress: {readonly params: chat1Types.RpcIn<'chat.1.NotifyChat.ChatAttachmentDownloadProgress'> },
  chat1NotifyChatChatAttachmentUploadProgress: {readonly params: chat1Types.RpcIn<'chat.1.NotifyChat.ChatAttachmentUploadProgress'> },
  chat1NotifyChatChatAttachmentUploadStart: {readonly params: chat1Types.RpcIn<'chat.1.NotifyChat.ChatAttachmentUploadStart'> },
  chat1NotifyChatChatConvUpdate: {readonly params: chat1Types.RpcIn<'chat.1.NotifyChat.ChatConvUpdate'> },
  chat1NotifyChatChatIdentifyUpdate: {readonly params: chat1Types.RpcIn<'chat.1.NotifyChat.ChatIdentifyUpdate'> },
  chat1NotifyChatChatInboxStale: {readonly params: chat1Types.RpcIn<'chat.1.NotifyChat.ChatInboxStale'> },
  chat1NotifyChatChatInboxSyncStarted: {readonly params: chat1Types.RpcIn<'chat.1.NotifyChat.ChatInboxSyncStarted'> },
  chat1NotifyChatChatInboxSynced: {readonly params: chat1Types.RpcIn<'chat.1.NotifyChat.ChatInboxSynced'> },
  chat1NotifyChatChatJoinedConversation: {readonly params: chat1Types.RpcIn<'chat.1.NotifyChat.ChatJoinedConversation'> },
  chat1NotifyChatChatKBFSToImpteamUpgrade: {readonly params: chat1Types.RpcIn<'chat.1.NotifyChat.ChatKBFSToImpteamUpgrade'> },
  chat1NotifyChatChatLeftConversation: {readonly params: chat1Types.RpcIn<'chat.1.NotifyChat.ChatLeftConversation'> },
  chat1NotifyChatChatParticipantsInfo: {readonly params: chat1Types.RpcIn<'chat.1.NotifyChat.ChatParticipantsInfo'> },
  chat1NotifyChatChatPaymentInfo: {readonly params: chat1Types.RpcIn<'chat.1.NotifyChat.ChatPaymentInfo'> },
  chat1NotifyChatChatPromptUnfurl: {readonly params: chat1Types.RpcIn<'chat.1.NotifyChat.ChatPromptUnfurl'> },
  chat1NotifyChatChatRequestInfo: {readonly params: chat1Types.RpcIn<'chat.1.NotifyChat.ChatRequestInfo'> },
  chat1NotifyChatChatResetConversation: {readonly params: chat1Types.RpcIn<'chat.1.NotifyChat.ChatResetConversation'> },
  chat1NotifyChatChatSetConvRetention: {readonly params: chat1Types.RpcIn<'chat.1.NotifyChat.ChatSetConvRetention'> },
  chat1NotifyChatChatSetConvSettings: {readonly params: chat1Types.RpcIn<'chat.1.NotifyChat.ChatSetConvSettings'> },
  chat1NotifyChatChatSetTeamRetention: {readonly params: chat1Types.RpcIn<'chat.1.NotifyChat.ChatSetTeamRetention'> },
  chat1NotifyChatChatSubteamRename: {readonly params: chat1Types.RpcIn<'chat.1.NotifyChat.ChatSubteamRename'> },
  chat1NotifyChatChatTLFFinalize: {readonly params: chat1Types.RpcIn<'chat.1.NotifyChat.ChatTLFFinalize'> },
  chat1NotifyChatChatTLFResolve: {readonly params: chat1Types.RpcIn<'chat.1.NotifyChat.ChatTLFResolve'> },
  chat1NotifyChatChatThreadsStale: {readonly params: chat1Types.RpcIn<'chat.1.NotifyChat.ChatThreadsStale'> },
  chat1NotifyChatChatTypingUpdate: {readonly params: chat1Types.RpcIn<'chat.1.NotifyChat.ChatTypingUpdate'> },
  chat1NotifyChatChatWelcomeMessageLoaded: {readonly params: chat1Types.RpcIn<'chat.1.NotifyChat.ChatWelcomeMessageLoaded'> },
  chat1NotifyChatNewChatActivity: {readonly params: chat1Types.RpcIn<'chat.1.NotifyChat.NewChatActivity'> },
  keybase1GpgUiConfirmDuplicateKeyChosen: {readonly params: keybase1Types.RpcIn<'keybase.1.gpgUi.confirmDuplicateKeyChosen'> , response: keybase1Types.RpcResponse<'keybase.1.gpgUi.confirmDuplicateKeyChosen'>},
  keybase1GpgUiConfirmImportSecretToExistingKey: {readonly params: keybase1Types.RpcIn<'keybase.1.gpgUi.confirmImportSecretToExistingKey'> , response: keybase1Types.RpcResponse<'keybase.1.gpgUi.confirmImportSecretToExistingKey'>},
  keybase1GpgUiGetTTY: {readonly params: keybase1Types.RpcIn<'keybase.1.gpgUi.getTTY'> , response: keybase1Types.RpcResponse<'keybase.1.gpgUi.getTTY'>},
  keybase1GpgUiSelectKey: {readonly params: keybase1Types.RpcIn<'keybase.1.gpgUi.selectKey'> , response: keybase1Types.RpcResponse<'keybase.1.gpgUi.selectKey'>},
  keybase1GpgUiSelectKeyAndPushOption: {readonly params: keybase1Types.RpcIn<'keybase.1.gpgUi.selectKeyAndPushOption'> , response: keybase1Types.RpcResponse<'keybase.1.gpgUi.selectKeyAndPushOption'>},
  keybase1GpgUiSign: {readonly params: keybase1Types.RpcIn<'keybase.1.gpgUi.sign'> , response: keybase1Types.RpcResponse<'keybase.1.gpgUi.sign'>},
  keybase1GpgUiWantToAddGPGKey: {readonly params: keybase1Types.RpcIn<'keybase.1.gpgUi.wantToAddGPGKey'> , response: keybase1Types.RpcResponse<'keybase.1.gpgUi.wantToAddGPGKey'>},
  keybase1GregorUIPushOutOfBandMessages: {readonly params: keybase1Types.RpcIn<'keybase.1.gregorUI.pushOutOfBandMessages'> , response: keybase1Types.RpcResponse<'keybase.1.gregorUI.pushOutOfBandMessages'>},
  keybase1GregorUIPushState: {readonly params: keybase1Types.RpcIn<'keybase.1.gregorUI.pushState'> , response: keybase1Types.RpcResponse<'keybase.1.gregorUI.pushState'>},
  keybase1HomeUIHomeUIRefresh: {readonly params: keybase1Types.RpcIn<'keybase.1.homeUI.homeUIRefresh'> , response: keybase1Types.RpcResponse<'keybase.1.homeUI.homeUIRefresh'>},
  keybase1Identify3UiIdentify3Result: {readonly params: keybase1Types.RpcIn<'keybase.1.identify3Ui.identify3Result'> , response: keybase1Types.RpcResponse<'keybase.1.identify3Ui.identify3Result'>},
  keybase1Identify3UiIdentify3ShowTracker: {readonly params: keybase1Types.RpcIn<'keybase.1.identify3Ui.identify3ShowTracker'> , response: keybase1Types.RpcResponse<'keybase.1.identify3Ui.identify3ShowTracker'>},
  keybase1Identify3UiIdentify3Summary: {readonly params: keybase1Types.RpcIn<'keybase.1.identify3Ui.identify3Summary'> , response: keybase1Types.RpcResponse<'keybase.1.identify3Ui.identify3Summary'>},
  keybase1Identify3UiIdentify3TrackerTimedOut: {readonly params: keybase1Types.RpcIn<'keybase.1.identify3Ui.identify3TrackerTimedOut'> , response: keybase1Types.RpcResponse<'keybase.1.identify3Ui.identify3TrackerTimedOut'>},
  keybase1Identify3UiIdentify3UpdateRow: {readonly params: keybase1Types.RpcIn<'keybase.1.identify3Ui.identify3UpdateRow'> , response: keybase1Types.RpcResponse<'keybase.1.identify3Ui.identify3UpdateRow'>},
  keybase1Identify3UiIdentify3UpdateUserCard: {readonly params: keybase1Types.RpcIn<'keybase.1.identify3Ui.identify3UpdateUserCard'> , response: keybase1Types.RpcResponse<'keybase.1.identify3Ui.identify3UpdateUserCard'>},
  keybase1Identify3UiIdentify3UserReset: {readonly params: keybase1Types.RpcIn<'keybase.1.identify3Ui.identify3UserReset'> , response: keybase1Types.RpcResponse<'keybase.1.identify3Ui.identify3UserReset'>},
  keybase1IdentifyUiCancel: {readonly params: keybase1Types.RpcIn<'keybase.1.identifyUi.cancel'> , response: keybase1Types.RpcResponse<'keybase.1.identifyUi.cancel'>},
  keybase1IdentifyUiConfirm: {readonly params: keybase1Types.RpcIn<'keybase.1.identifyUi.confirm'> , response: keybase1Types.RpcResponse<'keybase.1.identifyUi.confirm'>},
  keybase1IdentifyUiDelegateIdentifyUI: {readonly params: keybase1Types.RpcIn<'keybase.1.identifyUi.delegateIdentifyUI'> , response: keybase1Types.RpcResponse<'keybase.1.identifyUi.delegateIdentifyUI'>},
  keybase1IdentifyUiDismiss: {readonly params: keybase1Types.RpcIn<'keybase.1.identifyUi.dismiss'> , response: keybase1Types.RpcResponse<'keybase.1.identifyUi.dismiss'>},
  keybase1IdentifyUiDisplayCryptocurrency: {readonly params: keybase1Types.RpcIn<'keybase.1.identifyUi.displayCryptocurrency'> , response: keybase1Types.RpcResponse<'keybase.1.identifyUi.displayCryptocurrency'>},
  keybase1IdentifyUiDisplayKey: {readonly params: keybase1Types.RpcIn<'keybase.1.identifyUi.displayKey'> , response: keybase1Types.RpcResponse<'keybase.1.identifyUi.displayKey'>},
  keybase1IdentifyUiDisplayStellarAccount: {readonly params: keybase1Types.RpcIn<'keybase.1.identifyUi.displayStellarAccount'> , response: keybase1Types.RpcResponse<'keybase.1.identifyUi.displayStellarAccount'>},
  keybase1IdentifyUiDisplayTLFCreateWithInvite: {readonly params: keybase1Types.RpcIn<'keybase.1.identifyUi.displayTLFCreateWithInvite'> , response: keybase1Types.RpcResponse<'keybase.1.identifyUi.displayTLFCreateWithInvite'>},
  keybase1IdentifyUiDisplayTrackStatement: {readonly params: keybase1Types.RpcIn<'keybase.1.identifyUi.displayTrackStatement'> , response: keybase1Types.RpcResponse<'keybase.1.identifyUi.displayTrackStatement'>},
  keybase1IdentifyUiDisplayUserCard: {readonly params: keybase1Types.RpcIn<'keybase.1.identifyUi.displayUserCard'> , response: keybase1Types.RpcResponse<'keybase.1.identifyUi.displayUserCard'>},
  keybase1IdentifyUiFinish: {readonly params: keybase1Types.RpcIn<'keybase.1.identifyUi.finish'> , response: keybase1Types.RpcResponse<'keybase.1.identifyUi.finish'>},
  keybase1IdentifyUiFinishSocialProofCheck: {readonly params: keybase1Types.RpcIn<'keybase.1.identifyUi.finishSocialProofCheck'> , response: keybase1Types.RpcResponse<'keybase.1.identifyUi.finishSocialProofCheck'>},
  keybase1IdentifyUiFinishWebProofCheck: {readonly params: keybase1Types.RpcIn<'keybase.1.identifyUi.finishWebProofCheck'> , response: keybase1Types.RpcResponse<'keybase.1.identifyUi.finishWebProofCheck'>},
  keybase1IdentifyUiLaunchNetworkChecks: {readonly params: keybase1Types.RpcIn<'keybase.1.identifyUi.launchNetworkChecks'> , response: keybase1Types.RpcResponse<'keybase.1.identifyUi.launchNetworkChecks'>},
  keybase1IdentifyUiReportLastTrack: {readonly params: keybase1Types.RpcIn<'keybase.1.identifyUi.reportLastTrack'> , response: keybase1Types.RpcResponse<'keybase.1.identifyUi.reportLastTrack'>},
  keybase1IdentifyUiReportTrackToken: {readonly params: keybase1Types.RpcIn<'keybase.1.identifyUi.reportTrackToken'> , response: keybase1Types.RpcResponse<'keybase.1.identifyUi.reportTrackToken'>},
  keybase1IdentifyUiStart: {readonly params: keybase1Types.RpcIn<'keybase.1.identifyUi.start'> , response: keybase1Types.RpcResponse<'keybase.1.identifyUi.start'>},
  keybase1LogUiLog: {readonly params: keybase1Types.RpcIn<'keybase.1.logUi.log'> , response: keybase1Types.RpcResponse<'keybase.1.logUi.log'>},
  keybase1LoginUiChooseDeviceToRecoverWith: {readonly params: keybase1Types.RpcIn<'keybase.1.loginUi.chooseDeviceToRecoverWith'> , response: keybase1Types.RpcResponse<'keybase.1.loginUi.chooseDeviceToRecoverWith'>},
  keybase1LoginUiDisplayPaperKeyPhrase: {readonly params: keybase1Types.RpcIn<'keybase.1.loginUi.displayPaperKeyPhrase'> , response: keybase1Types.RpcResponse<'keybase.1.loginUi.displayPaperKeyPhrase'>},
  keybase1LoginUiDisplayPrimaryPaperKey: {readonly params: keybase1Types.RpcIn<'keybase.1.loginUi.displayPrimaryPaperKey'> , response: keybase1Types.RpcResponse<'keybase.1.loginUi.displayPrimaryPaperKey'>},
  keybase1LoginUiDisplayResetMessage: {readonly params: keybase1Types.RpcIn<'keybase.1.loginUi.displayResetMessage'> , response: keybase1Types.RpcResponse<'keybase.1.loginUi.displayResetMessage'>},
  keybase1LoginUiDisplayResetProgress: {readonly params: keybase1Types.RpcIn<'keybase.1.loginUi.displayResetProgress'> , response: keybase1Types.RpcResponse<'keybase.1.loginUi.displayResetProgress'>},
  keybase1LoginUiExplainDeviceRecovery: {readonly params: keybase1Types.RpcIn<'keybase.1.loginUi.explainDeviceRecovery'> , response: keybase1Types.RpcResponse<'keybase.1.loginUi.explainDeviceRecovery'>},
  keybase1LoginUiGetEmailOrUsername: {readonly params: keybase1Types.RpcIn<'keybase.1.loginUi.getEmailOrUsername'> , response: keybase1Types.RpcResponse<'keybase.1.loginUi.getEmailOrUsername'>},
  keybase1LoginUiPromptPassphraseRecovery: {readonly params: keybase1Types.RpcIn<'keybase.1.loginUi.promptPassphraseRecovery'> , response: keybase1Types.RpcResponse<'keybase.1.loginUi.promptPassphraseRecovery'>},
  keybase1LoginUiPromptResetAccount: {readonly params: keybase1Types.RpcIn<'keybase.1.loginUi.promptResetAccount'> , response: keybase1Types.RpcResponse<'keybase.1.loginUi.promptResetAccount'>},
  keybase1LoginUiPromptRevokePaperKeys: {readonly params: keybase1Types.RpcIn<'keybase.1.loginUi.promptRevokePaperKeys'> , response: keybase1Types.RpcResponse<'keybase.1.loginUi.promptRevokePaperKeys'>},
  keybase1LogsendPrepareLogsend: {readonly params: keybase1Types.RpcIn<'keybase.1.logsend.prepareLogsend'> , response: keybase1Types.RpcResponse<'keybase.1.logsend.prepareLogsend'>},
  keybase1NotifyAppExit: {readonly params: keybase1Types.RpcIn<'keybase.1.NotifyApp.exit'> , response: keybase1Types.RpcResponse<'keybase.1.NotifyApp.exit'>},
  keybase1NotifyAuditBoxAuditError: {readonly params: keybase1Types.RpcIn<'keybase.1.NotifyAudit.boxAuditError'> },
  keybase1NotifyAuditRootAuditError: {readonly params: keybase1Types.RpcIn<'keybase.1.NotifyAudit.rootAuditError'> },
  keybase1NotifyBadgesBadgeState: {readonly params: keybase1Types.RpcIn<'keybase.1.NotifyBadges.badgeState'> },
  keybase1NotifyCanUserPerformCanUserPerformChanged: {readonly params: keybase1Types.RpcIn<'keybase.1.NotifyCanUserPerform.canUserPerformChanged'> },
  keybase1NotifyDeviceCloneDeviceCloneCountChanged: {readonly params: keybase1Types.RpcIn<'keybase.1.NotifyDeviceClone.deviceCloneCountChanged'> },
  keybase1NotifyEmailAddressEmailAddressVerified: {readonly params: keybase1Types.RpcIn<'keybase.1.NotifyEmailAddress.emailAddressVerified'> , response: keybase1Types.RpcResponse<'keybase.1.NotifyEmailAddress.emailAddressVerified'>},
  keybase1NotifyEmailAddressEmailsChanged: {readonly params: keybase1Types.RpcIn<'keybase.1.NotifyEmailAddress.emailsChanged'> , response: keybase1Types.RpcResponse<'keybase.1.NotifyEmailAddress.emailsChanged'>},
  keybase1NotifyEphemeralNewTeamEk: {readonly params: keybase1Types.RpcIn<'keybase.1.NotifyEphemeral.newTeamEk'> },
  keybase1NotifyEphemeralNewTeambotEk: {readonly params: keybase1Types.RpcIn<'keybase.1.NotifyEphemeral.newTeambotEk'> , response: keybase1Types.RpcResponse<'keybase.1.NotifyEphemeral.newTeambotEk'>},
  keybase1NotifyEphemeralTeambotEkNeeded: {readonly params: keybase1Types.RpcIn<'keybase.1.NotifyEphemeral.teambotEkNeeded'> , response: keybase1Types.RpcResponse<'keybase.1.NotifyEphemeral.teambotEkNeeded'>},
  keybase1NotifyFSFSActivity: {readonly params: keybase1Types.RpcIn<'keybase.1.NotifyFS.FSActivity'> },
  keybase1NotifyFSFSEditListResponse: {readonly params: keybase1Types.RpcIn<'keybase.1.NotifyFS.FSEditListResponse'> , response: keybase1Types.RpcResponse<'keybase.1.NotifyFS.FSEditListResponse'>},
  keybase1NotifyFSFSFavoritesChanged: {readonly params: keybase1Types.RpcIn<'keybase.1.NotifyFS.FSFavoritesChanged'> , response: keybase1Types.RpcResponse<'keybase.1.NotifyFS.FSFavoritesChanged'>},
  keybase1NotifyFSFSOnlineStatusChanged: {readonly params: keybase1Types.RpcIn<'keybase.1.NotifyFS.FSOnlineStatusChanged'> , response: keybase1Types.RpcResponse<'keybase.1.NotifyFS.FSOnlineStatusChanged'>},
  keybase1NotifyFSFSOverallSyncStatusChanged: {readonly params: keybase1Types.RpcIn<'keybase.1.NotifyFS.FSOverallSyncStatusChanged'> , response: keybase1Types.RpcResponse<'keybase.1.NotifyFS.FSOverallSyncStatusChanged'>},
  keybase1NotifyFSFSPathUpdated: {readonly params: keybase1Types.RpcIn<'keybase.1.NotifyFS.FSPathUpdated'> },
  keybase1NotifyFSFSSubscriptionNotify: {readonly params: keybase1Types.RpcIn<'keybase.1.NotifyFS.FSSubscriptionNotify'> , response: keybase1Types.RpcResponse<'keybase.1.NotifyFS.FSSubscriptionNotify'>},
  keybase1NotifyFSFSSubscriptionNotifyPath: {readonly params: keybase1Types.RpcIn<'keybase.1.NotifyFS.FSSubscriptionNotifyPath'> , response: keybase1Types.RpcResponse<'keybase.1.NotifyFS.FSSubscriptionNotifyPath'>},
  keybase1NotifyFSFSSyncActivity: {readonly params: keybase1Types.RpcIn<'keybase.1.NotifyFS.FSSyncActivity'> , response: keybase1Types.RpcResponse<'keybase.1.NotifyFS.FSSyncActivity'>},
  keybase1NotifyFSFSSyncStatusResponse: {readonly params: keybase1Types.RpcIn<'keybase.1.NotifyFS.FSSyncStatusResponse'> , response: keybase1Types.RpcResponse<'keybase.1.NotifyFS.FSSyncStatusResponse'>},
  keybase1NotifyFavoritesFavoritesChanged: {readonly params: keybase1Types.RpcIn<'keybase.1.NotifyFavorites.favoritesChanged'> },
  keybase1NotifyFeaturedBotsFeaturedBotsUpdate: {readonly params: keybase1Types.RpcIn<'keybase.1.NotifyFeaturedBots.featuredBotsUpdate'> , response: keybase1Types.RpcResponse<'keybase.1.NotifyFeaturedBots.featuredBotsUpdate'>},
  keybase1NotifyInviteFriendsUpdateInviteCounts: {readonly params: keybase1Types.RpcIn<'keybase.1.NotifyInviteFriends.updateInviteCounts'> , response: keybase1Types.RpcResponse<'keybase.1.NotifyInviteFriends.updateInviteCounts'>},
  keybase1NotifyKeyfamilyKeyfamilyChanged: {readonly params: keybase1Types.RpcIn<'keybase.1.NotifyKeyfamily.keyfamilyChanged'> , response: keybase1Types.RpcResponse<'keybase.1.NotifyKeyfamily.keyfamilyChanged'>},
  keybase1NotifyPGPPgpKeyInSecretStoreFile: {readonly params: keybase1Types.RpcIn<'keybase.1.NotifyPGP.pgpKeyInSecretStoreFile'> , response: keybase1Types.RpcResponse<'keybase.1.NotifyPGP.pgpKeyInSecretStoreFile'>},
  keybase1NotifyPaperKeyPaperKeyCached: {readonly params: keybase1Types.RpcIn<'keybase.1.NotifyPaperKey.paperKeyCached'> , response: keybase1Types.RpcResponse<'keybase.1.NotifyPaperKey.paperKeyCached'>},
  keybase1NotifyPhoneNumberPhoneNumbersChanged: {readonly params: keybase1Types.RpcIn<'keybase.1.NotifyPhoneNumber.phoneNumbersChanged'> , response: keybase1Types.RpcResponse<'keybase.1.NotifyPhoneNumber.phoneNumbersChanged'>},
  keybase1NotifyRuntimeStatsRuntimeStatsUpdate: {readonly params: keybase1Types.RpcIn<'keybase.1.NotifyRuntimeStats.runtimeStatsUpdate'> , response: keybase1Types.RpcResponse<'keybase.1.NotifyRuntimeStats.runtimeStatsUpdate'>},
  keybase1NotifySaltpackSaltpackOperationDone: {readonly params: keybase1Types.RpcIn<'keybase.1.NotifySaltpack.saltpackOperationDone'> , response: keybase1Types.RpcResponse<'keybase.1.NotifySaltpack.saltpackOperationDone'>},
  keybase1NotifySaltpackSaltpackOperationProgress: {readonly params: keybase1Types.RpcIn<'keybase.1.NotifySaltpack.saltpackOperationProgress'> , response: keybase1Types.RpcResponse<'keybase.1.NotifySaltpack.saltpackOperationProgress'>},
  keybase1NotifySaltpackSaltpackOperationStart: {readonly params: keybase1Types.RpcIn<'keybase.1.NotifySaltpack.saltpackOperationStart'> , response: keybase1Types.RpcResponse<'keybase.1.NotifySaltpack.saltpackOperationStart'>},
  keybase1NotifyServiceHTTPSrvInfoUpdate: {readonly params: keybase1Types.RpcIn<'keybase.1.NotifyService.HTTPSrvInfoUpdate'> , response: keybase1Types.RpcResponse<'keybase.1.NotifyService.HTTPSrvInfoUpdate'>},
  keybase1NotifyServiceHandleKeybaseLink: {readonly params: keybase1Types.RpcIn<'keybase.1.NotifyService.handleKeybaseLink'> , response: keybase1Types.RpcResponse<'keybase.1.NotifyService.handleKeybaseLink'>},
  keybase1NotifyServiceShutdown: {readonly params: keybase1Types.RpcIn<'keybase.1.NotifyService.shutdown'> , response: keybase1Types.RpcResponse<'keybase.1.NotifyService.shutdown'>},
  keybase1NotifySessionClientOutOfDate: {readonly params: keybase1Types.RpcIn<'keybase.1.NotifySession.clientOutOfDate'> , response: keybase1Types.RpcResponse<'keybase.1.NotifySession.clientOutOfDate'>},
  keybase1NotifySessionLoggedIn: {readonly params: keybase1Types.RpcIn<'keybase.1.NotifySession.loggedIn'> , response: keybase1Types.RpcResponse<'keybase.1.NotifySession.loggedIn'>},
  keybase1NotifySessionLoggedOut: {readonly params: keybase1Types.RpcIn<'keybase.1.NotifySession.loggedOut'> },
  keybase1NotifySimpleFSSimpleFSArchiveStatusChanged: {readonly params: keybase1Types.RpcIn<'keybase.1.NotifySimpleFS.simpleFSArchiveStatusChanged'> , response: keybase1Types.RpcResponse<'keybase.1.NotifySimpleFS.simpleFSArchiveStatusChanged'>},
  keybase1NotifyTeamAvatarUpdated: {readonly params: keybase1Types.RpcIn<'keybase.1.NotifyTeam.avatarUpdated'> , response: keybase1Types.RpcResponse<'keybase.1.NotifyTeam.avatarUpdated'>},
  keybase1NotifyTeamNewlyAddedToTeam: {readonly params: keybase1Types.RpcIn<'keybase.1.NotifyTeam.newlyAddedToTeam'> , response: keybase1Types.RpcResponse<'keybase.1.NotifyTeam.newlyAddedToTeam'>},
  keybase1NotifyTeamTeamAbandoned: {readonly params: keybase1Types.RpcIn<'keybase.1.NotifyTeam.teamAbandoned'> , response: keybase1Types.RpcResponse<'keybase.1.NotifyTeam.teamAbandoned'>},
  keybase1NotifyTeamTeamChangedByID: {readonly params: keybase1Types.RpcIn<'keybase.1.NotifyTeam.teamChangedByID'> , response: keybase1Types.RpcResponse<'keybase.1.NotifyTeam.teamChangedByID'>},
  keybase1NotifyTeamTeamChangedByName: {readonly params: keybase1Types.RpcIn<'keybase.1.NotifyTeam.teamChangedByName'> , response: keybase1Types.RpcResponse<'keybase.1.NotifyTeam.teamChangedByName'>},
  keybase1NotifyTeamTeamDeleted: {readonly params: keybase1Types.RpcIn<'keybase.1.NotifyTeam.teamDeleted'> , response: keybase1Types.RpcResponse<'keybase.1.NotifyTeam.teamDeleted'>},
  keybase1NotifyTeamTeamExit: {readonly params: keybase1Types.RpcIn<'keybase.1.NotifyTeam.teamExit'> , response: keybase1Types.RpcResponse<'keybase.1.NotifyTeam.teamExit'>},
  keybase1NotifyTeamTeamMetadataUpdate: {readonly params: keybase1Types.RpcIn<'keybase.1.NotifyTeam.teamMetadataUpdate'> , response: keybase1Types.RpcResponse<'keybase.1.NotifyTeam.teamMetadataUpdate'>},
  keybase1NotifyTeamTeamRoleMapChanged: {readonly params: keybase1Types.RpcIn<'keybase.1.NotifyTeam.teamRoleMapChanged'> , response: keybase1Types.RpcResponse<'keybase.1.NotifyTeam.teamRoleMapChanged'>},
  keybase1NotifyTeamTeamTreeMembershipsDone: {readonly params: keybase1Types.RpcIn<'keybase.1.NotifyTeam.teamTreeMembershipsDone'> , response: keybase1Types.RpcResponse<'keybase.1.NotifyTeam.teamTreeMembershipsDone'>},
  keybase1NotifyTeamTeamTreeMembershipsPartial: {readonly params: keybase1Types.RpcIn<'keybase.1.NotifyTeam.teamTreeMembershipsPartial'> , response: keybase1Types.RpcResponse<'keybase.1.NotifyTeam.teamTreeMembershipsPartial'>},
  keybase1NotifyTeambotNewTeambotKey: {readonly params: keybase1Types.RpcIn<'keybase.1.NotifyTeambot.newTeambotKey'> },
  keybase1NotifyTeambotTeambotKeyNeeded: {readonly params: keybase1Types.RpcIn<'keybase.1.NotifyTeambot.teambotKeyNeeded'> , response: keybase1Types.RpcResponse<'keybase.1.NotifyTeambot.teambotKeyNeeded'>},
  keybase1NotifyTrackingNotifyUserBlocked: {readonly params: keybase1Types.RpcIn<'keybase.1.NotifyTracking.notifyUserBlocked'> , response: keybase1Types.RpcResponse<'keybase.1.NotifyTracking.notifyUserBlocked'>},
  keybase1NotifyTrackingTrackingChanged: {readonly params: keybase1Types.RpcIn<'keybase.1.NotifyTracking.trackingChanged'> },
  keybase1NotifyTrackingTrackingInfo: {readonly params: keybase1Types.RpcIn<'keybase.1.NotifyTracking.trackingInfo'> , response: keybase1Types.RpcResponse<'keybase.1.NotifyTracking.trackingInfo'>},
  keybase1NotifyUsersIdentifyUpdate: {readonly params: keybase1Types.RpcIn<'keybase.1.NotifyUsers.identifyUpdate'> , response: keybase1Types.RpcResponse<'keybase.1.NotifyUsers.identifyUpdate'>},
  keybase1NotifyUsersPasswordChanged: {readonly params: keybase1Types.RpcIn<'keybase.1.NotifyUsers.passwordChanged'> , response: keybase1Types.RpcResponse<'keybase.1.NotifyUsers.passwordChanged'>},
  keybase1NotifyUsersUserChanged: {readonly params: keybase1Types.RpcIn<'keybase.1.NotifyUsers.userChanged'> },
  keybase1NotifyUsersWebOfTrustChanged: {readonly params: keybase1Types.RpcIn<'keybase.1.NotifyUsers.webOfTrustChanged'> },
  keybase1PgpUiFinished: {readonly params: keybase1Types.RpcIn<'keybase.1.pgpUi.finished'> , response: keybase1Types.RpcResponse<'keybase.1.pgpUi.finished'>},
  keybase1PgpUiKeyGenerated: {readonly params: keybase1Types.RpcIn<'keybase.1.pgpUi.keyGenerated'> , response: keybase1Types.RpcResponse<'keybase.1.pgpUi.keyGenerated'>},
  keybase1PgpUiOutputPGPWarning: {readonly params: keybase1Types.RpcIn<'keybase.1.pgpUi.outputPGPWarning'> , response: keybase1Types.RpcResponse<'keybase.1.pgpUi.outputPGPWarning'>},
  keybase1PgpUiOutputSignatureNonKeybase: {readonly params: keybase1Types.RpcIn<'keybase.1.pgpUi.outputSignatureNonKeybase'> , response: keybase1Types.RpcResponse<'keybase.1.pgpUi.outputSignatureNonKeybase'>},
  keybase1PgpUiOutputSignatureSuccess: {readonly params: keybase1Types.RpcIn<'keybase.1.pgpUi.outputSignatureSuccess'> , response: keybase1Types.RpcResponse<'keybase.1.pgpUi.outputSignatureSuccess'>},
  keybase1PgpUiShouldPushPrivate: {readonly params: keybase1Types.RpcIn<'keybase.1.pgpUi.shouldPushPrivate'> , response: keybase1Types.RpcResponse<'keybase.1.pgpUi.shouldPushPrivate'>},
  keybase1ProveUiChecking: {readonly params: keybase1Types.RpcIn<'keybase.1.proveUi.checking'> , response: keybase1Types.RpcResponse<'keybase.1.proveUi.checking'>},
  keybase1ProveUiContinueChecking: {readonly params: keybase1Types.RpcIn<'keybase.1.proveUi.continueChecking'> , response: keybase1Types.RpcResponse<'keybase.1.proveUi.continueChecking'>},
  keybase1ProveUiDisplayRecheckWarning: {readonly params: keybase1Types.RpcIn<'keybase.1.proveUi.displayRecheckWarning'> , response: keybase1Types.RpcResponse<'keybase.1.proveUi.displayRecheckWarning'>},
  keybase1ProveUiOkToCheck: {readonly params: keybase1Types.RpcIn<'keybase.1.proveUi.okToCheck'> , response: keybase1Types.RpcResponse<'keybase.1.proveUi.okToCheck'>},
  keybase1ProveUiOutputInstructions: {readonly params: keybase1Types.RpcIn<'keybase.1.proveUi.outputInstructions'> , response: keybase1Types.RpcResponse<'keybase.1.proveUi.outputInstructions'>},
  keybase1ProveUiOutputPrechecks: {readonly params: keybase1Types.RpcIn<'keybase.1.proveUi.outputPrechecks'> , response: keybase1Types.RpcResponse<'keybase.1.proveUi.outputPrechecks'>},
  keybase1ProveUiPreProofWarning: {readonly params: keybase1Types.RpcIn<'keybase.1.proveUi.preProofWarning'> , response: keybase1Types.RpcResponse<'keybase.1.proveUi.preProofWarning'>},
  keybase1ProveUiPromptOverwrite: {readonly params: keybase1Types.RpcIn<'keybase.1.proveUi.promptOverwrite'> , response: keybase1Types.RpcResponse<'keybase.1.proveUi.promptOverwrite'>},
  keybase1ProveUiPromptUsername: {readonly params: keybase1Types.RpcIn<'keybase.1.proveUi.promptUsername'> , response: keybase1Types.RpcResponse<'keybase.1.proveUi.promptUsername'>},
  keybase1ProvisionUiChooseDevice: {readonly params: keybase1Types.RpcIn<'keybase.1.provisionUi.chooseDevice'> , response: keybase1Types.RpcResponse<'keybase.1.provisionUi.chooseDevice'>},
  keybase1ProvisionUiChooseDeviceType: {readonly params: keybase1Types.RpcIn<'keybase.1.provisionUi.chooseDeviceType'> , response: keybase1Types.RpcResponse<'keybase.1.provisionUi.chooseDeviceType'>},
  keybase1ProvisionUiChooseGPGMethod: {readonly params: keybase1Types.RpcIn<'keybase.1.provisionUi.chooseGPGMethod'> , response: keybase1Types.RpcResponse<'keybase.1.provisionUi.chooseGPGMethod'>},
  keybase1ProvisionUiChooseProvisioningMethod: {readonly params: keybase1Types.RpcIn<'keybase.1.provisionUi.chooseProvisioningMethod'> , response: keybase1Types.RpcResponse<'keybase.1.provisionUi.chooseProvisioningMethod'>},
  keybase1ProvisionUiDisplayAndPromptSecret: {readonly params: keybase1Types.RpcIn<'keybase.1.provisionUi.DisplayAndPromptSecret'> , response: keybase1Types.RpcResponse<'keybase.1.provisionUi.DisplayAndPromptSecret'>},
  keybase1ProvisionUiDisplaySecretExchanged: {readonly params: keybase1Types.RpcIn<'keybase.1.provisionUi.DisplaySecretExchanged'> , response: keybase1Types.RpcResponse<'keybase.1.provisionUi.DisplaySecretExchanged'>},
  keybase1ProvisionUiPromptNewDeviceName: {readonly params: keybase1Types.RpcIn<'keybase.1.provisionUi.PromptNewDeviceName'> , response: keybase1Types.RpcResponse<'keybase.1.provisionUi.PromptNewDeviceName'>},
  keybase1ProvisionUiProvisioneeSuccess: {readonly params: keybase1Types.RpcIn<'keybase.1.provisionUi.ProvisioneeSuccess'> , response: keybase1Types.RpcResponse<'keybase.1.provisionUi.ProvisioneeSuccess'>},
  keybase1ProvisionUiProvisionerSuccess: {readonly params: keybase1Types.RpcIn<'keybase.1.provisionUi.ProvisionerSuccess'> , response: keybase1Types.RpcResponse<'keybase.1.provisionUi.ProvisionerSuccess'>},
  keybase1ProvisionUiSwitchToGPGSignOK: {readonly params: keybase1Types.RpcIn<'keybase.1.provisionUi.switchToGPGSignOK'> , response: keybase1Types.RpcResponse<'keybase.1.provisionUi.switchToGPGSignOK'>},
  keybase1ReachabilityReachabilityChanged: {readonly params: keybase1Types.RpcIn<'keybase.1.reachability.reachabilityChanged'> },
  keybase1RekeyUIDelegateRekeyUI: {readonly params: keybase1Types.RpcIn<'keybase.1.rekeyUI.delegateRekeyUI'> , response: keybase1Types.RpcResponse<'keybase.1.rekeyUI.delegateRekeyUI'>},
  keybase1RekeyUIRefresh: {readonly params: keybase1Types.RpcIn<'keybase.1.rekeyUI.refresh'> , response: keybase1Types.RpcResponse<'keybase.1.rekeyUI.refresh'>},
  keybase1RekeyUIRekeySendEvent: {readonly params: keybase1Types.RpcIn<'keybase.1.rekeyUI.rekeySendEvent'> , response: keybase1Types.RpcResponse<'keybase.1.rekeyUI.rekeySendEvent'>},
  keybase1SaltpackUiSaltpackPromptForDecrypt: {readonly params: keybase1Types.RpcIn<'keybase.1.saltpackUi.saltpackPromptForDecrypt'> , response: keybase1Types.RpcResponse<'keybase.1.saltpackUi.saltpackPromptForDecrypt'>},
  keybase1SaltpackUiSaltpackVerifyBadSender: {readonly params: keybase1Types.RpcIn<'keybase.1.saltpackUi.saltpackVerifyBadSender'> , response: keybase1Types.RpcResponse<'keybase.1.saltpackUi.saltpackVerifyBadSender'>},
  keybase1SaltpackUiSaltpackVerifySuccess: {readonly params: keybase1Types.RpcIn<'keybase.1.saltpackUi.saltpackVerifySuccess'> , response: keybase1Types.RpcResponse<'keybase.1.saltpackUi.saltpackVerifySuccess'>},
  keybase1SecretUiGetPassphrase: {readonly params: keybase1Types.RpcIn<'keybase.1.secretUi.getPassphrase'> , response: keybase1Types.RpcResponse<'keybase.1.secretUi.getPassphrase'>},
  keybase1StreamUiClose: {readonly params: keybase1Types.RpcIn<'keybase.1.streamUi.close'> , response: keybase1Types.RpcResponse<'keybase.1.streamUi.close'>},
  keybase1StreamUiRead: {readonly params: keybase1Types.RpcIn<'keybase.1.streamUi.read'> , response: keybase1Types.RpcResponse<'keybase.1.streamUi.read'>},
  keybase1StreamUiReset: {readonly params: keybase1Types.RpcIn<'keybase.1.streamUi.reset'> , response: keybase1Types.RpcResponse<'keybase.1.streamUi.reset'>},
  keybase1StreamUiWrite: {readonly params: keybase1Types.RpcIn<'keybase.1.streamUi.write'> , response: keybase1Types.RpcResponse<'keybase.1.streamUi.write'>},
  keybase1TeamsUiConfirmInviteLinkAccept: {readonly params: keybase1Types.RpcIn<'keybase.1.teamsUi.confirmInviteLinkAccept'> , response: keybase1Types.RpcResponse<'keybase.1.teamsUi.confirmInviteLinkAccept'>},
  keybase1TeamsUiConfirmRootTeamDelete: {readonly params: keybase1Types.RpcIn<'keybase.1.teamsUi.confirmRootTeamDelete'> , response: keybase1Types.RpcResponse<'keybase.1.teamsUi.confirmRootTeamDelete'>},
  keybase1TeamsUiConfirmSubteamDelete: {readonly params: keybase1Types.RpcIn<'keybase.1.teamsUi.confirmSubteamDelete'> , response: keybase1Types.RpcResponse<'keybase.1.teamsUi.confirmSubteamDelete'>},
  keybase1UiPromptYesNo: {readonly params: keybase1Types.RpcIn<'keybase.1.ui.promptYesNo'> , response: keybase1Types.RpcResponse<'keybase.1.ui.promptYesNo'>},
  stellar1NotifyAccountDetailsUpdate: {readonly params: stellar1Types.RpcIn<'stellar.1.notify.accountDetailsUpdate'> },
  stellar1NotifyAccountsUpdate: {readonly params: stellar1Types.RpcIn<'stellar.1.notify.accountsUpdate'> },
  stellar1NotifyPaymentNotification: {readonly params: stellar1Types.RpcIn<'stellar.1.notify.paymentNotification'> },
  stellar1NotifyPaymentStatusNotification: {readonly params: stellar1Types.RpcIn<'stellar.1.notify.paymentStatusNotification'> },
  stellar1NotifyPendingPaymentsUpdate: {readonly params: stellar1Types.RpcIn<'stellar.1.notify.pendingPaymentsUpdate'> },
  stellar1NotifyRecentPaymentsUpdate: {readonly params: stellar1Types.RpcIn<'stellar.1.notify.recentPaymentsUpdate'> },
  stellar1NotifyRequestStatusNotification: {readonly params: stellar1Types.RpcIn<'stellar.1.notify.requestStatusNotification'> },
  stellar1UiPaymentReviewed: {readonly params: stellar1Types.RpcIn<'stellar.1.ui.paymentReviewed'> , response: stellar1Types.RpcResponse<'stellar.1.ui.paymentReviewed'>},
}

export const actionTypes = {
  chat1ChatUiChatBotCommandsUpdateStatus: 'engine-gen:chat1ChatUiChatBotCommandsUpdateStatus',
  chat1ChatUiChatClearWatch: 'engine-gen:chat1ChatUiChatClearWatch',
  chat1ChatUiChatCoinFlipStatus: 'engine-gen:chat1ChatUiChatCoinFlipStatus',
  chat1ChatUiChatCommandMarkdown: 'engine-gen:chat1ChatUiChatCommandMarkdown',
  chat1ChatUiChatCommandStatus: 'engine-gen:chat1ChatUiChatCommandStatus',
  chat1ChatUiChatConfirmChannelDelete: 'engine-gen:chat1ChatUiChatConfirmChannelDelete',
  chat1ChatUiChatGiphySearchResults: 'engine-gen:chat1ChatUiChatGiphySearchResults',
  chat1ChatUiChatGiphyToggleResultWindow: 'engine-gen:chat1ChatUiChatGiphyToggleResultWindow',
  chat1ChatUiChatInboxConversation: 'engine-gen:chat1ChatUiChatInboxConversation',
  chat1ChatUiChatInboxFailed: 'engine-gen:chat1ChatUiChatInboxFailed',
  chat1ChatUiChatInboxLayout: 'engine-gen:chat1ChatUiChatInboxLayout',
  chat1ChatUiChatInboxUnverified: 'engine-gen:chat1ChatUiChatInboxUnverified',
  chat1ChatUiChatLoadGalleryHit: 'engine-gen:chat1ChatUiChatLoadGalleryHit',
  chat1ChatUiChatMaybeMentionUpdate: 'engine-gen:chat1ChatUiChatMaybeMentionUpdate',
  chat1ChatUiChatSearchBotHits: 'engine-gen:chat1ChatUiChatSearchBotHits',
  chat1ChatUiChatSearchConvHits: 'engine-gen:chat1ChatUiChatSearchConvHits',
  chat1ChatUiChatSearchDone: 'engine-gen:chat1ChatUiChatSearchDone',
  chat1ChatUiChatSearchHit: 'engine-gen:chat1ChatUiChatSearchHit',
  chat1ChatUiChatSearchInboxDone: 'engine-gen:chat1ChatUiChatSearchInboxDone',
  chat1ChatUiChatSearchInboxHit: 'engine-gen:chat1ChatUiChatSearchInboxHit',
  chat1ChatUiChatSearchInboxStart: 'engine-gen:chat1ChatUiChatSearchInboxStart',
  chat1ChatUiChatSearchIndexStatus: 'engine-gen:chat1ChatUiChatSearchIndexStatus',
  chat1ChatUiChatSearchTeamHits: 'engine-gen:chat1ChatUiChatSearchTeamHits',
  chat1ChatUiChatShowManageChannels: 'engine-gen:chat1ChatUiChatShowManageChannels',
  chat1ChatUiChatStellarDataConfirm: 'engine-gen:chat1ChatUiChatStellarDataConfirm',
  chat1ChatUiChatStellarDataError: 'engine-gen:chat1ChatUiChatStellarDataError',
  chat1ChatUiChatStellarDone: 'engine-gen:chat1ChatUiChatStellarDone',
  chat1ChatUiChatStellarShowConfirm: 'engine-gen:chat1ChatUiChatStellarShowConfirm',
  chat1ChatUiChatThreadCached: 'engine-gen:chat1ChatUiChatThreadCached',
  chat1ChatUiChatThreadFull: 'engine-gen:chat1ChatUiChatThreadFull',
  chat1ChatUiChatThreadStatus: 'engine-gen:chat1ChatUiChatThreadStatus',
  chat1ChatUiChatWatchPosition: 'engine-gen:chat1ChatUiChatWatchPosition',
  chat1ChatUiTriggerContactSync: 'engine-gen:chat1ChatUiTriggerContactSync',
  chat1NotifyChatChatArchiveComplete: 'engine-gen:chat1NotifyChatChatArchiveComplete',
  chat1NotifyChatChatArchiveProgress: 'engine-gen:chat1NotifyChatChatArchiveProgress',
  chat1NotifyChatChatAttachmentDownloadComplete: 'engine-gen:chat1NotifyChatChatAttachmentDownloadComplete',
  chat1NotifyChatChatAttachmentDownloadProgress: 'engine-gen:chat1NotifyChatChatAttachmentDownloadProgress',
  chat1NotifyChatChatAttachmentUploadProgress: 'engine-gen:chat1NotifyChatChatAttachmentUploadProgress',
  chat1NotifyChatChatAttachmentUploadStart: 'engine-gen:chat1NotifyChatChatAttachmentUploadStart',
  chat1NotifyChatChatConvUpdate: 'engine-gen:chat1NotifyChatChatConvUpdate',
  chat1NotifyChatChatIdentifyUpdate: 'engine-gen:chat1NotifyChatChatIdentifyUpdate',
  chat1NotifyChatChatInboxStale: 'engine-gen:chat1NotifyChatChatInboxStale',
  chat1NotifyChatChatInboxSyncStarted: 'engine-gen:chat1NotifyChatChatInboxSyncStarted',
  chat1NotifyChatChatInboxSynced: 'engine-gen:chat1NotifyChatChatInboxSynced',
  chat1NotifyChatChatJoinedConversation: 'engine-gen:chat1NotifyChatChatJoinedConversation',
  chat1NotifyChatChatKBFSToImpteamUpgrade: 'engine-gen:chat1NotifyChatChatKBFSToImpteamUpgrade',
  chat1NotifyChatChatLeftConversation: 'engine-gen:chat1NotifyChatChatLeftConversation',
  chat1NotifyChatChatParticipantsInfo: 'engine-gen:chat1NotifyChatChatParticipantsInfo',
  chat1NotifyChatChatPaymentInfo: 'engine-gen:chat1NotifyChatChatPaymentInfo',
  chat1NotifyChatChatPromptUnfurl: 'engine-gen:chat1NotifyChatChatPromptUnfurl',
  chat1NotifyChatChatRequestInfo: 'engine-gen:chat1NotifyChatChatRequestInfo',
  chat1NotifyChatChatResetConversation: 'engine-gen:chat1NotifyChatChatResetConversation',
  chat1NotifyChatChatSetConvRetention: 'engine-gen:chat1NotifyChatChatSetConvRetention',
  chat1NotifyChatChatSetConvSettings: 'engine-gen:chat1NotifyChatChatSetConvSettings',
  chat1NotifyChatChatSetTeamRetention: 'engine-gen:chat1NotifyChatChatSetTeamRetention',
  chat1NotifyChatChatSubteamRename: 'engine-gen:chat1NotifyChatChatSubteamRename',
  chat1NotifyChatChatTLFFinalize: 'engine-gen:chat1NotifyChatChatTLFFinalize',
  chat1NotifyChatChatTLFResolve: 'engine-gen:chat1NotifyChatChatTLFResolve',
  chat1NotifyChatChatThreadsStale: 'engine-gen:chat1NotifyChatChatThreadsStale',
  chat1NotifyChatChatTypingUpdate: 'engine-gen:chat1NotifyChatChatTypingUpdate',
  chat1NotifyChatChatWelcomeMessageLoaded: 'engine-gen:chat1NotifyChatChatWelcomeMessageLoaded',
  chat1NotifyChatNewChatActivity: 'engine-gen:chat1NotifyChatNewChatActivity',
  keybase1GpgUiConfirmDuplicateKeyChosen: 'engine-gen:keybase1GpgUiConfirmDuplicateKeyChosen',
  keybase1GpgUiConfirmImportSecretToExistingKey: 'engine-gen:keybase1GpgUiConfirmImportSecretToExistingKey',
  keybase1GpgUiGetTTY: 'engine-gen:keybase1GpgUiGetTTY',
  keybase1GpgUiSelectKey: 'engine-gen:keybase1GpgUiSelectKey',
  keybase1GpgUiSelectKeyAndPushOption: 'engine-gen:keybase1GpgUiSelectKeyAndPushOption',
  keybase1GpgUiSign: 'engine-gen:keybase1GpgUiSign',
  keybase1GpgUiWantToAddGPGKey: 'engine-gen:keybase1GpgUiWantToAddGPGKey',
  keybase1GregorUIPushOutOfBandMessages: 'engine-gen:keybase1GregorUIPushOutOfBandMessages',
  keybase1GregorUIPushState: 'engine-gen:keybase1GregorUIPushState',
  keybase1HomeUIHomeUIRefresh: 'engine-gen:keybase1HomeUIHomeUIRefresh',
  keybase1Identify3UiIdentify3Result: 'engine-gen:keybase1Identify3UiIdentify3Result',
  keybase1Identify3UiIdentify3ShowTracker: 'engine-gen:keybase1Identify3UiIdentify3ShowTracker',
  keybase1Identify3UiIdentify3Summary: 'engine-gen:keybase1Identify3UiIdentify3Summary',
  keybase1Identify3UiIdentify3TrackerTimedOut: 'engine-gen:keybase1Identify3UiIdentify3TrackerTimedOut',
  keybase1Identify3UiIdentify3UpdateRow: 'engine-gen:keybase1Identify3UiIdentify3UpdateRow',
  keybase1Identify3UiIdentify3UpdateUserCard: 'engine-gen:keybase1Identify3UiIdentify3UpdateUserCard',
  keybase1Identify3UiIdentify3UserReset: 'engine-gen:keybase1Identify3UiIdentify3UserReset',
  keybase1IdentifyUiCancel: 'engine-gen:keybase1IdentifyUiCancel',
  keybase1IdentifyUiConfirm: 'engine-gen:keybase1IdentifyUiConfirm',
  keybase1IdentifyUiDelegateIdentifyUI: 'engine-gen:keybase1IdentifyUiDelegateIdentifyUI',
  keybase1IdentifyUiDismiss: 'engine-gen:keybase1IdentifyUiDismiss',
  keybase1IdentifyUiDisplayCryptocurrency: 'engine-gen:keybase1IdentifyUiDisplayCryptocurrency',
  keybase1IdentifyUiDisplayKey: 'engine-gen:keybase1IdentifyUiDisplayKey',
  keybase1IdentifyUiDisplayStellarAccount: 'engine-gen:keybase1IdentifyUiDisplayStellarAccount',
  keybase1IdentifyUiDisplayTLFCreateWithInvite: 'engine-gen:keybase1IdentifyUiDisplayTLFCreateWithInvite',
  keybase1IdentifyUiDisplayTrackStatement: 'engine-gen:keybase1IdentifyUiDisplayTrackStatement',
  keybase1IdentifyUiDisplayUserCard: 'engine-gen:keybase1IdentifyUiDisplayUserCard',
  keybase1IdentifyUiFinish: 'engine-gen:keybase1IdentifyUiFinish',
  keybase1IdentifyUiFinishSocialProofCheck: 'engine-gen:keybase1IdentifyUiFinishSocialProofCheck',
  keybase1IdentifyUiFinishWebProofCheck: 'engine-gen:keybase1IdentifyUiFinishWebProofCheck',
  keybase1IdentifyUiLaunchNetworkChecks: 'engine-gen:keybase1IdentifyUiLaunchNetworkChecks',
  keybase1IdentifyUiReportLastTrack: 'engine-gen:keybase1IdentifyUiReportLastTrack',
  keybase1IdentifyUiReportTrackToken: 'engine-gen:keybase1IdentifyUiReportTrackToken',
  keybase1IdentifyUiStart: 'engine-gen:keybase1IdentifyUiStart',
  keybase1LogUiLog: 'engine-gen:keybase1LogUiLog',
  keybase1LoginUiChooseDeviceToRecoverWith: 'engine-gen:keybase1LoginUiChooseDeviceToRecoverWith',
  keybase1LoginUiDisplayPaperKeyPhrase: 'engine-gen:keybase1LoginUiDisplayPaperKeyPhrase',
  keybase1LoginUiDisplayPrimaryPaperKey: 'engine-gen:keybase1LoginUiDisplayPrimaryPaperKey',
  keybase1LoginUiDisplayResetMessage: 'engine-gen:keybase1LoginUiDisplayResetMessage',
  keybase1LoginUiDisplayResetProgress: 'engine-gen:keybase1LoginUiDisplayResetProgress',
  keybase1LoginUiExplainDeviceRecovery: 'engine-gen:keybase1LoginUiExplainDeviceRecovery',
  keybase1LoginUiGetEmailOrUsername: 'engine-gen:keybase1LoginUiGetEmailOrUsername',
  keybase1LoginUiPromptPassphraseRecovery: 'engine-gen:keybase1LoginUiPromptPassphraseRecovery',
  keybase1LoginUiPromptResetAccount: 'engine-gen:keybase1LoginUiPromptResetAccount',
  keybase1LoginUiPromptRevokePaperKeys: 'engine-gen:keybase1LoginUiPromptRevokePaperKeys',
  keybase1LogsendPrepareLogsend: 'engine-gen:keybase1LogsendPrepareLogsend',
  keybase1NotifyAppExit: 'engine-gen:keybase1NotifyAppExit',
  keybase1NotifyAuditBoxAuditError: 'engine-gen:keybase1NotifyAuditBoxAuditError',
  keybase1NotifyAuditRootAuditError: 'engine-gen:keybase1NotifyAuditRootAuditError',
  keybase1NotifyBadgesBadgeState: 'engine-gen:keybase1NotifyBadgesBadgeState',
  keybase1NotifyCanUserPerformCanUserPerformChanged: 'engine-gen:keybase1NotifyCanUserPerformCanUserPerformChanged',
  keybase1NotifyDeviceCloneDeviceCloneCountChanged: 'engine-gen:keybase1NotifyDeviceCloneDeviceCloneCountChanged',
  keybase1NotifyEmailAddressEmailAddressVerified: 'engine-gen:keybase1NotifyEmailAddressEmailAddressVerified',
  keybase1NotifyEmailAddressEmailsChanged: 'engine-gen:keybase1NotifyEmailAddressEmailsChanged',
  keybase1NotifyEphemeralNewTeamEk: 'engine-gen:keybase1NotifyEphemeralNewTeamEk',
  keybase1NotifyEphemeralNewTeambotEk: 'engine-gen:keybase1NotifyEphemeralNewTeambotEk',
  keybase1NotifyEphemeralTeambotEkNeeded: 'engine-gen:keybase1NotifyEphemeralTeambotEkNeeded',
  keybase1NotifyFSFSActivity: 'engine-gen:keybase1NotifyFSFSActivity',
  keybase1NotifyFSFSEditListResponse: 'engine-gen:keybase1NotifyFSFSEditListResponse',
  keybase1NotifyFSFSFavoritesChanged: 'engine-gen:keybase1NotifyFSFSFavoritesChanged',
  keybase1NotifyFSFSOnlineStatusChanged: 'engine-gen:keybase1NotifyFSFSOnlineStatusChanged',
  keybase1NotifyFSFSOverallSyncStatusChanged: 'engine-gen:keybase1NotifyFSFSOverallSyncStatusChanged',
  keybase1NotifyFSFSPathUpdated: 'engine-gen:keybase1NotifyFSFSPathUpdated',
  keybase1NotifyFSFSSubscriptionNotify: 'engine-gen:keybase1NotifyFSFSSubscriptionNotify',
  keybase1NotifyFSFSSubscriptionNotifyPath: 'engine-gen:keybase1NotifyFSFSSubscriptionNotifyPath',
  keybase1NotifyFSFSSyncActivity: 'engine-gen:keybase1NotifyFSFSSyncActivity',
  keybase1NotifyFSFSSyncStatusResponse: 'engine-gen:keybase1NotifyFSFSSyncStatusResponse',
  keybase1NotifyFavoritesFavoritesChanged: 'engine-gen:keybase1NotifyFavoritesFavoritesChanged',
  keybase1NotifyFeaturedBotsFeaturedBotsUpdate: 'engine-gen:keybase1NotifyFeaturedBotsFeaturedBotsUpdate',
  keybase1NotifyInviteFriendsUpdateInviteCounts: 'engine-gen:keybase1NotifyInviteFriendsUpdateInviteCounts',
  keybase1NotifyKeyfamilyKeyfamilyChanged: 'engine-gen:keybase1NotifyKeyfamilyKeyfamilyChanged',
  keybase1NotifyPGPPgpKeyInSecretStoreFile: 'engine-gen:keybase1NotifyPGPPgpKeyInSecretStoreFile',
  keybase1NotifyPaperKeyPaperKeyCached: 'engine-gen:keybase1NotifyPaperKeyPaperKeyCached',
  keybase1NotifyPhoneNumberPhoneNumbersChanged: 'engine-gen:keybase1NotifyPhoneNumberPhoneNumbersChanged',
  keybase1NotifyRuntimeStatsRuntimeStatsUpdate: 'engine-gen:keybase1NotifyRuntimeStatsRuntimeStatsUpdate',
  keybase1NotifySaltpackSaltpackOperationDone: 'engine-gen:keybase1NotifySaltpackSaltpackOperationDone',
  keybase1NotifySaltpackSaltpackOperationProgress: 'engine-gen:keybase1NotifySaltpackSaltpackOperationProgress',
  keybase1NotifySaltpackSaltpackOperationStart: 'engine-gen:keybase1NotifySaltpackSaltpackOperationStart',
  keybase1NotifyServiceHTTPSrvInfoUpdate: 'engine-gen:keybase1NotifyServiceHTTPSrvInfoUpdate',
  keybase1NotifyServiceHandleKeybaseLink: 'engine-gen:keybase1NotifyServiceHandleKeybaseLink',
  keybase1NotifyServiceShutdown: 'engine-gen:keybase1NotifyServiceShutdown',
  keybase1NotifySessionClientOutOfDate: 'engine-gen:keybase1NotifySessionClientOutOfDate',
  keybase1NotifySessionLoggedIn: 'engine-gen:keybase1NotifySessionLoggedIn',
  keybase1NotifySessionLoggedOut: 'engine-gen:keybase1NotifySessionLoggedOut',
  keybase1NotifySimpleFSSimpleFSArchiveStatusChanged: 'engine-gen:keybase1NotifySimpleFSSimpleFSArchiveStatusChanged',
  keybase1NotifyTeamAvatarUpdated: 'engine-gen:keybase1NotifyTeamAvatarUpdated',
  keybase1NotifyTeamNewlyAddedToTeam: 'engine-gen:keybase1NotifyTeamNewlyAddedToTeam',
  keybase1NotifyTeamTeamAbandoned: 'engine-gen:keybase1NotifyTeamTeamAbandoned',
  keybase1NotifyTeamTeamChangedByID: 'engine-gen:keybase1NotifyTeamTeamChangedByID',
  keybase1NotifyTeamTeamChangedByName: 'engine-gen:keybase1NotifyTeamTeamChangedByName',
  keybase1NotifyTeamTeamDeleted: 'engine-gen:keybase1NotifyTeamTeamDeleted',
  keybase1NotifyTeamTeamExit: 'engine-gen:keybase1NotifyTeamTeamExit',
  keybase1NotifyTeamTeamMetadataUpdate: 'engine-gen:keybase1NotifyTeamTeamMetadataUpdate',
  keybase1NotifyTeamTeamRoleMapChanged: 'engine-gen:keybase1NotifyTeamTeamRoleMapChanged',
  keybase1NotifyTeamTeamTreeMembershipsDone: 'engine-gen:keybase1NotifyTeamTeamTreeMembershipsDone',
  keybase1NotifyTeamTeamTreeMembershipsPartial: 'engine-gen:keybase1NotifyTeamTeamTreeMembershipsPartial',
  keybase1NotifyTeambotNewTeambotKey: 'engine-gen:keybase1NotifyTeambotNewTeambotKey',
  keybase1NotifyTeambotTeambotKeyNeeded: 'engine-gen:keybase1NotifyTeambotTeambotKeyNeeded',
  keybase1NotifyTrackingNotifyUserBlocked: 'engine-gen:keybase1NotifyTrackingNotifyUserBlocked',
  keybase1NotifyTrackingTrackingChanged: 'engine-gen:keybase1NotifyTrackingTrackingChanged',
  keybase1NotifyTrackingTrackingInfo: 'engine-gen:keybase1NotifyTrackingTrackingInfo',
  keybase1NotifyUsersIdentifyUpdate: 'engine-gen:keybase1NotifyUsersIdentifyUpdate',
  keybase1NotifyUsersPasswordChanged: 'engine-gen:keybase1NotifyUsersPasswordChanged',
  keybase1NotifyUsersUserChanged: 'engine-gen:keybase1NotifyUsersUserChanged',
  keybase1NotifyUsersWebOfTrustChanged: 'engine-gen:keybase1NotifyUsersWebOfTrustChanged',
  keybase1PgpUiFinished: 'engine-gen:keybase1PgpUiFinished',
  keybase1PgpUiKeyGenerated: 'engine-gen:keybase1PgpUiKeyGenerated',
  keybase1PgpUiOutputPGPWarning: 'engine-gen:keybase1PgpUiOutputPGPWarning',
  keybase1PgpUiOutputSignatureNonKeybase: 'engine-gen:keybase1PgpUiOutputSignatureNonKeybase',
  keybase1PgpUiOutputSignatureSuccess: 'engine-gen:keybase1PgpUiOutputSignatureSuccess',
  keybase1PgpUiShouldPushPrivate: 'engine-gen:keybase1PgpUiShouldPushPrivate',
  keybase1ProveUiChecking: 'engine-gen:keybase1ProveUiChecking',
  keybase1ProveUiContinueChecking: 'engine-gen:keybase1ProveUiContinueChecking',
  keybase1ProveUiDisplayRecheckWarning: 'engine-gen:keybase1ProveUiDisplayRecheckWarning',
  keybase1ProveUiOkToCheck: 'engine-gen:keybase1ProveUiOkToCheck',
  keybase1ProveUiOutputInstructions: 'engine-gen:keybase1ProveUiOutputInstructions',
  keybase1ProveUiOutputPrechecks: 'engine-gen:keybase1ProveUiOutputPrechecks',
  keybase1ProveUiPreProofWarning: 'engine-gen:keybase1ProveUiPreProofWarning',
  keybase1ProveUiPromptOverwrite: 'engine-gen:keybase1ProveUiPromptOverwrite',
  keybase1ProveUiPromptUsername: 'engine-gen:keybase1ProveUiPromptUsername',
  keybase1ProvisionUiChooseDevice: 'engine-gen:keybase1ProvisionUiChooseDevice',
  keybase1ProvisionUiChooseDeviceType: 'engine-gen:keybase1ProvisionUiChooseDeviceType',
  keybase1ProvisionUiChooseGPGMethod: 'engine-gen:keybase1ProvisionUiChooseGPGMethod',
  keybase1ProvisionUiChooseProvisioningMethod: 'engine-gen:keybase1ProvisionUiChooseProvisioningMethod',
  keybase1ProvisionUiDisplayAndPromptSecret: 'engine-gen:keybase1ProvisionUiDisplayAndPromptSecret',
  keybase1ProvisionUiDisplaySecretExchanged: 'engine-gen:keybase1ProvisionUiDisplaySecretExchanged',
  keybase1ProvisionUiPromptNewDeviceName: 'engine-gen:keybase1ProvisionUiPromptNewDeviceName',
  keybase1ProvisionUiProvisioneeSuccess: 'engine-gen:keybase1ProvisionUiProvisioneeSuccess',
  keybase1ProvisionUiProvisionerSuccess: 'engine-gen:keybase1ProvisionUiProvisionerSuccess',
  keybase1ProvisionUiSwitchToGPGSignOK: 'engine-gen:keybase1ProvisionUiSwitchToGPGSignOK',
  keybase1ReachabilityReachabilityChanged: 'engine-gen:keybase1ReachabilityReachabilityChanged',
  keybase1RekeyUIDelegateRekeyUI: 'engine-gen:keybase1RekeyUIDelegateRekeyUI',
  keybase1RekeyUIRefresh: 'engine-gen:keybase1RekeyUIRefresh',
  keybase1RekeyUIRekeySendEvent: 'engine-gen:keybase1RekeyUIRekeySendEvent',
  keybase1SaltpackUiSaltpackPromptForDecrypt: 'engine-gen:keybase1SaltpackUiSaltpackPromptForDecrypt',
  keybase1SaltpackUiSaltpackVerifyBadSender: 'engine-gen:keybase1SaltpackUiSaltpackVerifyBadSender',
  keybase1SaltpackUiSaltpackVerifySuccess: 'engine-gen:keybase1SaltpackUiSaltpackVerifySuccess',
  keybase1SecretUiGetPassphrase: 'engine-gen:keybase1SecretUiGetPassphrase',
  keybase1StreamUiClose: 'engine-gen:keybase1StreamUiClose',
  keybase1StreamUiRead: 'engine-gen:keybase1StreamUiRead',
  keybase1StreamUiReset: 'engine-gen:keybase1StreamUiReset',
  keybase1StreamUiWrite: 'engine-gen:keybase1StreamUiWrite',
  keybase1TeamsUiConfirmInviteLinkAccept: 'engine-gen:keybase1TeamsUiConfirmInviteLinkAccept',
  keybase1TeamsUiConfirmRootTeamDelete: 'engine-gen:keybase1TeamsUiConfirmRootTeamDelete',
  keybase1TeamsUiConfirmSubteamDelete: 'engine-gen:keybase1TeamsUiConfirmSubteamDelete',
  keybase1UiPromptYesNo: 'engine-gen:keybase1UiPromptYesNo',
  stellar1NotifyAccountDetailsUpdate: 'engine-gen:stellar1NotifyAccountDetailsUpdate',
  stellar1NotifyAccountsUpdate: 'engine-gen:stellar1NotifyAccountsUpdate',
  stellar1NotifyPaymentNotification: 'engine-gen:stellar1NotifyPaymentNotification',
  stellar1NotifyPaymentStatusNotification: 'engine-gen:stellar1NotifyPaymentStatusNotification',
  stellar1NotifyPendingPaymentsUpdate: 'engine-gen:stellar1NotifyPendingPaymentsUpdate',
  stellar1NotifyRecentPaymentsUpdate: 'engine-gen:stellar1NotifyRecentPaymentsUpdate',
  stellar1NotifyRequestStatusNotification: 'engine-gen:stellar1NotifyRequestStatusNotification',
  stellar1UiPaymentReviewed: 'engine-gen:stellar1UiPaymentReviewed',
} as const

export type ActionKey = keyof ActionSpec
type EngineActionMap = {
  [K in ActionKey]: {readonly payload: ActionSpec[K]; readonly type: (typeof actionTypes)[K]}
}

export type ActionPayload<K extends ActionKey = ActionKey> = ActionSpec[K]
export type EngineAction<K extends ActionKey = ActionKey> = EngineActionMap[K]
export type EngineActions = EngineAction
export type ResetStoreAction = {readonly type: typeof resetStore; readonly payload: undefined}
export type Actions = EngineActions | ResetStoreAction
export type ActionType = Actions['type']
export type ActionOf<T extends ActionType> = Extract<Actions, {readonly type: T}>
export type PayloadOf<T extends ActionType> = ActionOf<T> extends {readonly payload: infer P} ? P : never
export type ParamsOf<T extends ActionType> = PayloadOf<T> extends {readonly params: infer P} ? P : never
export type ResponseOf<T extends ActionType> = PayloadOf<T> extends {readonly response: infer R} ? R : never
