// Copyright 2017 Keybase, Inc. All rights reserved. Use of
// this source code is governed by the included BSD license.

package client

import (
	"github.com/keybase/client/go/libkb"
)

const (
	PromptDescriptorGeneric libkb.PromptDescriptor = iota
	PromptDescriptorRevokePaperKeys
	PromptDescriptorReregister
	PromptDescriptorInviteOK
	PromptDescriptorPGPGenPushSecret
	PromptDescriptorDoctorWhichAccount
	PromptDescriptorDoctorSignOK
	PromptDescriptorGPGOKToAdd
	PromptDescriptorGPGConfirmDuplicateKey
	PromptDescriptorTrackAction
	PromptDescriptorTrackPublic
	PromptDescriptorProvePreWarning
	PromptDescriptorProveOKToCheck
	PromptDescriptorProveOverwriteOK
	PromptDescriptorLocksmithDeviceName
	PromptDescriptorLocksmithSigningOption
	PromptDescriptorGPGSelectKey
	PromptDescriptorLoginUsername
	PromptDescriptorLoginWritePaper
	PromptDescriptorLoginWallet
	PromptDescriptorSignupFullName
	PromptDescriptorSignupNotes
	PromptDescriptorSignupUsername
	PromptDescriptorSignupEmail
	PromptDescriptorSignupReenterPassphrase
	PromptDescriptorSignupDevice
	PromptDescriptorSignupCode
	PromptDescriptorChooseProvisioningMethod
	PromptDescriptorChooseGPGMethod
	PromptDescriptorChooseDevice
	PromptDescriptorChooseDeviceType
	PromptDescriptorProvisionPhrase
	PromptDescriptorProvisionDeviceName
	PromptDescriptorProvisionSwitchToGPGSign
	PromptDescriptorExportSecretKeyFromGPG
	PromptDescriptorDeprovisionWhichUser
	PromptDescriptorUpdateDo
	PromptDescriptorUpdateAuto
	PromptDescriptorUpdateSnooze
	PromptDescriptorDecryptInteractive
	PromptDescriptorPGPGenEnterID
	PromptDescriptorTrackExpireLocal
	PromptDescriptorChooseConversation
	PromptDescriptorEnterChatTLFName
	PromptDescriptorEnterChatMessage
	PromptDescriptorDeviceRevoke
	PromptDescriptorFSOverwrite
	PromptDescriptorRemoveMember
)

const (
	OutputDescriptorGeneric libkb.OutputDescriptor = iota
	OutputDescriptorPrimaryPaperKey
	OutputDescriptorEndageredTLFs
)
