// flow-typed signature: 6438495bbe3d914660d8993a3e46e06d
// flow-typed version: <<STUB>>/@storybook/addon-storyshots_v3.2.13/flow_v0.58.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@storybook/addon-storyshots'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@storybook/addon-storyshots' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@storybook/addon-storyshots/dist/index' {
  declare module.exports: any;
}

declare module '@storybook/addon-storyshots/dist/require_context' {
  declare module.exports: any;
}

declare module '@storybook/addon-storyshots/dist/storybook-channel-mock' {
  declare module.exports: any;
}

declare module '@storybook/addon-storyshots/dist/test-bodies' {
  declare module.exports: any;
}

declare module '@storybook/addon-storyshots/stories/directly_required/index' {
  declare module.exports: any;
}

declare module '@storybook/addon-storyshots/stories/required_with_context/Button.stories' {
  declare module.exports: any;
}

declare module '@storybook/addon-storyshots/stories/required_with_context/Welcome.stories' {
  declare module.exports: any;
}

// Filename aliases
declare module '@storybook/addon-storyshots/dist/index.js' {
  declare module.exports: $Exports<'@storybook/addon-storyshots/dist/index'>;
}
declare module '@storybook/addon-storyshots/dist/require_context.js' {
  declare module.exports: $Exports<'@storybook/addon-storyshots/dist/require_context'>;
}
declare module '@storybook/addon-storyshots/dist/storybook-channel-mock.js' {
  declare module.exports: $Exports<'@storybook/addon-storyshots/dist/storybook-channel-mock'>;
}
declare module '@storybook/addon-storyshots/dist/test-bodies.js' {
  declare module.exports: $Exports<'@storybook/addon-storyshots/dist/test-bodies'>;
}
declare module '@storybook/addon-storyshots/stories/directly_required/index.js' {
  declare module.exports: $Exports<'@storybook/addon-storyshots/stories/directly_required/index'>;
}
declare module '@storybook/addon-storyshots/stories/required_with_context/Button.stories.js' {
  declare module.exports: $Exports<'@storybook/addon-storyshots/stories/required_with_context/Button.stories'>;
}
declare module '@storybook/addon-storyshots/stories/required_with_context/Welcome.stories.js' {
  declare module.exports: $Exports<'@storybook/addon-storyshots/stories/required_with_context/Welcome.stories'>;
}
