// flow-typed signature: c583357c5d5c097a74c6d41bd2c79a60
// flow-typed version: <<STUB>>/@storybook/channels_v3.2.13/flow_v0.58.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@storybook/channels'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@storybook/channels' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@storybook/channels/dist/index' {
  declare module.exports: any;
}

declare module '@storybook/channels/src/index' {
  declare module.exports: any;
}

declare module '@storybook/channels/src/index.test' {
  declare module.exports: any;
}

// Filename aliases
declare module '@storybook/channels/dist/index.js' {
  declare module.exports: $Exports<'@storybook/channels/dist/index'>;
}
declare module '@storybook/channels/src/index.js' {
  declare module.exports: $Exports<'@storybook/channels/src/index'>;
}
declare module '@storybook/channels/src/index.test.js' {
  declare module.exports: $Exports<'@storybook/channels/src/index.test'>;
}
