// flow-typed signature: 7c14dbdc2b565c9f59e4b9c14b67e27d
// flow-typed version: <<STUB>>/getenv_v0.7.0/flow_v0.60.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'getenv'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'getenv' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'getenv/lib/getenv' {
  declare module.exports: any;
}

declare module 'getenv/test/disableErrors' {
  declare module.exports: any;
}

declare module 'getenv/test/fallbacks' {
  declare module.exports: any;
}

declare module 'getenv/test/getenv' {
  declare module.exports: any;
}

// Filename aliases
declare module 'getenv/index' {
  declare module.exports: $Exports<'getenv'>;
}
declare module 'getenv/index.js' {
  declare module.exports: $Exports<'getenv'>;
}
declare module 'getenv/lib/getenv.js' {
  declare module.exports: $Exports<'getenv/lib/getenv'>;
}
declare module 'getenv/test/disableErrors.js' {
  declare module.exports: $Exports<'getenv/test/disableErrors'>;
}
declare module 'getenv/test/fallbacks.js' {
  declare module.exports: $Exports<'getenv/test/fallbacks'>;
}
declare module 'getenv/test/getenv.js' {
  declare module.exports: $Exports<'getenv/test/getenv'>;
}
