// flow-typed signature: f79193a3e70315c75f548461d76faed0
// flow-typed version: <<STUB>>/react-gateway_v3.0.0/flow_v0.72.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-gateway'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-gateway' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-gateway/lib/Gateway' {
  declare module.exports: any;
}

declare module 'react-gateway/lib/GatewayDest' {
  declare module.exports: any;
}

declare module 'react-gateway/lib/GatewayProvider' {
  declare module.exports: any;
}

declare module 'react-gateway/lib/GatewayRegistry' {
  declare module.exports: any;
}

declare module 'react-gateway/lib/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-gateway/lib/Gateway.js' {
  declare module.exports: $Exports<'react-gateway/lib/Gateway'>;
}
declare module 'react-gateway/lib/GatewayDest.js' {
  declare module.exports: $Exports<'react-gateway/lib/GatewayDest'>;
}
declare module 'react-gateway/lib/GatewayProvider.js' {
  declare module.exports: $Exports<'react-gateway/lib/GatewayProvider'>;
}
declare module 'react-gateway/lib/GatewayRegistry.js' {
  declare module.exports: $Exports<'react-gateway/lib/GatewayRegistry'>;
}
declare module 'react-gateway/lib/index.js' {
  declare module.exports: $Exports<'react-gateway/lib/index'>;
}
