// flow-typed signature: e9185e8c53b02bab83acf9e5411aef49
// flow-typed version: <<STUB>>/react-native-camera_v0.10.0/flow_v0.56.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-native-camera'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-native-camera' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'react-native-camera/index' {
  declare module.exports: $Exports<'react-native-camera'>;
}
declare module 'react-native-camera/index.js' {
  declare module.exports: $Exports<'react-native-camera'>;
}
