// flow-typed signature: 4aa4ce99044116f7165a7f9d11242324
// flow-typed version: <<STUB>>/shallowequal_v1.0.2/flow_v0.69.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'shallowequal'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'shallowequal' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'shallowequal/index' {
  declare module.exports: $Exports<'shallowequal'>;
}
declare module 'shallowequal/index.js' {
  declare module.exports: $Exports<'shallowequal'>;
}
