// Auto-generated by avdl-compiler v1.3.29 (https://github.com/keybase/node-avdl-compiler)
//   Input file: avdl/chat1/decorate.avdl

package chat1

import (
	stellar1 "github.com/keybase/client/go/protocol/stellar1"
	"github.com/keybase/go-framed-msgpack-rpc/rpc"
)

type DecorationPayment struct {
	PaymentID stellar1.PaymentID `codec:"paymentID" json:"paymentID"`
}

func (o DecorationPayment) DeepCopy() DecorationPayment {
	return DecorationPayment{
		PaymentID: o.PaymentID.DeepCopy(),
	}
}

type DecorateInterface interface {
}

func DecorateProtocol(i DecorateInterface) rpc.Protocol {
	return rpc.Protocol{
		Name:    "chat.1.decorate",
		Methods: map[string]rpc.ServeHandlerDescription{},
	}
}

type DecorateClient struct {
	Cli rpc.GenericClient
}
