platform :ios, '10.0'

require_relative '../../node_modules/react-native-unimodules/cocoapods.rb'

target 'Keybase' do
  pod 'React', :path => '../../node_modules/react-native', :subspecs => [
    'Core',
    'CxxBridge',
    'DevSupport',
    'RCTText',
    'RCTNetwork',
    'RCTWebSocket',
    'RCTAnimation',
    'RCTImage',
    'RCTActionSheet',
    'RCTLinkingIOS',
    'RCTPushNotification',
    'RCTSettings',
    'RCTCameraRoll'
  ]

  # Do not leave dependencies commented out here - it messes with `react-native link/unlink` behavior
  pod 'yoga', :path => '../../node_modules/react-native/ReactCommon/yoga'
  pod 'DoubleConversion', :podspec => '../../node_modules/react-native/third-party-podspecs/DoubleConversion.podspec'
  pod 'glog', :podspec => '../../node_modules/react-native/third-party-podspecs/glog.podspec'
  pod 'Folly', :podspec => '../../node_modules/react-native/third-party-podspecs/Folly.podspec'

  # Pods for Keybase

  use_unimodules!(modules_paths: ['../../node_modules'])
end

target 'Keybase For Tests' do
  inherit! :search_paths
end

target 'KeybaseShare' do
  inherit! :search_paths
end
