# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'Keybase' do
  # Comment this line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  pod 'React', :path => '../../node_modules/react-native', :subspecs => [
    'Core',
    'RCTActionSheet',
    'RCTCameraRoll',
    'RCTImage',
    'RCTLinkingIOS',
    'RCTNetwork',
    'RCTPushNotification',
    'RCTText',
    'RCTVibration',
    'RCTWebSocket'
  ] # Pods for Keybase

end

target 'Keybase For Tests' do
  # Comment this line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Keybase For Tests

end
