export type RefreshReason =
  | 'bootstrap'
  | 'componentNeverLoaded'
  | 'inboxSyncedCurrentButEmpty'
  | 'inboxStale'
  | 'inboxSyncedClear'
  | 'inboxSyncedUnknown'
  | 'joinedAConversation'
  | 'leftAConversation'
  | 'teamTypeChanged'
  | 'maybeKickedFromTeam'
  | 'widgetRefresh'
  | 'shareConfigSearch'
