#! /bin/bash

###
### This script is largely copied from the post-install script used by Google
### Chrome. It adds the Keybase package repo to your package manager sources,
### so that system updates pull in Keybase updates.
###

# sources.list setting for keybase updates.
REPOCONFIG="http://dist.keybase.io/linux/rpm/repo"

YUM_REPO_FILE="/etc/yum.repos.d/keybase.repo"

install_yum() {
  # We can't add the signing key during an RPM install, because that uses the
  # same global lock that the install does. It'll get fetched when it's used
  # though, and the user will have to approve it.

  if [ -d "/etc/yum.repos.d" ]; then
cat > "$YUM_REPO_FILE" << REPOCONTENT
[keybase]
name=keybase
baseurl=$REPOCONFIG
enabled=1
gpgcheck=1
gpgkey=https://keybase.io/docs/server_security/code_signing_key.asc
REPOCONTENT
  fi
}

install_yum
