run:
  skip-files:
    prot.go

linters-settings:
  gocritic:
    disabled-checks:
      - ifElseChain
      - elseif
      - singleCaseSwitch

linters:
  enable:
    - gofmt
    - gocritic
    - unconvert
