version: '2'

run:
  timeout: 10m
  tests: true

formatters:
  exclusions:
    generated: lax
    paths:
      - prot.go
      - cmd_wallet.*.go
      - protocol
      - third_party$
      - kbfs
      - builtin$
  enable:
    - gofmt
    - gofumpt

linters:
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    paths:
      - prot.go
      - cmd_wallet.*.go
      - protocol
      - third_party$
      - builtin$
      - examples$
      - kbfs
  enable:
    # Currently enabled linters (migrated from v1 config)
    - gocritic
    - unconvert
    - revive
    - govet

  disable:
    # Disabled by default in v1, keeping disabled for incremental migration
    - errcheck # Error checking - enabled by default in v2, many unchecked errors
    - staticcheck # Static analysis - enabled by default in v2, style issues
    - ineffassign # Will enable in Phase 1
    - unused # Will enable in Phase 1

    # Additional linters from kbfs-server/keybase examples (disabled for now)
    # These can be enabled incrementally in future work
    # - bodyclose     # HTTP response body checks
    # - misspell      # Spelling checks
    # - gosec         # Security checks
    # - unparam       # Unused parameters

  settings:
    gocritic:
      disabled-checks:
        - ifElseChain
        - elseif

    govet:
      enable-all: true
      disable:
        - shadow # Too noisy, legitimate patterns
        - fieldalignment # Memory optimization, not worth churn

    revive:
      enable-all-rules: false
      rules:
        # Disabled rules (from v1 config + package-comments for noisy format checks)
        - name: unused-parameter
          disabled: true
        - name: error-strings
          disabled: true
        - name: exported
          disabled: true
        - name: package-comments # Disabled - too noisy about comment format
          disabled: true
        - name: var-naming # Disabled - allow utils/types package names
          disabled: true

        # Enabled rules (from v1 config)
        - name: blank-imports
        - name: context-as-argument
        - name: context-keys-type
        - name: dot-imports
        - name: empty-block
        - name: error-naming
        - name: error-return
        - name: errorf
        - name: increment-decrement
        - name: indent-error-flow
        - name: range
        - name: receiver-naming
        - name: redefines-builtin-id
        - name: superfluous-else
        - name: time-naming
        - name: unexported-return
        - name: unreachable-code
        - name: var-declaration
# ==============================================================================
# NOTE: Version 2 config doesn't support issues.exclude-files for path-based exclusions.
# Files like prot.go, cmd_wallet*.go, and protocol/ that were previously excluded
# will need to be handled via linter-specific settings or disabled rules (like
# var-naming, exported, package-comments which are already disabled in revive).
# ==============================================================================
# MIGRATION PLAN FOR ADDITIONAL LINTERS
# ==============================================================================
# This config maintains backward compatibility with the v1 config while
# preparing for incremental improvements.
#
# Currently Enabled (4 linters):
#   1. gofmt       - Formatting
#   2. gocritic    - Code quality checks
#   3. unconvert   - Type conversion checks
#   4. govet       - Official Go vet tool
#   5. revive      - Style checks
#
# Recommended to enable next (from kbfs-server/keybase examples):
#   Phase 1 - Low effort, high value:
#     - staticcheck    # Static analysis - comprehensive bug detection
#     - ineffassign    # Ineffectual assignments - easy wins
#     - unused         # Unused code - easy cleanup
#
#   Phase 2 - Medium effort:
#     - bodyclose      # HTTP response body checks - prevents leaks
#     - misspell       # Spelling checks - documentation quality
#
#   Phase 3 - Higher effort:
#     - gosec          # Security checks - may need exclusions (G115, G404, G104)
#     - unparam        # Unused parameters - refactoring needed
#     - errcheck       # Error checking - significant fixes needed
#     - noctx          # Context propagation - architectural changes
#
# Configuration notes from examples:
# - gocritic: ifElseChain and elseif checks commonly disabled
# - govet: shadow and fieldalignment commonly disabled
# - revive: documentation rules (exported, package-comments) often disabled
# - staticcheck: ST1000-ST1021 style checks often disabled for protocol code
# - gosec: G115 (int overflow), G404 (weak rand), G104 (unhandled errors) often excluded
# ==============================================================================
