// NOTE: This file is GENERATED from json files in actions/json. Run 'yarn build-actions' to regenerate
/* eslint-disable no-unused-vars,no-use-before-define */
import * as autoreset from './autoreset-gen'
import * as bots from './bots-gen'
import * as chat2 from './chat2-gen'
import * as config from './config-gen'
import * as crypto from './crypto-gen'
import * as deeplinks from './deeplinks-gen'
import * as dev from './dev-gen'
import * as devices from './devices-gen'
import * as enginegen from './engine-gen-gen'
import * as fs from './fs-gen'
import * as git from './git-gen'
import * as gregor from './gregor-gen'
import * as login from './login-gen'
import * as notifications from './notifications-gen'
import * as people from './people-gen'
import * as pinentry from './pinentry-gen'
import * as profile from './profile-gen'
import * as provision from './provision-gen'
import * as push from './push-gen'
import * as recoverpassword from './recover-password-gen'
import * as routetree from './route-tree-gen'
import * as settings from './settings-gen'
import * as signup from './signup-gen'
import * as teambuilding from './team-building-gen'
import * as teams from './teams-gen'
import * as tracker2 from './tracker2-gen'
import * as unlockfolders from './unlock-folders-gen'
import * as users from './users-gen'
import * as waiting from './waiting-gen'
import * as wallets from './wallets-gen'

export type TypedActions =
  | autoreset.Actions
  | bots.Actions
  | chat2.Actions
  | config.Actions
  | crypto.Actions
  | deeplinks.Actions
  | dev.Actions
  | devices.Actions
  | enginegen.Actions
  | fs.Actions
  | git.Actions
  | gregor.Actions
  | login.Actions
  | notifications.Actions
  | people.Actions
  | pinentry.Actions
  | profile.Actions
  | provision.Actions
  | push.Actions
  | recoverpassword.Actions
  | routetree.Actions
  | settings.Actions
  | signup.Actions
  | teambuilding.Actions
  | teams.Actions
  | tracker2.Actions
  | unlockfolders.Actions
  | users.Actions
  | waiting.Actions
  | wallets.Actions

export type TypedActionsMap = {
  'autoreset:cancelReset': autoreset.CancelResetPayload
  'autoreset:displayProgress': autoreset.DisplayProgressPayload
  'autoreset:finishedReset': autoreset.FinishedResetPayload
  'autoreset:resetAccount': autoreset.ResetAccountPayload
  'autoreset:resetCancelled': autoreset.ResetCancelledPayload
  'autoreset:resetError': autoreset.ResetErrorPayload
  'autoreset:setUsername': autoreset.SetUsernamePayload
  'autoreset:showFinalResetScreen': autoreset.ShowFinalResetScreenPayload
  'autoreset:startAccountReset': autoreset.StartAccountResetPayload
  'autoreset:submittedReset': autoreset.SubmittedResetPayload
  'autoreset:updateAutoresetState': autoreset.UpdateAutoresetStatePayload
  'bots:getFeaturedBots': bots.GetFeaturedBotsPayload
  'bots:searchFeaturedBots': bots.SearchFeaturedBotsPayload
  'bots:updateFeaturedBots': bots.UpdateFeaturedBotsPayload
  'bots:setLoadedAllBots': bots.SetLoadedAllBotsPayload
  'bots:searchFeaturedAndUsers': bots.SearchFeaturedAndUsersPayload
  'bots:setSearchFeaturedAndUsersResults': bots.SetSearchFeaturedAndUsersResultsPayload
  'chat2:toggleSmallTeamsExpanded': chat2.ToggleSmallTeamsExpandedPayload
  'chat2:selectedConversation': chat2.SelectedConversationPayload
  'chat2:deselectedConversation': chat2.DeselectedConversationPayload
  'chat2:channelSuggestionsTriggered': chat2.ChannelSuggestionsTriggeredPayload
  'chat2:conversationErrored': chat2.ConversationErroredPayload
  'chat2:previewConversation': chat2.PreviewConversationPayload
  'chat2:createConversation': chat2.CreateConversationPayload
  'chat2:changeFocus': chat2.ChangeFocusPayload
  'chat2:badgesUpdated': chat2.BadgesUpdatedPayload
  'chat2:inboxRefresh': chat2.InboxRefreshPayload
  'chat2:metaNeedsUpdating': chat2.MetaNeedsUpdatingPayload
  'chat2:metaHandleQueue': chat2.MetaHandleQueuePayload
  'chat2:metaRequestingTrusted': chat2.MetaRequestingTrustedPayload
  'chat2:metaRequestTrusted': chat2.MetaRequestTrustedPayload
  'chat2:metasReceived': chat2.MetasReceivedPayload
  'chat2:clearMetas': chat2.ClearMetasPayload
  'chat2:clearMessages': chat2.ClearMessagesPayload
  'chat2:metaReceivedError': chat2.MetaReceivedErrorPayload
  'chat2:metaDelete': chat2.MetaDeletePayload
  'chat2:updateMoreToLoad': chat2.UpdateMoreToLoadPayload
  'chat2:messagesAdd': chat2.MessagesAddPayload
  'chat2:messageErrored': chat2.MessageErroredPayload
  'chat2:messageSetEditing': chat2.MessageSetEditingPayload
  'chat2:messageSetQuoting': chat2.MessageSetQuotingPayload
  'chat2:messageReplyPrivately': chat2.MessageReplyPrivatelyPayload
  'chat2:messageEdit': chat2.MessageEditPayload
  'chat2:messageWasEdited': chat2.MessageWasEditedPayload
  'chat2:pendingMessageWasEdited': chat2.PendingMessageWasEditedPayload
  'chat2:messagesWereDeleted': chat2.MessagesWereDeletedPayload
  'chat2:messagesExploded': chat2.MessagesExplodedPayload
  'chat2:messageDelete': chat2.MessageDeletePayload
  'chat2:messageDeleteHistory': chat2.MessageDeleteHistoryPayload
  'chat2:loadOlderMessagesDueToScroll': chat2.LoadOlderMessagesDueToScrollPayload
  'chat2:loadNewerMessagesDueToScroll': chat2.LoadNewerMessagesDueToScrollPayload
  'chat2:loadMessagesCentered': chat2.LoadMessagesCenteredPayload
  'chat2:desktopNotification': chat2.DesktopNotificationPayload
  'chat2:messageSend': chat2.MessageSendPayload
  'chat2:messageSendByUsernames': chat2.MessageSendByUsernamesPayload
  'chat2:toggleLocalReaction': chat2.ToggleLocalReactionPayload
  'chat2:toggleMessageReaction': chat2.ToggleMessageReactionPayload
  'chat2:updateReactions': chat2.UpdateReactionsPayload
  'chat2:messageRetry': chat2.MessageRetryPayload
  'chat2:joinConversation': chat2.JoinConversationPayload
  'chat2:leaveConversation': chat2.LeaveConversationPayload
  'chat2:muteConversation': chat2.MuteConversationPayload
  'chat2:openFolder': chat2.OpenFolderPayload
  'chat2:resetChatWithoutThem': chat2.ResetChatWithoutThemPayload
  'chat2:resetLetThemIn': chat2.ResetLetThemInPayload
  'chat2:attachmentPreviewSelect': chat2.AttachmentPreviewSelectPayload
  'chat2:attachmentDownload': chat2.AttachmentDownloadPayload
  'chat2:attachmentMobileSave': chat2.AttachmentMobileSavePayload
  'chat2:attachmentMobileSaved': chat2.AttachmentMobileSavedPayload
  'chat2:attachmentLoading': chat2.AttachmentLoadingPayload
  'chat2:attachmentDownloaded': chat2.AttachmentDownloadedPayload
  'chat2:attachmentsUpload': chat2.AttachmentsUploadPayload
  'chat2:attachFromDragAndDrop': chat2.AttachFromDragAndDropPayload
  'chat2:attachmentUploading': chat2.AttachmentUploadingPayload
  'chat2:attachmentUploaded': chat2.AttachmentUploadedPayload
  'chat2:attachmentPasted': chat2.AttachmentPastedPayload
  'chat2:messageAttachmentUploaded': chat2.MessageAttachmentUploadedPayload
  'chat2:sendTyping': chat2.SendTypingPayload
  'chat2:markInitiallyLoadedThreadAsRead': chat2.MarkInitiallyLoadedThreadAsReadPayload
  'chat2:markConversationsStale': chat2.MarkConversationsStalePayload
  'chat2:navigateToInbox': chat2.NavigateToInboxPayload
  'chat2:navigateToThread': chat2.NavigateToThreadPayload
  'chat2:messageAttachmentNativeShare': chat2.MessageAttachmentNativeSharePayload
  'chat2:messageAttachmentNativeSave': chat2.MessageAttachmentNativeSavePayload
  'chat2:updateNotificationSettings': chat2.UpdateNotificationSettingsPayload
  'chat2:notificationSettingsUpdated': chat2.NotificationSettingsUpdatedPayload
  'chat2:blockConversation': chat2.BlockConversationPayload
  'chat2:hideConversation': chat2.HideConversationPayload
  'chat2:unhideConversation': chat2.UnhideConversationPayload
  'chat2:setConversationOffline': chat2.SetConversationOfflinePayload
  'chat2:setConvRetentionPolicy': chat2.SetConvRetentionPolicyPayload
  'chat2:updateConvRetentionPolicy': chat2.UpdateConvRetentionPolicyPayload
  'chat2:updateTeamRetentionPolicy': chat2.UpdateTeamRetentionPolicyPayload
  'chat2:setConvExplodingMode': chat2.SetConvExplodingModePayload
  'chat2:setExplodingModeLock': chat2.SetExplodingModeLockPayload
  'chat2:updateConvExplodingModes': chat2.UpdateConvExplodingModesPayload
  'chat2:staticConfigLoaded': chat2.StaticConfigLoadedPayload
  'chat2:setMinWriterRole': chat2.SetMinWriterRolePayload
  'chat2:saveMinWriterRole': chat2.SaveMinWriterRolePayload
  'chat2:openChatFromWidget': chat2.OpenChatFromWidgetPayload
  'chat2:paymentInfoReceived': chat2.PaymentInfoReceivedPayload
  'chat2:requestInfoReceived': chat2.RequestInfoReceivedPayload
  'chat2:prepareFulfillRequestForm': chat2.PrepareFulfillRequestFormPayload
  'chat2:unfurlResolvePrompt': chat2.UnfurlResolvePromptPayload
  'chat2:unfurlTogglePrompt': chat2.UnfurlTogglePromptPayload
  'chat2:unfurlRemove': chat2.UnfurlRemovePayload
  'chat2:unsentTextChanged': chat2.UnsentTextChangedPayload
  'chat2:updateMessages': chat2.UpdateMessagesPayload
  'chat2:giphySend': chat2.GiphySendPayload
  'chat2:giphyGotSearchResult': chat2.GiphyGotSearchResultPayload
  'chat2:giphyToggleWindow': chat2.GiphyToggleWindowPayload
  'chat2:clearPaymentConfirmInfo': chat2.ClearPaymentConfirmInfoPayload
  'chat2:setPaymentConfirmInfo': chat2.SetPaymentConfirmInfoPayload
  'chat2:confirmScreenResponse': chat2.ConfirmScreenResponsePayload
  'chat2:setUnsentText': chat2.SetUnsentTextPayload
  'chat2:setPrependText': chat2.SetPrependTextPayload
  'chat2:updateUnreadline': chat2.UpdateUnreadlinePayload
  'chat2:toggleMessageCollapse': chat2.ToggleMessageCollapsePayload
  'chat2:updateCoinFlipStatus': chat2.UpdateCoinFlipStatusPayload
  'chat2:setCommandMarkdown': chat2.SetCommandMarkdownPayload
  'chat2:addUsersToChannel': chat2.AddUsersToChannelPayload
  'chat2:addUserToChannel': chat2.AddUserToChannelPayload
  'chat2:jumpToRecent': chat2.JumpToRecentPayload
  'chat2:setContainsLastMessage': chat2.SetContainsLastMessagePayload
  'chat2:threadSearch': chat2.ThreadSearchPayload
  'chat2:threadSearchResults': chat2.ThreadSearchResultsPayload
  'chat2:setThreadSearchStatus': chat2.SetThreadSearchStatusPayload
  'chat2:toggleThreadSearch': chat2.ToggleThreadSearchPayload
  'chat2:toggleReplyToMessage': chat2.ToggleReplyToMessagePayload
  'chat2:replyJump': chat2.ReplyJumpPayload
  'chat2:setThreadSearchQuery': chat2.SetThreadSearchQueryPayload
  'chat2:inboxSearch': chat2.InboxSearchPayload
  'chat2:inboxSearchStarted': chat2.InboxSearchStartedPayload
  'chat2:toggleInboxSearch': chat2.ToggleInboxSearchPayload
  'chat2:inboxSearchOpenTeamsResults': chat2.InboxSearchOpenTeamsResultsPayload
  'chat2:inboxSearchBotsResults': chat2.InboxSearchBotsResultsPayload
  'chat2:inboxSearchNameResults': chat2.InboxSearchNameResultsPayload
  'chat2:inboxSearchTextResult': chat2.InboxSearchTextResultPayload
  'chat2:inboxSearchMoveSelectedIndex': chat2.InboxSearchMoveSelectedIndexPayload
  'chat2:inboxSearchSelect': chat2.InboxSearchSelectPayload
  'chat2:inboxSearchSetTextStatus': chat2.InboxSearchSetTextStatusPayload
  'chat2:inboxSearchSetIndexPercent': chat2.InboxSearchSetIndexPercentPayload
  'chat2:setMaybeMentionInfo': chat2.SetMaybeMentionInfoPayload
  'chat2:tabSelected': chat2.TabSelectedPayload
  'chat2:resolveMaybeMention': chat2.ResolveMaybeMentionPayload
  'chat2:loadAttachmentView': chat2.LoadAttachmentViewPayload
  'chat2:addAttachmentViewMessage': chat2.AddAttachmentViewMessagePayload
  'chat2:setAttachmentViewStatus': chat2.SetAttachmentViewStatusPayload
  'chat2:clearAttachmentView': chat2.ClearAttachmentViewPayload
  'chat2:updateUserReacjis': chat2.UpdateUserReacjisPayload
  'chat2:setCommandStatusInfo': chat2.SetCommandStatusInfoPayload
  'chat2:clearCommandStatusInfo': chat2.ClearCommandStatusInfoPayload
  'chat2:setThreadLoadStatus': chat2.SetThreadLoadStatusPayload
  'chat2:pinMessage': chat2.PinMessagePayload
  'chat2:unpinMessage': chat2.UnpinMessagePayload
  'chat2:ignorePinnedMessage': chat2.IgnorePinnedMessagePayload
  'chat2:dismissBottomBanner': chat2.DismissBottomBannerPayload
  'chat2:updateLastCoord': chat2.UpdateLastCoordPayload
  'chat2:toggleGiphyPrefill': chat2.ToggleGiphyPrefillPayload
  'chat2:updateBlockButtons': chat2.UpdateBlockButtonsPayload
  'chat2:dismissBlockButtons': chat2.DismissBlockButtonsPayload
  'chat2:setInboxNumSmallRows': chat2.SetInboxNumSmallRowsPayload
  'chat2:enableAudioRecording': chat2.EnableAudioRecordingPayload
  'chat2:attemptAudioRecording': chat2.AttemptAudioRecordingPayload
  'chat2:stopAudioRecording': chat2.StopAudioRecordingPayload
  'chat2:lockAudioRecording': chat2.LockAudioRecordingPayload
  'chat2:sendAudioRecording': chat2.SendAudioRecordingPayload
  'chat2:setAudioRecordingPostInfo': chat2.SetAudioRecordingPostInfoPayload
  'chat2:loadNextBotPage': chat2.LoadNextBotPagePayload
  'chat2:setLoadedBotPage': chat2.SetLoadedBotPagePayload
  'chat2:refreshBotPublicCommands': chat2.RefreshBotPublicCommandsPayload
  'chat2:setBotPublicCommands': chat2.SetBotPublicCommandsPayload
  'chat2:addBotMember': chat2.AddBotMemberPayload
  'chat2:refreshBotSettings': chat2.RefreshBotSettingsPayload
  'chat2:setBotSettings': chat2.SetBotSettingsPayload
  'chat2:removeBotMember': chat2.RemoveBotMemberPayload
  'chat2:editBotSettings': chat2.EditBotSettingsPayload
  'chat2:setParticipants': chat2.SetParticipantsPayload
  'chat2:findGeneralConvIDFromTeamID': chat2.FindGeneralConvIDFromTeamIDPayload
  'chat2:setGeneralConvFromTeamID': chat2.SetGeneralConvFromTeamIDPayload
  'chat2:refreshBotRoleInConv': chat2.RefreshBotRoleInConvPayload
  'chat2:setBotRoleInConv': chat2.SetBotRoleInConvPayload
  'chat2:showInfoPanel': chat2.ShowInfoPanelPayload
  'chat2:dismissJourneycard': chat2.DismissJourneycardPayload
  'chat2:addToMessageMap': chat2.AddToMessageMapPayload
  'chat2:refreshMutualTeamsInConv': chat2.RefreshMutualTeamsInConvPayload
  'chat2:loadedMutualTeams': chat2.LoadedMutualTeamsPayload
  'chat2:fetchUserEmoji': chat2.FetchUserEmojiPayload
  'chat2:loadedUserEmoji': chat2.LoadedUserEmojiPayload
  'config:startHandshake': config.StartHandshakePayload
  'config:restartHandshake': config.RestartHandshakePayload
  'config:daemonHandshake': config.DaemonHandshakePayload
  'config:daemonHandshakeWait': config.DaemonHandshakeWaitPayload
  'config:daemonHandshakeDone': config.DaemonHandshakeDonePayload
  'config:filePickerError': config.FilePickerErrorPayload
  'config:logout': config.LogoutPayload
  'config:logoutAndTryToLogInAs': config.LogoutAndTryToLogInAsPayload
  'config:logoutHandshake': config.LogoutHandshakePayload
  'config:logoutHandshakeWait': config.LogoutHandshakeWaitPayload
  'config:installerRan': config.InstallerRanPayload
  'config:dumpLogs': config.DumpLogsPayload
  'config:openAppSettings': config.OpenAppSettingsPayload
  'config:changedFocus': config.ChangedFocusPayload
  'config:changedActive': config.ChangedActivePayload
  'config:mobileAppState': config.MobileAppStatePayload
  'config:showMain': config.ShowMainPayload
  'config:bootstrapStatusLoaded': config.BootstrapStatusLoadedPayload
  'config:followerInfoUpdated': config.FollowerInfoUpdatedPayload
  'config:daemonError': config.DaemonErrorPayload
  'config:setAccounts': config.SetAccountsPayload
  'config:setDefaultUsername': config.SetDefaultUsernamePayload
  'config:globalError': config.GlobalErrorPayload
  'config:pushLoaded': config.PushLoadedPayload
  'config:setStartupDetails': config.SetStartupDetailsPayload
  'config:setStartupFile': config.SetStartupFilePayload
  'config:setOpenAtLogin': config.SetOpenAtLoginPayload
  'config:setNotifySound': config.SetNotifySoundPayload
  'config:setDeletedSelf': config.SetDeletedSelfPayload
  'config:persistRoute': config.PersistRoutePayload
  'config:setNavigator': config.SetNavigatorPayload
  'config:loggedOut': config.LoggedOutPayload
  'config:loggedIn': config.LoggedInPayload
  'config:setUserSwitching': config.SetUserSwitchingPayload
  'config:updateMenubarWindowID': config.UpdateMenubarWindowIDPayload
  'config:copyToClipboard': config.CopyToClipboardPayload
  'config:checkForUpdate': config.CheckForUpdatePayload
  'config:updateInfo': config.UpdateInfoPayload
  'config:updateNow': config.UpdateNowPayload
  'config:openAppStore': config.OpenAppStorePayload
  'config:updateCriticalCheckStatus': config.UpdateCriticalCheckStatusPayload
  'config:osNetworkStatusChanged': config.OsNetworkStatusChangedPayload
  'config:setDarkModePreference': config.SetDarkModePreferencePayload
  'config:setSystemDarkMode': config.SetSystemDarkModePayload
  'config:updateHTTPSrvInfo': config.UpdateHTTPSrvInfoPayload
  'config:remoteWindowWantsProps': config.RemoteWindowWantsPropsPayload
  'config:updateWindowState': config.UpdateWindowStatePayload
  'config:setUseNativeFrame': config.SetUseNativeFramePayload
  'config:setWhatsNewLastSeenVersion': config.SetWhatsNewLastSeenVersionPayload
  'config:toggleRuntimeStats': config.ToggleRuntimeStatsPayload
  'config:loadOnLoginStartup': config.LoadOnLoginStartupPayload
  'config:loadedOnLoginStartup': config.LoadedOnLoginStartupPayload
  'config:loadOnStart': config.LoadOnStartPayload
  'config:showShareActionSheet': config.ShowShareActionSheetPayload
  'config:androidShare': config.AndroidSharePayload
  'config:setIncomingShareUseOriginal': config.SetIncomingShareUseOriginalPayload
  'crypto:clearRecipients': crypto.ClearRecipientsPayload
  'crypto:clearInput': crypto.ClearInputPayload
  'crypto:downloadEncryptedText': crypto.DownloadEncryptedTextPayload
  'crypto:downloadSignedText': crypto.DownloadSignedTextPayload
  'crypto:setRecipients': crypto.SetRecipientsPayload
  'crypto:setInput': crypto.SetInputPayload
  'crypto:setInputThrottled': crypto.SetInputThrottledPayload
  'crypto:setEncryptOptions': crypto.SetEncryptOptionsPayload
  'crypto:onSaltpackOpenFile': crypto.OnSaltpackOpenFilePayload
  'crypto:onOperationSuccess': crypto.OnOperationSuccessPayload
  'crypto:onOperationError': crypto.OnOperationErrorPayload
  'crypto:resetOperation': crypto.ResetOperationPayload
  'crypto:runTextOperation': crypto.RunTextOperationPayload
  'crypto:runFileOperation': crypto.RunFileOperationPayload
  'crypto:saltpackDone': crypto.SaltpackDonePayload
  'crypto:saltpackEncrypt': crypto.SaltpackEncryptPayload
  'crypto:saltpackDecrypt': crypto.SaltpackDecryptPayload
  'crypto:saltpackProgress': crypto.SaltpackProgressPayload
  'crypto:saltpackSign': crypto.SaltpackSignPayload
  'crypto:saltpackStart': crypto.SaltpackStartPayload
  'crypto:saltpackVerify': crypto.SaltpackVerifyPayload
  'deeplinks:handleKeybaseLink': deeplinks.HandleKeybaseLinkPayload
  'deeplinks:link': deeplinks.LinkPayload
  'deeplinks:saltpackFileOpen': deeplinks.SaltpackFileOpenPayload
  'deeplinks:setKeybaseLinkError': deeplinks.SetKeybaseLinkErrorPayload
  'dev:updateDebugConfig': dev.UpdateDebugConfigPayload
  'dev:debugCount': dev.DebugCountPayload
  'devices:load': devices.LoadPayload
  'devices:clearBadges': devices.ClearBadgesPayload
  'devices:loaded': devices.LoadedPayload
  'devices:endangeredTLFsLoaded': devices.EndangeredTLFsLoadedPayload
  'devices:paperKeyCreated': devices.PaperKeyCreatedPayload
  'devices:revoke': devices.RevokePayload
  'devices:revoked': devices.RevokedPayload
  'devices:badgeAppForDevices': devices.BadgeAppForDevicesPayload
  'devices:showRevokePage': devices.ShowRevokePagePayload
  'devices:showDevicePage': devices.ShowDevicePagePayload
  'devices:showPaperKeyPage': devices.ShowPaperKeyPagePayload
  'engine-gen:disconnected': enginegen.DisconnectedPayload
  'engine-gen:connected': enginegen.ConnectedPayload
  'engine-gen:chat1ChatUiChatAttachmentDownloadStart': enginegen.Chat1ChatUiChatAttachmentDownloadStartPayload
  'engine-gen:chat1ChatUiChatAttachmentDownloadProgress': enginegen.Chat1ChatUiChatAttachmentDownloadProgressPayload
  'engine-gen:chat1ChatUiChatAttachmentDownloadDone': enginegen.Chat1ChatUiChatAttachmentDownloadDonePayload
  'engine-gen:chat1ChatUiChatInboxLayout': enginegen.Chat1ChatUiChatInboxLayoutPayload
  'engine-gen:chat1ChatUiChatInboxUnverified': enginegen.Chat1ChatUiChatInboxUnverifiedPayload
  'engine-gen:chat1ChatUiChatInboxConversation': enginegen.Chat1ChatUiChatInboxConversationPayload
  'engine-gen:chat1ChatUiChatInboxFailed': enginegen.Chat1ChatUiChatInboxFailedPayload
  'engine-gen:chat1ChatUiChatThreadCached': enginegen.Chat1ChatUiChatThreadCachedPayload
  'engine-gen:chat1ChatUiChatThreadFull': enginegen.Chat1ChatUiChatThreadFullPayload
  'engine-gen:chat1ChatUiChatThreadStatus': enginegen.Chat1ChatUiChatThreadStatusPayload
  'engine-gen:chat1ChatUiChatSearchHit': enginegen.Chat1ChatUiChatSearchHitPayload
  'engine-gen:chat1ChatUiChatSearchDone': enginegen.Chat1ChatUiChatSearchDonePayload
  'engine-gen:chat1ChatUiChatSearchInboxStart': enginegen.Chat1ChatUiChatSearchInboxStartPayload
  'engine-gen:chat1ChatUiChatSearchInboxHit': enginegen.Chat1ChatUiChatSearchInboxHitPayload
  'engine-gen:chat1ChatUiChatSearchInboxDone': enginegen.Chat1ChatUiChatSearchInboxDonePayload
  'engine-gen:chat1ChatUiChatSearchIndexStatus': enginegen.Chat1ChatUiChatSearchIndexStatusPayload
  'engine-gen:chat1ChatUiChatSearchConvHits': enginegen.Chat1ChatUiChatSearchConvHitsPayload
  'engine-gen:chat1ChatUiChatSearchTeamHits': enginegen.Chat1ChatUiChatSearchTeamHitsPayload
  'engine-gen:chat1ChatUiChatSearchBotHits': enginegen.Chat1ChatUiChatSearchBotHitsPayload
  'engine-gen:chat1ChatUiChatConfirmChannelDelete': enginegen.Chat1ChatUiChatConfirmChannelDeletePayload
  'engine-gen:chat1ChatUiChatStellarShowConfirm': enginegen.Chat1ChatUiChatStellarShowConfirmPayload
  'engine-gen:chat1ChatUiChatStellarDataConfirm': enginegen.Chat1ChatUiChatStellarDataConfirmPayload
  'engine-gen:chat1ChatUiChatStellarDataError': enginegen.Chat1ChatUiChatStellarDataErrorPayload
  'engine-gen:chat1ChatUiChatStellarDone': enginegen.Chat1ChatUiChatStellarDonePayload
  'engine-gen:chat1ChatUiChatGiphySearchResults': enginegen.Chat1ChatUiChatGiphySearchResultsPayload
  'engine-gen:chat1ChatUiChatGiphyToggleResultWindow': enginegen.Chat1ChatUiChatGiphyToggleResultWindowPayload
  'engine-gen:chat1ChatUiChatShowManageChannels': enginegen.Chat1ChatUiChatShowManageChannelsPayload
  'engine-gen:chat1ChatUiChatCoinFlipStatus': enginegen.Chat1ChatUiChatCoinFlipStatusPayload
  'engine-gen:chat1ChatUiChatCommandMarkdown': enginegen.Chat1ChatUiChatCommandMarkdownPayload
  'engine-gen:chat1ChatUiChatMaybeMentionUpdate': enginegen.Chat1ChatUiChatMaybeMentionUpdatePayload
  'engine-gen:chat1ChatUiChatLoadGalleryHit': enginegen.Chat1ChatUiChatLoadGalleryHitPayload
  'engine-gen:chat1ChatUiChatWatchPosition': enginegen.Chat1ChatUiChatWatchPositionPayload
  'engine-gen:chat1ChatUiChatClearWatch': enginegen.Chat1ChatUiChatClearWatchPayload
  'engine-gen:chat1ChatUiChatCommandStatus': enginegen.Chat1ChatUiChatCommandStatusPayload
  'engine-gen:chat1ChatUiChatBotCommandsUpdateStatus': enginegen.Chat1ChatUiChatBotCommandsUpdateStatusPayload
  'engine-gen:chat1ChatUiTriggerContactSync': enginegen.Chat1ChatUiTriggerContactSyncPayload
  'engine-gen:chat1NotifyChatNewChatActivity': enginegen.Chat1NotifyChatNewChatActivityPayload
  'engine-gen:chat1NotifyChatChatIdentifyUpdate': enginegen.Chat1NotifyChatChatIdentifyUpdatePayload
  'engine-gen:chat1NotifyChatChatTLFFinalize': enginegen.Chat1NotifyChatChatTLFFinalizePayload
  'engine-gen:chat1NotifyChatChatTLFResolve': enginegen.Chat1NotifyChatChatTLFResolvePayload
  'engine-gen:chat1NotifyChatChatInboxStale': enginegen.Chat1NotifyChatChatInboxStalePayload
  'engine-gen:chat1NotifyChatChatThreadsStale': enginegen.Chat1NotifyChatChatThreadsStalePayload
  'engine-gen:chat1NotifyChatChatTypingUpdate': enginegen.Chat1NotifyChatChatTypingUpdatePayload
  'engine-gen:chat1NotifyChatChatJoinedConversation': enginegen.Chat1NotifyChatChatJoinedConversationPayload
  'engine-gen:chat1NotifyChatChatLeftConversation': enginegen.Chat1NotifyChatChatLeftConversationPayload
  'engine-gen:chat1NotifyChatChatResetConversation': enginegen.Chat1NotifyChatChatResetConversationPayload
  'engine-gen:chat1NotifyChatChatInboxSyncStarted': enginegen.Chat1NotifyChatChatInboxSyncStartedPayload
  'engine-gen:chat1NotifyChatChatInboxSynced': enginegen.Chat1NotifyChatChatInboxSyncedPayload
  'engine-gen:chat1NotifyChatChatSetConvRetention': enginegen.Chat1NotifyChatChatSetConvRetentionPayload
  'engine-gen:chat1NotifyChatChatSetTeamRetention': enginegen.Chat1NotifyChatChatSetTeamRetentionPayload
  'engine-gen:chat1NotifyChatChatSetConvSettings': enginegen.Chat1NotifyChatChatSetConvSettingsPayload
  'engine-gen:chat1NotifyChatChatSubteamRename': enginegen.Chat1NotifyChatChatSubteamRenamePayload
  'engine-gen:chat1NotifyChatChatKBFSToImpteamUpgrade': enginegen.Chat1NotifyChatChatKBFSToImpteamUpgradePayload
  'engine-gen:chat1NotifyChatChatAttachmentUploadStart': enginegen.Chat1NotifyChatChatAttachmentUploadStartPayload
  'engine-gen:chat1NotifyChatChatAttachmentUploadProgress': enginegen.Chat1NotifyChatChatAttachmentUploadProgressPayload
  'engine-gen:chat1NotifyChatChatPaymentInfo': enginegen.Chat1NotifyChatChatPaymentInfoPayload
  'engine-gen:chat1NotifyChatChatRequestInfo': enginegen.Chat1NotifyChatChatRequestInfoPayload
  'engine-gen:chat1NotifyChatChatPromptUnfurl': enginegen.Chat1NotifyChatChatPromptUnfurlPayload
  'engine-gen:chat1NotifyChatChatConvUpdate': enginegen.Chat1NotifyChatChatConvUpdatePayload
  'engine-gen:chat1NotifyChatChatWelcomeMessageLoaded': enginegen.Chat1NotifyChatChatWelcomeMessageLoadedPayload
  'engine-gen:chat1NotifyChatChatParticipantsInfo': enginegen.Chat1NotifyChatChatParticipantsInfoPayload
  'engine-gen:keybase1GpgUiWantToAddGPGKey': enginegen.Keybase1GpgUiWantToAddGPGKeyPayload
  'engine-gen:keybase1GpgUiConfirmDuplicateKeyChosen': enginegen.Keybase1GpgUiConfirmDuplicateKeyChosenPayload
  'engine-gen:keybase1GpgUiConfirmImportSecretToExistingKey': enginegen.Keybase1GpgUiConfirmImportSecretToExistingKeyPayload
  'engine-gen:keybase1GpgUiSelectKeyAndPushOption': enginegen.Keybase1GpgUiSelectKeyAndPushOptionPayload
  'engine-gen:keybase1GpgUiSelectKey': enginegen.Keybase1GpgUiSelectKeyPayload
  'engine-gen:keybase1GpgUiSign': enginegen.Keybase1GpgUiSignPayload
  'engine-gen:keybase1GpgUiGetTTY': enginegen.Keybase1GpgUiGetTTYPayload
  'engine-gen:keybase1GregorUIPushState': enginegen.Keybase1GregorUIPushStatePayload
  'engine-gen:keybase1GregorUIPushOutOfBandMessages': enginegen.Keybase1GregorUIPushOutOfBandMessagesPayload
  'engine-gen:keybase1HomeUIHomeUIRefresh': enginegen.Keybase1HomeUIHomeUIRefreshPayload
  'engine-gen:keybase1Identify3UiIdentify3ShowTracker': enginegen.Keybase1Identify3UiIdentify3ShowTrackerPayload
  'engine-gen:keybase1Identify3UiIdentify3Summary': enginegen.Keybase1Identify3UiIdentify3SummaryPayload
  'engine-gen:keybase1Identify3UiIdentify3UpdateRow': enginegen.Keybase1Identify3UiIdentify3UpdateRowPayload
  'engine-gen:keybase1Identify3UiIdentify3UserReset': enginegen.Keybase1Identify3UiIdentify3UserResetPayload
  'engine-gen:keybase1Identify3UiIdentify3UpdateUserCard': enginegen.Keybase1Identify3UiIdentify3UpdateUserCardPayload
  'engine-gen:keybase1Identify3UiIdentify3TrackerTimedOut': enginegen.Keybase1Identify3UiIdentify3TrackerTimedOutPayload
  'engine-gen:keybase1Identify3UiIdentify3Result': enginegen.Keybase1Identify3UiIdentify3ResultPayload
  'engine-gen:keybase1IdentifyUiDisplayTLFCreateWithInvite': enginegen.Keybase1IdentifyUiDisplayTLFCreateWithInvitePayload
  'engine-gen:keybase1IdentifyUiDelegateIdentifyUI': enginegen.Keybase1IdentifyUiDelegateIdentifyUIPayload
  'engine-gen:keybase1IdentifyUiStart': enginegen.Keybase1IdentifyUiStartPayload
  'engine-gen:keybase1IdentifyUiDisplayKey': enginegen.Keybase1IdentifyUiDisplayKeyPayload
  'engine-gen:keybase1IdentifyUiReportLastTrack': enginegen.Keybase1IdentifyUiReportLastTrackPayload
  'engine-gen:keybase1IdentifyUiLaunchNetworkChecks': enginegen.Keybase1IdentifyUiLaunchNetworkChecksPayload
  'engine-gen:keybase1IdentifyUiDisplayTrackStatement': enginegen.Keybase1IdentifyUiDisplayTrackStatementPayload
  'engine-gen:keybase1IdentifyUiFinishWebProofCheck': enginegen.Keybase1IdentifyUiFinishWebProofCheckPayload
  'engine-gen:keybase1IdentifyUiFinishSocialProofCheck': enginegen.Keybase1IdentifyUiFinishSocialProofCheckPayload
  'engine-gen:keybase1IdentifyUiDisplayCryptocurrency': enginegen.Keybase1IdentifyUiDisplayCryptocurrencyPayload
  'engine-gen:keybase1IdentifyUiDisplayStellarAccount': enginegen.Keybase1IdentifyUiDisplayStellarAccountPayload
  'engine-gen:keybase1IdentifyUiReportTrackToken': enginegen.Keybase1IdentifyUiReportTrackTokenPayload
  'engine-gen:keybase1IdentifyUiDisplayUserCard': enginegen.Keybase1IdentifyUiDisplayUserCardPayload
  'engine-gen:keybase1IdentifyUiConfirm': enginegen.Keybase1IdentifyUiConfirmPayload
  'engine-gen:keybase1IdentifyUiCancel': enginegen.Keybase1IdentifyUiCancelPayload
  'engine-gen:keybase1IdentifyUiFinish': enginegen.Keybase1IdentifyUiFinishPayload
  'engine-gen:keybase1IdentifyUiDismiss': enginegen.Keybase1IdentifyUiDismissPayload
  'engine-gen:keybase1LogUiLog': enginegen.Keybase1LogUiLogPayload
  'engine-gen:keybase1LoginUiGetEmailOrUsername': enginegen.Keybase1LoginUiGetEmailOrUsernamePayload
  'engine-gen:keybase1LoginUiPromptRevokePaperKeys': enginegen.Keybase1LoginUiPromptRevokePaperKeysPayload
  'engine-gen:keybase1LoginUiDisplayPaperKeyPhrase': enginegen.Keybase1LoginUiDisplayPaperKeyPhrasePayload
  'engine-gen:keybase1LoginUiDisplayPrimaryPaperKey': enginegen.Keybase1LoginUiDisplayPrimaryPaperKeyPayload
  'engine-gen:keybase1LoginUiPromptResetAccount': enginegen.Keybase1LoginUiPromptResetAccountPayload
  'engine-gen:keybase1LoginUiDisplayResetProgress': enginegen.Keybase1LoginUiDisplayResetProgressPayload
  'engine-gen:keybase1LoginUiExplainDeviceRecovery': enginegen.Keybase1LoginUiExplainDeviceRecoveryPayload
  'engine-gen:keybase1LoginUiPromptPassphraseRecovery': enginegen.Keybase1LoginUiPromptPassphraseRecoveryPayload
  'engine-gen:keybase1LoginUiChooseDeviceToRecoverWith': enginegen.Keybase1LoginUiChooseDeviceToRecoverWithPayload
  'engine-gen:keybase1LoginUiDisplayResetMessage': enginegen.Keybase1LoginUiDisplayResetMessagePayload
  'engine-gen:keybase1LogsendPrepareLogsend': enginegen.Keybase1LogsendPrepareLogsendPayload
  'engine-gen:keybase1NotifyAppExit': enginegen.Keybase1NotifyAppExitPayload
  'engine-gen:keybase1NotifyAuditRootAuditError': enginegen.Keybase1NotifyAuditRootAuditErrorPayload
  'engine-gen:keybase1NotifyAuditBoxAuditError': enginegen.Keybase1NotifyAuditBoxAuditErrorPayload
  'engine-gen:keybase1NotifyBadgesBadgeState': enginegen.Keybase1NotifyBadgesBadgeStatePayload
  'engine-gen:keybase1NotifyCanUserPerformCanUserPerformChanged': enginegen.Keybase1NotifyCanUserPerformCanUserPerformChangedPayload
  'engine-gen:keybase1NotifyDeviceCloneDeviceCloneCountChanged': enginegen.Keybase1NotifyDeviceCloneDeviceCloneCountChangedPayload
  'engine-gen:keybase1NotifyEmailAddressEmailAddressVerified': enginegen.Keybase1NotifyEmailAddressEmailAddressVerifiedPayload
  'engine-gen:keybase1NotifyEmailAddressEmailsChanged': enginegen.Keybase1NotifyEmailAddressEmailsChangedPayload
  'engine-gen:keybase1NotifyEphemeralNewTeamEk': enginegen.Keybase1NotifyEphemeralNewTeamEkPayload
  'engine-gen:keybase1NotifyEphemeralNewTeambotEk': enginegen.Keybase1NotifyEphemeralNewTeambotEkPayload
  'engine-gen:keybase1NotifyEphemeralTeambotEkNeeded': enginegen.Keybase1NotifyEphemeralTeambotEkNeededPayload
  'engine-gen:keybase1NotifyFavoritesFavoritesChanged': enginegen.Keybase1NotifyFavoritesFavoritesChangedPayload
  'engine-gen:keybase1NotifyFeaturedBotsFeaturedBotsUpdate': enginegen.Keybase1NotifyFeaturedBotsFeaturedBotsUpdatePayload
  'engine-gen:keybase1NotifyFSFSActivity': enginegen.Keybase1NotifyFSFSActivityPayload
  'engine-gen:keybase1NotifyFSFSPathUpdated': enginegen.Keybase1NotifyFSFSPathUpdatedPayload
  'engine-gen:keybase1NotifyFSFSSyncActivity': enginegen.Keybase1NotifyFSFSSyncActivityPayload
  'engine-gen:keybase1NotifyFSFSEditListResponse': enginegen.Keybase1NotifyFSFSEditListResponsePayload
  'engine-gen:keybase1NotifyFSFSSyncStatusResponse': enginegen.Keybase1NotifyFSFSSyncStatusResponsePayload
  'engine-gen:keybase1NotifyFSFSOverallSyncStatusChanged': enginegen.Keybase1NotifyFSFSOverallSyncStatusChangedPayload
  'engine-gen:keybase1NotifyFSFSFavoritesChanged': enginegen.Keybase1NotifyFSFSFavoritesChangedPayload
  'engine-gen:keybase1NotifyFSFSOnlineStatusChanged': enginegen.Keybase1NotifyFSFSOnlineStatusChangedPayload
  'engine-gen:keybase1NotifyFSFSSubscriptionNotifyPath': enginegen.Keybase1NotifyFSFSSubscriptionNotifyPathPayload
  'engine-gen:keybase1NotifyFSFSSubscriptionNotify': enginegen.Keybase1NotifyFSFSSubscriptionNotifyPayload
  'engine-gen:keybase1NotifyInviteFriendsUpdateInviteCounts': enginegen.Keybase1NotifyInviteFriendsUpdateInviteCountsPayload
  'engine-gen:keybase1NotifyKeyfamilyKeyfamilyChanged': enginegen.Keybase1NotifyKeyfamilyKeyfamilyChangedPayload
  'engine-gen:keybase1NotifyPaperKeyPaperKeyCached': enginegen.Keybase1NotifyPaperKeyPaperKeyCachedPayload
  'engine-gen:keybase1NotifyPGPPgpKeyInSecretStoreFile': enginegen.Keybase1NotifyPGPPgpKeyInSecretStoreFilePayload
  'engine-gen:keybase1NotifyPhoneNumberPhoneNumbersChanged': enginegen.Keybase1NotifyPhoneNumberPhoneNumbersChangedPayload
  'engine-gen:keybase1NotifyRuntimeStatsRuntimeStatsUpdate': enginegen.Keybase1NotifyRuntimeStatsRuntimeStatsUpdatePayload
  'engine-gen:keybase1NotifySaltpackSaltpackOperationStart': enginegen.Keybase1NotifySaltpackSaltpackOperationStartPayload
  'engine-gen:keybase1NotifySaltpackSaltpackOperationProgress': enginegen.Keybase1NotifySaltpackSaltpackOperationProgressPayload
  'engine-gen:keybase1NotifySaltpackSaltpackOperationDone': enginegen.Keybase1NotifySaltpackSaltpackOperationDonePayload
  'engine-gen:keybase1NotifyServiceHTTPSrvInfoUpdate': enginegen.Keybase1NotifyServiceHTTPSrvInfoUpdatePayload
  'engine-gen:keybase1NotifyServiceHandleKeybaseLink': enginegen.Keybase1NotifyServiceHandleKeybaseLinkPayload
  'engine-gen:keybase1NotifyServiceShutdown': enginegen.Keybase1NotifyServiceShutdownPayload
  'engine-gen:keybase1NotifySessionLoggedOut': enginegen.Keybase1NotifySessionLoggedOutPayload
  'engine-gen:keybase1NotifySessionLoggedIn': enginegen.Keybase1NotifySessionLoggedInPayload
  'engine-gen:keybase1NotifySessionClientOutOfDate': enginegen.Keybase1NotifySessionClientOutOfDatePayload
  'engine-gen:keybase1NotifyTeamTeamChangedByID': enginegen.Keybase1NotifyTeamTeamChangedByIDPayload
  'engine-gen:keybase1NotifyTeamTeamChangedByName': enginegen.Keybase1NotifyTeamTeamChangedByNamePayload
  'engine-gen:keybase1NotifyTeamTeamDeleted': enginegen.Keybase1NotifyTeamTeamDeletedPayload
  'engine-gen:keybase1NotifyTeamTeamAbandoned': enginegen.Keybase1NotifyTeamTeamAbandonedPayload
  'engine-gen:keybase1NotifyTeamTeamExit': enginegen.Keybase1NotifyTeamTeamExitPayload
  'engine-gen:keybase1NotifyTeamNewlyAddedToTeam': enginegen.Keybase1NotifyTeamNewlyAddedToTeamPayload
  'engine-gen:keybase1NotifyTeamTeamRoleMapChanged': enginegen.Keybase1NotifyTeamTeamRoleMapChangedPayload
  'engine-gen:keybase1NotifyTeamAvatarUpdated': enginegen.Keybase1NotifyTeamAvatarUpdatedPayload
  'engine-gen:keybase1NotifyTeamTeamMetadataUpdate': enginegen.Keybase1NotifyTeamTeamMetadataUpdatePayload
  'engine-gen:keybase1NotifyTeamTeamTreeMembershipsPartial': enginegen.Keybase1NotifyTeamTeamTreeMembershipsPartialPayload
  'engine-gen:keybase1NotifyTeamTeamTreeMembershipsDone': enginegen.Keybase1NotifyTeamTeamTreeMembershipsDonePayload
  'engine-gen:keybase1NotifyTeambotNewTeambotKey': enginegen.Keybase1NotifyTeambotNewTeambotKeyPayload
  'engine-gen:keybase1NotifyTeambotTeambotKeyNeeded': enginegen.Keybase1NotifyTeambotTeambotKeyNeededPayload
  'engine-gen:keybase1NotifyTrackingTrackingChanged': enginegen.Keybase1NotifyTrackingTrackingChangedPayload
  'engine-gen:keybase1NotifyTrackingTrackingInfo': enginegen.Keybase1NotifyTrackingTrackingInfoPayload
  'engine-gen:keybase1NotifyTrackingNotifyUserBlocked': enginegen.Keybase1NotifyTrackingNotifyUserBlockedPayload
  'engine-gen:keybase1NotifyUsersUserChanged': enginegen.Keybase1NotifyUsersUserChangedPayload
  'engine-gen:keybase1NotifyUsersWebOfTrustChanged': enginegen.Keybase1NotifyUsersWebOfTrustChangedPayload
  'engine-gen:keybase1NotifyUsersPasswordChanged': enginegen.Keybase1NotifyUsersPasswordChangedPayload
  'engine-gen:keybase1NotifyUsersIdentifyUpdate': enginegen.Keybase1NotifyUsersIdentifyUpdatePayload
  'engine-gen:keybase1PgpUiOutputPGPWarning': enginegen.Keybase1PgpUiOutputPGPWarningPayload
  'engine-gen:keybase1PgpUiOutputSignatureSuccess': enginegen.Keybase1PgpUiOutputSignatureSuccessPayload
  'engine-gen:keybase1PgpUiOutputSignatureNonKeybase': enginegen.Keybase1PgpUiOutputSignatureNonKeybasePayload
  'engine-gen:keybase1PgpUiKeyGenerated': enginegen.Keybase1PgpUiKeyGeneratedPayload
  'engine-gen:keybase1PgpUiShouldPushPrivate': enginegen.Keybase1PgpUiShouldPushPrivatePayload
  'engine-gen:keybase1PgpUiFinished': enginegen.Keybase1PgpUiFinishedPayload
  'engine-gen:keybase1ProveUiPromptOverwrite': enginegen.Keybase1ProveUiPromptOverwritePayload
  'engine-gen:keybase1ProveUiPromptUsername': enginegen.Keybase1ProveUiPromptUsernamePayload
  'engine-gen:keybase1ProveUiOutputPrechecks': enginegen.Keybase1ProveUiOutputPrechecksPayload
  'engine-gen:keybase1ProveUiPreProofWarning': enginegen.Keybase1ProveUiPreProofWarningPayload
  'engine-gen:keybase1ProveUiOutputInstructions': enginegen.Keybase1ProveUiOutputInstructionsPayload
  'engine-gen:keybase1ProveUiOkToCheck': enginegen.Keybase1ProveUiOkToCheckPayload
  'engine-gen:keybase1ProveUiChecking': enginegen.Keybase1ProveUiCheckingPayload
  'engine-gen:keybase1ProveUiContinueChecking': enginegen.Keybase1ProveUiContinueCheckingPayload
  'engine-gen:keybase1ProveUiDisplayRecheckWarning': enginegen.Keybase1ProveUiDisplayRecheckWarningPayload
  'engine-gen:keybase1ProvisionUiChooseProvisioningMethod': enginegen.Keybase1ProvisionUiChooseProvisioningMethodPayload
  'engine-gen:keybase1ProvisionUiChooseGPGMethod': enginegen.Keybase1ProvisionUiChooseGPGMethodPayload
  'engine-gen:keybase1ProvisionUiSwitchToGPGSignOK': enginegen.Keybase1ProvisionUiSwitchToGPGSignOKPayload
  'engine-gen:keybase1ProvisionUiChooseDevice': enginegen.Keybase1ProvisionUiChooseDevicePayload
  'engine-gen:keybase1ProvisionUiChooseDeviceType': enginegen.Keybase1ProvisionUiChooseDeviceTypePayload
  'engine-gen:keybase1ProvisionUiDisplayAndPromptSecret': enginegen.Keybase1ProvisionUiDisplayAndPromptSecretPayload
  'engine-gen:keybase1ProvisionUiDisplaySecretExchanged': enginegen.Keybase1ProvisionUiDisplaySecretExchangedPayload
  'engine-gen:keybase1ProvisionUiPromptNewDeviceName': enginegen.Keybase1ProvisionUiPromptNewDeviceNamePayload
  'engine-gen:keybase1ProvisionUiProvisioneeSuccess': enginegen.Keybase1ProvisionUiProvisioneeSuccessPayload
  'engine-gen:keybase1ProvisionUiProvisionerSuccess': enginegen.Keybase1ProvisionUiProvisionerSuccessPayload
  'engine-gen:keybase1ReachabilityReachabilityChanged': enginegen.Keybase1ReachabilityReachabilityChangedPayload
  'engine-gen:keybase1RekeyUIDelegateRekeyUI': enginegen.Keybase1RekeyUIDelegateRekeyUIPayload
  'engine-gen:keybase1RekeyUIRefresh': enginegen.Keybase1RekeyUIRefreshPayload
  'engine-gen:keybase1RekeyUIRekeySendEvent': enginegen.Keybase1RekeyUIRekeySendEventPayload
  'engine-gen:keybase1SaltpackUiSaltpackPromptForDecrypt': enginegen.Keybase1SaltpackUiSaltpackPromptForDecryptPayload
  'engine-gen:keybase1SaltpackUiSaltpackVerifySuccess': enginegen.Keybase1SaltpackUiSaltpackVerifySuccessPayload
  'engine-gen:keybase1SaltpackUiSaltpackVerifyBadSender': enginegen.Keybase1SaltpackUiSaltpackVerifyBadSenderPayload
  'engine-gen:keybase1SecretUiGetPassphrase': enginegen.Keybase1SecretUiGetPassphrasePayload
  'engine-gen:keybase1StreamUiClose': enginegen.Keybase1StreamUiClosePayload
  'engine-gen:keybase1StreamUiRead': enginegen.Keybase1StreamUiReadPayload
  'engine-gen:keybase1StreamUiReset': enginegen.Keybase1StreamUiResetPayload
  'engine-gen:keybase1StreamUiWrite': enginegen.Keybase1StreamUiWritePayload
  'engine-gen:keybase1TeamsUiConfirmRootTeamDelete': enginegen.Keybase1TeamsUiConfirmRootTeamDeletePayload
  'engine-gen:keybase1TeamsUiConfirmSubteamDelete': enginegen.Keybase1TeamsUiConfirmSubteamDeletePayload
  'engine-gen:keybase1TeamsUiConfirmInviteLinkAccept': enginegen.Keybase1TeamsUiConfirmInviteLinkAcceptPayload
  'engine-gen:keybase1UiPromptYesNo': enginegen.Keybase1UiPromptYesNoPayload
  'engine-gen:stellar1NotifyPaymentNotification': enginegen.Stellar1NotifyPaymentNotificationPayload
  'engine-gen:stellar1NotifyPaymentStatusNotification': enginegen.Stellar1NotifyPaymentStatusNotificationPayload
  'engine-gen:stellar1NotifyRequestStatusNotification': enginegen.Stellar1NotifyRequestStatusNotificationPayload
  'engine-gen:stellar1NotifyAccountDetailsUpdate': enginegen.Stellar1NotifyAccountDetailsUpdatePayload
  'engine-gen:stellar1NotifyAccountsUpdate': enginegen.Stellar1NotifyAccountsUpdatePayload
  'engine-gen:stellar1NotifyPendingPaymentsUpdate': enginegen.Stellar1NotifyPendingPaymentsUpdatePayload
  'engine-gen:stellar1NotifyRecentPaymentsUpdate': enginegen.Stellar1NotifyRecentPaymentsUpdatePayload
  'engine-gen:stellar1UiPaymentReviewed': enginegen.Stellar1UiPaymentReviewedPayload
  'fs:subscribePath': fs.SubscribePathPayload
  'fs:subscribeNonPath': fs.SubscribeNonPathPayload
  'fs:unsubscribe': fs.UnsubscribePayload
  'fs:pollJournalStatus': fs.PollJournalStatusPayload
  'fs:getOnlineStatus': fs.GetOnlineStatusPayload
  'fs:folderListLoad': fs.FolderListLoadPayload
  'fs:folderListLoaded': fs.FolderListLoadedPayload
  'fs:favoritesLoad': fs.FavoritesLoadPayload
  'fs:favoritesLoaded': fs.FavoritesLoadedPayload
  'fs:setFolderViewFilter': fs.SetFolderViewFilterPayload
  'fs:tlfSyncConfigLoaded': fs.TlfSyncConfigLoadedPayload
  'fs:loadTlfSyncConfig': fs.LoadTlfSyncConfigPayload
  'fs:setTlfSyncConfig': fs.SetTlfSyncConfigPayload
  'fs:pathItemLoaded': fs.PathItemLoadedPayload
  'fs:loadPathMetadata': fs.LoadPathMetadataPayload
  'fs:sortSetting': fs.SortSettingPayload
  'fs:shareNative': fs.ShareNativePayload
  'fs:saveMedia': fs.SaveMediaPayload
  'fs:upload': fs.UploadPayload
  'fs:uploadFromDragAndDrop': fs.UploadFromDragAndDropPayload
  'fs:loadUploadStatus': fs.LoadUploadStatusPayload
  'fs:loadedUploadStatus': fs.LoadedUploadStatusPayload
  'fs:dismissUpload': fs.DismissUploadPayload
  'fs:journalUpdate': fs.JournalUpdatePayload
  'fs:openLocalPathInSystemFileManager': fs.OpenLocalPathInSystemFileManagerPayload
  'fs:openPathInSystemFileManager': fs.OpenPathInSystemFileManagerPayload
  'fs:uninstallKBFSConfirm': fs.UninstallKBFSConfirmPayload
  'fs:refreshDriverStatus': fs.RefreshDriverStatusPayload
  'fs:setDriverStatus': fs.SetDriverStatusPayload
  'fs:setSfmiBannerDismissed': fs.SetSfmiBannerDismissedPayload
  'fs:driverEnable': fs.DriverEnablePayload
  'fs:driverDisable': fs.DriverDisablePayload
  'fs:driverDisabling': fs.DriverDisablingPayload
  'fs:driverKextPermissionError': fs.DriverKextPermissionErrorPayload
  'fs:startManualConflictResolution': fs.StartManualConflictResolutionPayload
  'fs:finishManualConflictResolution': fs.FinishManualConflictResolutionPayload
  'fs:openSecurityPreferences': fs.OpenSecurityPreferencesPayload
  'fs:favoriteIgnore': fs.FavoriteIgnorePayload
  'fs:favoriteIgnoreError': fs.FavoriteIgnoreErrorPayload
  'fs:newFolderRow': fs.NewFolderRowPayload
  'fs:startRename': fs.StartRenamePayload
  'fs:setEditName': fs.SetEditNamePayload
  'fs:commitEdit': fs.CommitEditPayload
  'fs:editSuccess': fs.EditSuccessPayload
  'fs:editError': fs.EditErrorPayload
  'fs:discardEdit': fs.DiscardEditPayload
  'fs:redbar': fs.RedbarPayload
  'fs:dismissRedbar': fs.DismissRedbarPayload
  'fs:setLastPublicBannerClosedTlf': fs.SetLastPublicBannerClosedTlfPayload
  'fs:openFilesFromWidget': fs.OpenFilesFromWidgetPayload
  'fs:letResetUserBackIn': fs.LetResetUserBackInPayload
  'fs:openAndUpload': fs.OpenAndUploadPayload
  'fs:pickAndUpload': fs.PickAndUploadPayload
  'fs:userFileEditsLoad': fs.UserFileEditsLoadPayload
  'fs:userFileEditsLoaded': fs.UserFileEditsLoadedPayload
  'fs:deleteFile': fs.DeleteFilePayload
  'fs:setMoveOrCopySource': fs.SetMoveOrCopySourcePayload
  'fs:setDestinationPickerParentPath': fs.SetDestinationPickerParentPathPayload
  'fs:showMoveOrCopy': fs.ShowMoveOrCopyPayload
  'fs:setIncomingShareSource': fs.SetIncomingShareSourcePayload
  'fs:showIncomingShare': fs.ShowIncomingSharePayload
  'fs:move': fs.MovePayload
  'fs:copy': fs.CopyPayload
  'fs:setPathItemActionMenuView': fs.SetPathItemActionMenuViewPayload
  'fs:checkKbfsDaemonRpcStatus': fs.CheckKbfsDaemonRpcStatusPayload
  'fs:waitForKbfsDaemon': fs.WaitForKbfsDaemonPayload
  'fs:kbfsDaemonRpcStatusChanged': fs.KbfsDaemonRpcStatusChangedPayload
  'fs:kbfsDaemonOnlineStatusChanged': fs.KbfsDaemonOnlineStatusChangedPayload
  'fs:overallSyncStatusChanged': fs.OverallSyncStatusChangedPayload
  'fs:showHideDiskSpaceBanner': fs.ShowHideDiskSpaceBannerPayload
  'fs:setPathSoftError': fs.SetPathSoftErrorPayload
  'fs:setTlfSoftError': fs.SetTlfSoftErrorPayload
  'fs:loadSettings': fs.LoadSettingsPayload
  'fs:settingsLoaded': fs.SettingsLoadedPayload
  'fs:setSpaceAvailableNotificationThreshold': fs.SetSpaceAvailableNotificationThresholdPayload
  'fs:setTlfsAsUnloaded': fs.SetTlfsAsUnloadedPayload
  'fs:placeholderAction': fs.PlaceholderActionPayload
  'fs:refreshMountDirsAfter10s': fs.RefreshMountDirsAfter10sPayload
  'fs:setDirectMountDir': fs.SetDirectMountDirPayload
  'fs:setPreferredMountDirs': fs.SetPreferredMountDirsPayload
  'fs:loadPathInfo': fs.LoadPathInfoPayload
  'fs:loadedPathInfo': fs.LoadedPathInfoPayload
  'fs:download': fs.DownloadPayload
  'fs:loadDownloadStatus': fs.LoadDownloadStatusPayload
  'fs:loadDownloadInfo': fs.LoadDownloadInfoPayload
  'fs:loadedDownloadStatus': fs.LoadedDownloadStatusPayload
  'fs:loadedDownloadInfo': fs.LoadedDownloadInfoPayload
  'fs:cancelDownload': fs.CancelDownloadPayload
  'fs:dismissDownload': fs.DismissDownloadPayload
  'fs:setPathItemActionMenuDownload': fs.SetPathItemActionMenuDownloadPayload
  'fs:finishedDownloadWithIntent': fs.FinishedDownloadWithIntentPayload
  'fs:finishedRegularDownload': fs.FinishedRegularDownloadPayload
  'fs:loadFileContext': fs.LoadFileContextPayload
  'fs:loadedFileContext': fs.LoadedFileContextPayload
  'fs:loadAdditionalTlf': fs.LoadAdditionalTlfPayload
  'fs:loadedAdditionalTlf': fs.LoadedAdditionalTlfPayload
  'fs:loadFilesTabBadge': fs.LoadFilesTabBadgePayload
  'fs:loadedFilesTabBadge': fs.LoadedFilesTabBadgePayload
  'fs:userIn': fs.UserInPayload
  'fs:userOut': fs.UserOutPayload
  'fs:setDebugLevel': fs.SetDebugLevelPayload
  'fs:setCriticalUpdate': fs.SetCriticalUpdatePayload
  'git:loadGit': git.LoadGitPayload
  'git:loaded': git.LoadedPayload
  'git:createTeamRepo': git.CreateTeamRepoPayload
  'git:createPersonalRepo': git.CreatePersonalRepoPayload
  'git:repoDeleted': git.RepoDeletedPayload
  'git:repoCreated': git.RepoCreatedPayload
  'git:deleteTeamRepo': git.DeleteTeamRepoPayload
  'git:deletePersonalRepo': git.DeletePersonalRepoPayload
  'git:setError': git.SetErrorPayload
  'git:badgeAppForGit': git.BadgeAppForGitPayload
  'git:setTeamRepoSettings': git.SetTeamRepoSettingsPayload
  'git:navigateToTeamRepo': git.NavigateToTeamRepoPayload
  'git:clearBadges': git.ClearBadgesPayload
  'gregor:pushState': gregor.PushStatePayload
  'gregor:checkReachability': gregor.CheckReachabilityPayload
  'gregor:pushOOBM': gregor.PushOOBMPayload
  'gregor:updateReachable': gregor.UpdateReachablePayload
  'gregor:updateCategory': gregor.UpdateCategoryPayload
  'login:login': login.LoginPayload
  'login:loginError': login.LoginErrorPayload
  'login:loadIsOnline': login.LoadIsOnlinePayload
  'login:loadedIsOnline': login.LoadedIsOnlinePayload
  'notifications:badgeApp': notifications.BadgeAppPayload
  'notifications:receivedBadgeState': notifications.ReceivedBadgeStatePayload
  'notifications:setBadgeCounts': notifications.SetBadgeCountsPayload
  'notifications:listenForNotifications': notifications.ListenForNotificationsPayload
  'notifications:listenForKBFSNotifications': notifications.ListenForKBFSNotificationsPayload
  'people:getPeopleData': people.GetPeopleDataPayload
  'people:peopleDataProcessed': people.PeopleDataProcessedPayload
  'people:dismissAnnouncement': people.DismissAnnouncementPayload
  'people:dismissWotNotifications': people.DismissWotNotificationsPayload
  'people:badgeAppForWotNotifications': people.BadgeAppForWotNotificationsPayload
  'people:markViewed': people.MarkViewedPayload
  'people:skipTodo': people.SkipTodoPayload
  'people:setResentEmail': people.SetResentEmailPayload
  'pinentry:newPinentry': pinentry.NewPinentryPayload
  'pinentry:close': pinentry.ClosePayload
  'pinentry:onSubmit': pinentry.OnSubmitPayload
  'pinentry:onCancel': pinentry.OnCancelPayload
  'profile:addProof': profile.AddProofPayload
  'profile:proofParamsReceived': profile.ProofParamsReceivedPayload
  'profile:updatePlatformGenericURL': profile.UpdatePlatformGenericURLPayload
  'profile:updatePlatformGenericChecking': profile.UpdatePlatformGenericCheckingPayload
  'profile:clearPlatformGeneric': profile.ClearPlatformGenericPayload
  'profile:backToProfile': profile.BackToProfilePayload
  'profile:cancelAddProof': profile.CancelAddProofPayload
  'profile:cancelPgpGen': profile.CancelPgpGenPayload
  'profile:checkProof': profile.CheckProofPayload
  'profile:recheckProof': profile.RecheckProofPayload
  'profile:cleanupUsername': profile.CleanupUsernamePayload
  'profile:uploadAvatar': profile.UploadAvatarPayload
  'profile:editAvatar': profile.EditAvatarPayload
  'profile:editProfile': profile.EditProfilePayload
  'profile:revokeFinish': profile.RevokeFinishPayload
  'profile:finishRevoking': profile.FinishRevokingPayload
  'profile:finishedWithKeyGen': profile.FinishedWithKeyGenPayload
  'profile:generatePgp': profile.GeneratePgpPayload
  'profile:hideStellar': profile.HideStellarPayload
  'profile:onClickAvatar': profile.OnClickAvatarPayload
  'profile:showUserProfile': profile.ShowUserProfilePayload
  'profile:submitZcashAddress': profile.SubmitZcashAddressPayload
  'profile:submitBTCAddress': profile.SubmitBTCAddressPayload
  'profile:submitRevokeProof': profile.SubmitRevokeProofPayload
  'profile:submitUsername': profile.SubmitUsernamePayload
  'profile:submitBlockUser': profile.SubmitBlockUserPayload
  'profile:submitUnblockUser': profile.SubmitUnblockUserPayload
  'profile:finishBlockUser': profile.FinishBlockUserPayload
  'profile:updateErrorText': profile.UpdateErrorTextPayload
  'profile:updatePgpInfo': profile.UpdatePgpInfoPayload
  'profile:updatePgpPublicKey': profile.UpdatePgpPublicKeyPayload
  'profile:updatePlatform': profile.UpdatePlatformPayload
  'profile:updatePromptShouldStoreKeyOnServer': profile.UpdatePromptShouldStoreKeyOnServerPayload
  'profile:updateProofStatus': profile.UpdateProofStatusPayload
  'profile:updateProofText': profile.UpdateProofTextPayload
  'profile:updateSigID': profile.UpdateSigIDPayload
  'profile:updateUsername': profile.UpdateUsernamePayload
  'profile:wotVouch': profile.WotVouchPayload
  'profile:wotVouchSetError': profile.WotVouchSetErrorPayload
  'provision:startProvision': provision.StartProvisionPayload
  'provision:provisionError': provision.ProvisionErrorPayload
  'provision:submitUsername': provision.SubmitUsernamePayload
  'provision:submitPassword': provision.SubmitPasswordPayload
  'provision:submitPaperkey': provision.SubmitPaperkeyPayload
  'provision:submitTextCode': provision.SubmitTextCodePayload
  'provision:submitDeviceSelect': provision.SubmitDeviceSelectPayload
  'provision:submitDeviceName': provision.SubmitDeviceNamePayload
  'provision:submitGPGMethod': provision.SubmitGPGMethodPayload
  'provision:switchToGPGSignOnly': provision.SwitchToGPGSignOnlyPayload
  'provision:submitGPGSignOK': provision.SubmitGPGSignOKPayload
  'provision:showDeviceListPage': provision.ShowDeviceListPagePayload
  'provision:showNewDeviceNamePage': provision.ShowNewDeviceNamePagePayload
  'provision:showCodePage': provision.ShowCodePagePayload
  'provision:showFinalErrorPage': provision.ShowFinalErrorPagePayload
  'provision:showGPGPage': provision.ShowGPGPagePayload
  'provision:showInlineError': provision.ShowInlineErrorPayload
  'provision:showPasswordPage': provision.ShowPasswordPagePayload
  'provision:showPaperkeyPage': provision.ShowPaperkeyPagePayload
  'provision:addNewDevice': provision.AddNewDevicePayload
  'provision:forgotUsername': provision.ForgotUsernamePayload
  'provision:forgotUsernameResult': provision.ForgotUsernameResultPayload
  'provision:cancelProvision': provision.CancelProvisionPayload
  'provision:backToDeviceList': provision.BackToDeviceListPayload
  'provision:provisionDone': provision.ProvisionDonePayload
  'push:rejectPermissions': push.RejectPermissionsPayload
  'push:requestPermissions': push.RequestPermissionsPayload
  'push:showPermissionsPrompt': push.ShowPermissionsPromptPayload
  'push:updatePushToken': push.UpdatePushTokenPayload
  'push:updateHasPermissions': push.UpdateHasPermissionsPayload
  'push:notification': push.NotificationPayload
  'recover-password:startRecoverPassword': recoverpassword.StartRecoverPasswordPayload
  'recover-password:restartRecovery': recoverpassword.RestartRecoveryPayload
  'recover-password:displayDeviceSelect': recoverpassword.DisplayDeviceSelectPayload
  'recover-password:submitDeviceSelect': recoverpassword.SubmitDeviceSelectPayload
  'recover-password:abortDeviceSelect': recoverpassword.AbortDeviceSelectPayload
  'recover-password:showExplainDevice': recoverpassword.ShowExplainDevicePayload
  'recover-password:setPaperKeyError': recoverpassword.SetPaperKeyErrorPayload
  'recover-password:submitPaperKey': recoverpassword.SubmitPaperKeyPayload
  'recover-password:submitResetPrompt': recoverpassword.SubmitResetPromptPayload
  'recover-password:abortPaperKey': recoverpassword.AbortPaperKeyPayload
  'recover-password:setPasswordError': recoverpassword.SetPasswordErrorPayload
  'recover-password:submitPassword': recoverpassword.SubmitPasswordPayload
  'recover-password:promptResetPassword': recoverpassword.PromptResetPasswordPayload
  'recover-password:submitResetPassword': recoverpassword.SubmitResetPasswordPayload
  'recover-password:completeResetPassword': recoverpassword.CompleteResetPasswordPayload
  'recover-password:resetResetPasswordState': recoverpassword.ResetResetPasswordStatePayload
  'recover-password:displayError': recoverpassword.DisplayErrorPayload
  'route-tree:navigateAppend': routetree.NavigateAppendPayload
  'route-tree:navigateUp': routetree.NavigateUpPayload
  'route-tree:clearModals': routetree.ClearModalsPayload
  'route-tree:navUpToScreen': routetree.NavUpToScreenPayload
  'route-tree:switchLoggedIn': routetree.SwitchLoggedInPayload
  'route-tree:switchTab': routetree.SwitchTabPayload
  'route-tree:resetStack': routetree.ResetStackPayload
  'route-tree:onNavChanged': routetree.OnNavChangedPayload
  'route-tree:setParams': routetree.SetParamsPayload
  'settings:addPhoneNumber': settings.AddPhoneNumberPayload
  'settings:addedPhoneNumber': settings.AddedPhoneNumberPayload
  'settings:resendVerificationForPhoneNumber': settings.ResendVerificationForPhoneNumberPayload
  'settings:verifyPhoneNumber': settings.VerifyPhoneNumberPayload
  'settings:verifiedPhoneNumber': settings.VerifiedPhoneNumberPayload
  'settings:clearPhoneNumberAdd': settings.ClearPhoneNumberAddPayload
  'settings:clearPhoneNumberErrors': settings.ClearPhoneNumberErrorsPayload
  'settings:dbNuke': settings.DbNukePayload
  'settings:deleteAccountForever': settings.DeleteAccountForeverPayload
  'settings:editEmail': settings.EditEmailPayload
  'settings:editPhone': settings.EditPhonePayload
  'settings:sentVerificationEmail': settings.SentVerificationEmailPayload
  'settings:emailVerified': settings.EmailVerifiedPayload
  'settings:loadContactImportEnabled': settings.LoadContactImportEnabledPayload
  'settings:loadedContactImportEnabled': settings.LoadedContactImportEnabledPayload
  'settings:loadedContactPermissions': settings.LoadedContactPermissionsPayload
  'settings:requestContactPermissions': settings.RequestContactPermissionsPayload
  'settings:editContactImportEnabled': settings.EditContactImportEnabledPayload
  'settings:showContactsJoinedModal': settings.ShowContactsJoinedModalPayload
  'settings:importContactsLater': settings.ImportContactsLaterPayload
  'settings:setContactImportedCount': settings.SetContactImportedCountPayload
  'settings:loadedUserCountryCode': settings.LoadedUserCountryCodePayload
  'settings:addEmail': settings.AddEmailPayload
  'settings:addedEmail': settings.AddedEmailPayload
  'settings:clearAddingEmail': settings.ClearAddingEmailPayload
  'settings:clearAddedEmail': settings.ClearAddedEmailPayload
  'settings:clearAddedPhone': settings.ClearAddedPhonePayload
  'settings:invitesClearError': settings.InvitesClearErrorPayload
  'settings:invitesReclaim': settings.InvitesReclaimPayload
  'settings:invitesRefresh': settings.InvitesRefreshPayload
  'settings:invitesRefreshed': settings.InvitesRefreshedPayload
  'settings:invitesSend': settings.InvitesSendPayload
  'settings:invitesSent': settings.InvitesSentPayload
  'settings:loadRememberPassword': settings.LoadRememberPasswordPayload
  'settings:loadedRememberPassword': settings.LoadedRememberPasswordPayload
  'settings:loadSettings': settings.LoadSettingsPayload
  'settings:loadedSettings': settings.LoadedSettingsPayload
  'settings:loadLockdownMode': settings.LoadLockdownModePayload
  'settings:loadedLockdownMode': settings.LoadedLockdownModePayload
  'settings:onChangeLockdownMode': settings.OnChangeLockdownModePayload
  'settings:notificationsRefresh': settings.NotificationsRefreshPayload
  'settings:notificationsRefreshed': settings.NotificationsRefreshedPayload
  'settings:notificationsSaved': settings.NotificationsSavedPayload
  'settings:notificationsToggle': settings.NotificationsTogglePayload
  'settings:onChangeNewEmail': settings.OnChangeNewEmailPayload
  'settings:onChangeNewPassword': settings.OnChangeNewPasswordPayload
  'settings:onChangeNewPasswordConfirm': settings.OnChangeNewPasswordConfirmPayload
  'settings:onChangeRememberPassword': settings.OnChangeRememberPasswordPayload
  'settings:onChangeShowPassword': settings.OnChangeShowPasswordPayload
  'settings:onSubmitNewEmail': settings.OnSubmitNewEmailPayload
  'settings:onSubmitNewPassword': settings.OnSubmitNewPasswordPayload
  'settings:onUpdateEmailError': settings.OnUpdateEmailErrorPayload
  'settings:onUpdatePGPSettings': settings.OnUpdatePGPSettingsPayload
  'settings:onUpdatePasswordError': settings.OnUpdatePasswordErrorPayload
  'settings:onUpdatedPGPSettings': settings.OnUpdatedPGPSettingsPayload
  'settings:stop': settings.StopPayload
  'settings:trace': settings.TracePayload
  'settings:processorProfile': settings.ProcessorProfilePayload
  'settings:unfurlSettingsSaved': settings.UnfurlSettingsSavedPayload
  'settings:unfurlSettingsRefresh': settings.UnfurlSettingsRefreshPayload
  'settings:unfurlSettingsRefreshed': settings.UnfurlSettingsRefreshedPayload
  'settings:unfurlSettingsError': settings.UnfurlSettingsErrorPayload
  'settings:contactSettingsError': settings.ContactSettingsErrorPayload
  'settings:contactSettingsRefresh': settings.ContactSettingsRefreshPayload
  'settings:contactSettingsRefreshed': settings.ContactSettingsRefreshedPayload
  'settings:contactSettingsSaved': settings.ContactSettingsSavedPayload
  'settings:loadHasRandomPw': settings.LoadHasRandomPwPayload
  'settings:loadedHasRandomPw': settings.LoadedHasRandomPwPayload
  'settings:resetCheckPasswordIsCorrect': settings.ResetCheckPasswordIsCorrectPayload
  'settings:checkPassword': settings.CheckPasswordPayload
  'settings:loadedCheckPassword': settings.LoadedCheckPasswordPayload
  'settings:sendFeedback': settings.SendFeedbackPayload
  'settings:feedbackSent': settings.FeedbackSentPayload
  'settings:loadProxyData': settings.LoadProxyDataPayload
  'settings:loadedProxyData': settings.LoadedProxyDataPayload
  'settings:saveProxyData': settings.SaveProxyDataPayload
  'settings:certificatePinningToggled': settings.CertificatePinningToggledPayload
  'settings:loadDefaultPhoneNumberCountry': settings.LoadDefaultPhoneNumberCountryPayload
  'settings:updateDefaultPhoneNumberCountry': settings.UpdateDefaultPhoneNumberCountryPayload
  'settings:loginBrowserViaWebAuthToken': settings.LoginBrowserViaWebAuthTokenPayload
  'signup:goBackAndClearErrors': signup.GoBackAndClearErrorsPayload
  'signup:requestAutoInvite': signup.RequestAutoInvitePayload
  'signup:requestedAutoInvite': signup.RequestedAutoInvitePayload
  'signup:checkInviteCode': signup.CheckInviteCodePayload
  'signup:checkedInviteCode': signup.CheckedInviteCodePayload
  'signup:checkPassword': signup.CheckPasswordPayload
  'signup:checkUsername': signup.CheckUsernamePayload
  'signup:checkedUsername': signup.CheckedUsernamePayload
  'signup:requestInvite': signup.RequestInvitePayload
  'signup:requestedInvite': signup.RequestedInvitePayload
  'signup:restartSignup': signup.RestartSignupPayload
  'signup:signedup': signup.SignedupPayload
  'signup:checkDevicename': signup.CheckDevicenamePayload
  'signup:checkedDevicename': signup.CheckedDevicenamePayload
  'signup:setJustSignedUpEmail': signup.SetJustSignedUpEmailPayload
  'signup:clearJustSignedUpEmail': signup.ClearJustSignedUpEmailPayload
  'team-building:fetchedUserRecs': teambuilding.FetchedUserRecsPayload
  'team-building:fetchUserRecs': teambuilding.FetchUserRecsPayload
  'team-building:finishTeamBuilding': teambuilding.FinishTeamBuildingPayload
  'team-building:setError': teambuilding.SetErrorPayload
  'team-building:finishedTeamBuilding': teambuilding.FinishedTeamBuildingPayload
  'team-building:cancelTeamBuilding': teambuilding.CancelTeamBuildingPayload
  'team-building:search': teambuilding.SearchPayload
  'team-building:addUsersToTeamSoFar': teambuilding.AddUsersToTeamSoFarPayload
  'team-building:removeUsersFromTeamSoFar': teambuilding.RemoveUsersFromTeamSoFarPayload
  'team-building:searchResultsLoaded': teambuilding.SearchResultsLoadedPayload
  'team-building:selectRole': teambuilding.SelectRolePayload
  'team-building:changeSendNotification': teambuilding.ChangeSendNotificationPayload
  'team-building:labelsSeen': teambuilding.LabelsSeenPayload
  'team-building:tbResetStore': teambuilding.TbResetStorePayload
  'teams:addUserToTeams': teams.AddUserToTeamsPayload
  'teams:channelSetMemberSelected': teams.ChannelSetMemberSelectedPayload
  'teams:clearNavBadges': teams.ClearNavBadgesPayload
  'teams:createNewTeam': teams.CreateNewTeamPayload
  'teams:createNewTeamFromConversation': teams.CreateNewTeamFromConversationPayload
  'teams:teamCreated': teams.TeamCreatedPayload
  'teams:createChannel': teams.CreateChannelPayload
  'teams:createChannels': teams.CreateChannelsPayload
  'teams:clearAddUserToTeamsResults': teams.ClearAddUserToTeamsResultsPayload
  'teams:setAddUserToTeamsResults': teams.SetAddUserToTeamsResultsPayload
  'teams:setEmailInviteError': teams.SetEmailInviteErrorPayload
  'teams:setChannelSelected': teams.SetChannelSelectedPayload
  'teams:getTeams': teams.GetTeamsPayload
  'teams:unsubscribeTeamList': teams.UnsubscribeTeamListPayload
  'teams:loadTeam': teams.LoadTeamPayload
  'teams:teamLoaded': teams.TeamLoadedPayload
  'teams:unsubscribeTeamDetails': teams.UnsubscribeTeamDetailsPayload
  'teams:setTeamVersion': teams.SetTeamVersionPayload
  'teams:getMembers': teams.GetMembersPayload
  'teams:setMembers': teams.SetMembersPayload
  'teams:teamSetMemberSelected': teams.TeamSetMemberSelectedPayload
  'teams:getTeamProfileAddList': teams.GetTeamProfileAddListPayload
  'teams:addTeamWithChosenChannels': teams.AddTeamWithChosenChannelsPayload
  'teams:saveChannelMembership': teams.SaveChannelMembershipPayload
  'teams:addParticipant': teams.AddParticipantPayload
  'teams:removeParticipant': teams.RemoveParticipantPayload
  'teams:deleteTeam': teams.DeleteTeamPayload
  'teams:inviteToTeamByEmail': teams.InviteToTeamByEmailPayload
  'teams:inviteToTeamByPhone': teams.InviteToTeamByPhonePayload
  'teams:joinTeam': teams.JoinTeamPayload
  'teams:openInviteLink': teams.OpenInviteLinkPayload
  'teams:requestInviteLinkDetails': teams.RequestInviteLinkDetailsPayload
  'teams:updateInviteLinkDetails': teams.UpdateInviteLinkDetailsPayload
  'teams:respondToInviteLink': teams.RespondToInviteLinkPayload
  'teams:launchNewTeamWizardOrModal': teams.LaunchNewTeamWizardOrModalPayload
  'teams:leaveTeam': teams.LeaveTeamPayload
  'teams:leftTeam': teams.LeftTeamPayload
  'teams:addToTeam': teams.AddToTeamPayload
  'teams:addedToTeam': teams.AddedToTeamPayload
  'teams:reAddToTeam': teams.ReAddToTeamPayload
  'teams:editTeamDescription': teams.EditTeamDescriptionPayload
  'teams:uploadTeamAvatar': teams.UploadTeamAvatarPayload
  'teams:editMembership': teams.EditMembershipPayload
  'teams:removeMember': teams.RemoveMemberPayload
  'teams:removePendingInvite': teams.RemovePendingInvitePayload
  'teams:ignoreRequest': teams.IgnoreRequestPayload
  'teams:setMemberPublicity': teams.SetMemberPublicityPayload
  'teams:setPublicity': teams.SetPublicityPayload
  'teams:setChannelCreationError': teams.SetChannelCreationErrorPayload
  'teams:setWelcomeMessageError': teams.SetWelcomeMessageErrorPayload
  'teams:setEditDescriptionError': teams.SetEditDescriptionErrorPayload
  'teams:setEditMemberError': teams.SetEditMemberErrorPayload
  'teams:settingsError': teams.SettingsErrorPayload
  'teams:setTeamsWithChosenChannels': teams.SetTeamsWithChosenChannelsPayload
  'teams:setTeamCreationError': teams.SetTeamCreationErrorPayload
  'teams:setTeamInviteError': teams.SetTeamInviteErrorPayload
  'teams:setTeamJoinError': teams.SetTeamJoinErrorPayload
  'teams:setTeamJoinSuccess': teams.SetTeamJoinSuccessPayload
  'teams:setTeamRetentionPolicy': teams.SetTeamRetentionPolicyPayload
  'teams:setTeamLoadingInvites': teams.SetTeamLoadingInvitesPayload
  'teams:setTeamInfo': teams.SetTeamInfoPayload
  'teams:setTeamProfileAddList': teams.SetTeamProfileAddListPayload
  'teams:setTeamAccessRequestsPending': teams.SetTeamAccessRequestsPendingPayload
  'teams:setNewTeamInfo': teams.SetNewTeamInfoPayload
  'teams:setNewTeamRequests': teams.SetNewTeamRequestsPayload
  'teams:setTeamSawChatBanner': teams.SetTeamSawChatBannerPayload
  'teams:setTeamSawSubteamsBanner': teams.SetTeamSawSubteamsBannerPayload
  'teams:updateChannelName': teams.UpdateChannelNamePayload
  'teams:setUpdatedChannelName': teams.SetUpdatedChannelNamePayload
  'teams:updateTopic': teams.UpdateTopicPayload
  'teams:setUpdatedTopic': teams.SetUpdatedTopicPayload
  'teams:deleteChannelConfirmed': teams.DeleteChannelConfirmedPayload
  'teams:deleteMultiChannelsConfirmed': teams.DeleteMultiChannelsConfirmedPayload
  'teams:checkRequestedAccess': teams.CheckRequestedAccessPayload
  'teams:getTeamRetentionPolicy': teams.GetTeamRetentionPolicyPayload
  'teams:saveTeamRetentionPolicy': teams.SaveTeamRetentionPolicyPayload
  'teams:renameTeam': teams.RenameTeamPayload
  'teams:setTeamRoleMapLatestKnownVersion': teams.SetTeamRoleMapLatestKnownVersionPayload
  'teams:setTeamRoleMap': teams.SetTeamRoleMapPayload
  'teams:toggleInvitesCollapsed': teams.ToggleInvitesCollapsedPayload
  'teams:setWelcomeMessage': teams.SetWelcomeMessagePayload
  'teams:loadWelcomeMessage': teams.LoadWelcomeMessagePayload
  'teams:loadedWelcomeMessage': teams.LoadedWelcomeMessagePayload
  'teams:startAddMembersWizard': teams.StartAddMembersWizardPayload
  'teams:setAddMembersWizardRole': teams.SetAddMembersWizardRolePayload
  'teams:setAddMembersWizardIndividualRole': teams.SetAddMembersWizardIndividualRolePayload
  'teams:setCreatingChannels': teams.SetCreatingChannelsPayload
  'teams:addMembersWizardPushMembers': teams.AddMembersWizardPushMembersPayload
  'teams:addMembersWizardSetMembers': teams.AddMembersWizardSetMembersPayload
  'teams:addMembersWizardRemoveMember': teams.AddMembersWizardRemoveMemberPayload
  'teams:addMembersWizardSetDefaultChannels': teams.AddMembersWizardSetDefaultChannelsPayload
  'teams:cancelAddMembersWizard': teams.CancelAddMembersWizardPayload
  'teams:finishedAddMembersWizard': teams.FinishedAddMembersWizardPayload
  'teams:finishedNewTeamWizard': teams.FinishedNewTeamWizardPayload
  'teams:setJustFinishedAddMembersWizard': teams.SetJustFinishedAddMembersWizardPayload
  'teams:setSubteamFilter': teams.SetSubteamFilterPayload
  'teams:showTeamByName': teams.ShowTeamByNamePayload
  'teams:setMemberActivityDetails': teams.SetMemberActivityDetailsPayload
  'teams:loadTeamTree': teams.LoadTeamTreePayload
  'teams:startNewTeamWizard': teams.StartNewTeamWizardPayload
  'teams:setTeamWizardTeamType': teams.SetTeamWizardTeamTypePayload
  'teams:setTeamWizardNameDescription': teams.SetTeamWizardNameDescriptionPayload
  'teams:setTeamWizardAvatar': teams.SetTeamWizardAvatarPayload
  'teams:setTeamWizardTeamSize': teams.SetTeamWizardTeamSizePayload
  'teams:setTeamWizardChannels': teams.SetTeamWizardChannelsPayload
  'teams:setTeamWizardSubteams': teams.SetTeamWizardSubteamsPayload
  'teams:setTeamWizardSubteamMembers': teams.SetTeamWizardSubteamMembersPayload
  'teams:setTeamWizardError': teams.SetTeamWizardErrorPayload
  'teams:finishNewTeamWizard': teams.FinishNewTeamWizardPayload
  'teams:manageChatChannels': teams.ManageChatChannelsPayload
  'teams:teamSeen': teams.TeamSeenPayload
  'teams:getActivityForTeams': teams.GetActivityForTeamsPayload
  'teams:setActivityLevels': teams.SetActivityLevelsPayload
  'teams:setTeamListFilterSort': teams.SetTeamListFilterSortPayload
  'teams:loadTeamChannelList': teams.LoadTeamChannelListPayload
  'teams:teamChannelListLoaded': teams.TeamChannelListLoadedPayload
  'tracker2:load': tracker2.LoadPayload
  'tracker2:updatedDetails': tracker2.UpdatedDetailsPayload
  'tracker2:updateResult': tracker2.UpdateResultPayload
  'tracker2:closeTracker': tracker2.CloseTrackerPayload
  'tracker2:changeFollow': tracker2.ChangeFollowPayload
  'tracker2:ignore': tracker2.IgnorePayload
  'tracker2:updateFollows': tracker2.UpdateFollowsPayload
  'tracker2:updateWotEntries': tracker2.UpdateWotEntriesPayload
  'tracker2:getProofSuggestions': tracker2.GetProofSuggestionsPayload
  'tracker2:proofSuggestionsUpdated': tracker2.ProofSuggestionsUpdatedPayload
  'tracker2:showUser': tracker2.ShowUserPayload
  'tracker2:loadNonUserProfile': tracker2.LoadNonUserProfilePayload
  'tracker2:loadedNonUserProfile': tracker2.LoadedNonUserProfilePayload
  'unlock-folders:checkPaperKey': unlockfolders.CheckPaperKeyPayload
  'unlock-folders:openPopup': unlockfolders.OpenPopupPayload
  'unlock-folders:closePopup': unlockfolders.ClosePopupPayload
  'unlock-folders:checkPaperKeyDone': unlockfolders.CheckPaperKeyDonePayload
  'unlock-folders:closeDone': unlockfolders.CloseDonePayload
  'unlock-folders:finish': unlockfolders.FinishPayload
  'unlock-folders:newRekeyPopup': unlockfolders.NewRekeyPopupPayload
  'unlock-folders:onBackFromPaperKey': unlockfolders.OnBackFromPaperKeyPayload
  'unlock-folders:toPaperKeyInput': unlockfolders.ToPaperKeyInputPayload
  'users:getBio': users.GetBioPayload
  'users:updateBrokenState': users.UpdateBrokenStatePayload
  'users:updateFullnames': users.UpdateFullnamesPayload
  'users:updateBio': users.UpdateBioPayload
  'users:setUserBlocks': users.SetUserBlocksPayload
  'users:getBlockState': users.GetBlockStatePayload
  'users:submitRevokeVouch': users.SubmitRevokeVouchPayload
  'users:updateBlockState': users.UpdateBlockStatePayload
  'users:wotReact': users.WotReactPayload
  'users:reportUser': users.ReportUserPayload
  'waiting:incrementWaiting': waiting.IncrementWaitingPayload
  'waiting:decrementWaiting': waiting.DecrementWaitingPayload
  'waiting:batchChangeWaiting': waiting.BatchChangeWaitingPayload
  'waiting:clearWaiting': waiting.ClearWaitingPayload
  'wallets:abandonPayment': wallets.AbandonPaymentPayload
  'wallets:acceptDisclaimer': wallets.AcceptDisclaimerPayload
  'wallets:acceptSEP7Path': wallets.AcceptSEP7PathPayload
  'wallets:acceptSEP7Pay': wallets.AcceptSEP7PayPayload
  'wallets:acceptSEP7Tx': wallets.AcceptSEP7TxPayload
  'wallets:resetAcceptingDisclaimer': wallets.ResetAcceptingDisclaimerPayload
  'wallets:accountsReceived': wallets.AccountsReceivedPayload
  'wallets:accountUpdateReceived': wallets.AccountUpdateReceivedPayload
  'wallets:assetDeposit': wallets.AssetDepositPayload
  'wallets:assetWithdraw': wallets.AssetWithdrawPayload
  'wallets:assetsReceived': wallets.AssetsReceivedPayload
  'wallets:badgesUpdated': wallets.BadgesUpdatedPayload
  'wallets:buildingPaymentIDReceived': wallets.BuildingPaymentIDReceivedPayload
  'wallets:builtPaymentReceived': wallets.BuiltPaymentReceivedPayload
  'wallets:builtRequestReceived': wallets.BuiltRequestReceivedPayload
  'wallets:checkDisclaimer': wallets.CheckDisclaimerPayload
  'wallets:clearBuilding': wallets.ClearBuildingPayload
  'wallets:clearBuiltPayment': wallets.ClearBuiltPaymentPayload
  'wallets:clearBuiltRequest': wallets.ClearBuiltRequestPayload
  'wallets:clearErrors': wallets.ClearErrorsPayload
  'wallets:cancelRequest': wallets.CancelRequestPayload
  'wallets:cancelPayment': wallets.CancelPaymentPayload
  'wallets:createNewAccount': wallets.CreateNewAccountPayload
  'wallets:createdNewAccount': wallets.CreatedNewAccountPayload
  'wallets:externalPartnersReceived': wallets.ExternalPartnersReceivedPayload
  'wallets:exitFailedPayment': wallets.ExitFailedPaymentPayload
  'wallets:exportSecretKey': wallets.ExportSecretKeyPayload
  'wallets:loadAssets': wallets.LoadAssetsPayload
  'wallets:loadAccounts': wallets.LoadAccountsPayload
  'wallets:loadExternalPartners': wallets.LoadExternalPartnersPayload
  'wallets:loadMorePayments': wallets.LoadMorePaymentsPayload
  'wallets:loadPayments': wallets.LoadPaymentsPayload
  'wallets:loadPaymentDetail': wallets.LoadPaymentDetailPayload
  'wallets:loadWalletDisclaimer': wallets.LoadWalletDisclaimerPayload
  'wallets:walletDisclaimerReceived': wallets.WalletDisclaimerReceivedPayload
  'wallets:loadDisplayCurrencies': wallets.LoadDisplayCurrenciesPayload
  'wallets:markAsRead': wallets.MarkAsReadPayload
  'wallets:displayCurrenciesReceived': wallets.DisplayCurrenciesReceivedPayload
  'wallets:loadSendAssetChoices': wallets.LoadSendAssetChoicesPayload
  'wallets:sendAssetChoicesReceived': wallets.SendAssetChoicesReceivedPayload
  'wallets:changeAccountName': wallets.ChangeAccountNamePayload
  'wallets:changedAccountName': wallets.ChangedAccountNamePayload
  'wallets:setAccountAsDefault': wallets.SetAccountAsDefaultPayload
  'wallets:didSetAccountAsDefault': wallets.DidSetAccountAsDefaultPayload
  'wallets:deleteAccount': wallets.DeleteAccountPayload
  'wallets:deletedAccount': wallets.DeletedAccountPayload
  'wallets:loadDisplayCurrency': wallets.LoadDisplayCurrencyPayload
  'wallets:displayCurrencyReceived': wallets.DisplayCurrencyReceivedPayload
  'wallets:changeDisplayCurrency': wallets.ChangeDisplayCurrencyPayload
  'wallets:requestPayment': wallets.RequestPaymentPayload
  'wallets:requestedPayment': wallets.RequestedPaymentPayload
  'wallets:paymentDetailReceived': wallets.PaymentDetailReceivedPayload
  'wallets:paymentsReceived': wallets.PaymentsReceivedPayload
  'wallets:pendingPaymentsReceived': wallets.PendingPaymentsReceivedPayload
  'wallets:recentPaymentsReceived': wallets.RecentPaymentsReceivedPayload
  'wallets:reviewedPaymentReceived': wallets.ReviewedPaymentReceivedPayload
  'wallets:secretKeyReceived': wallets.SecretKeyReceivedPayload
  'wallets:secretKeySeen': wallets.SecretKeySeenPayload
  'wallets:selectAccount': wallets.SelectAccountPayload
  'wallets:setSEP7Tx': wallets.SetSEP7TxPayload
  'wallets:showTransaction': wallets.ShowTransactionPayload
  'wallets:buildPayment': wallets.BuildPaymentPayload
  'wallets:sendPayment': wallets.SendPaymentPayload
  'wallets:sentPayment': wallets.SentPaymentPayload
  'wallets:sentPaymentError': wallets.SentPaymentErrorPayload
  'wallets:setBuildingAmount': wallets.SetBuildingAmountPayload
  'wallets:setBuildingCurrency': wallets.SetBuildingCurrencyPayload
  'wallets:setBuildingFrom': wallets.SetBuildingFromPayload
  'wallets:setBuildingIsRequest': wallets.SetBuildingIsRequestPayload
  'wallets:setBuildingPublicMemo': wallets.SetBuildingPublicMemoPayload
  'wallets:setBuildingRecipientType': wallets.SetBuildingRecipientTypePayload
  'wallets:setBuildingSecretNote': wallets.SetBuildingSecretNotePayload
  'wallets:setBuildingTo': wallets.SetBuildingToPayload
  'wallets:clearBuildingAdvanced': wallets.ClearBuildingAdvancedPayload
  'wallets:setBuildingAdvancedRecipient': wallets.SetBuildingAdvancedRecipientPayload
  'wallets:setBuildingAdvancedRecipientAmount': wallets.SetBuildingAdvancedRecipientAmountPayload
  'wallets:setBuildingAdvancedRecipientAsset': wallets.SetBuildingAdvancedRecipientAssetPayload
  'wallets:setBuildingAdvancedRecipientType': wallets.SetBuildingAdvancedRecipientTypePayload
  'wallets:setBuildingAdvancedPublicMemo': wallets.SetBuildingAdvancedPublicMemoPayload
  'wallets:setBuildingAdvancedSenderAccountID': wallets.SetBuildingAdvancedSenderAccountIDPayload
  'wallets:setBuildingAdvancedSenderAsset': wallets.SetBuildingAdvancedSenderAssetPayload
  'wallets:setBuildingAdvancedSecretNote': wallets.SetBuildingAdvancedSecretNotePayload
  'wallets:calculateBuildingAdvanced': wallets.CalculateBuildingAdvancedPayload
  'wallets:setBuiltPaymentAdvanced': wallets.SetBuiltPaymentAdvancedPayload
  'wallets:sendPaymentAdvanced': wallets.SendPaymentAdvancedPayload
  'wallets:setLastSentXLM': wallets.SetLastSentXLMPayload
  'wallets:setReadyToReview': wallets.SetReadyToReviewPayload
  'wallets:reviewPayment': wallets.ReviewPaymentPayload
  'wallets:openSendRequestForm': wallets.OpenSendRequestFormPayload
  'wallets:linkExistingAccount': wallets.LinkExistingAccountPayload
  'wallets:linkedExistingAccount': wallets.LinkedExistingAccountPayload
  'wallets:rejectDisclaimer': wallets.RejectDisclaimerPayload
  'wallets:validateAccountName': wallets.ValidateAccountNamePayload
  'wallets:validatedAccountName': wallets.ValidatedAccountNamePayload
  'wallets:validateSecretKey': wallets.ValidateSecretKeyPayload
  'wallets:validatedSecretKey': wallets.ValidatedSecretKeyPayload
  'wallets:validateSEP7Link': wallets.ValidateSEP7LinkPayload
  'wallets:validateSEP7LinkError': wallets.ValidateSEP7LinkErrorPayload
  'wallets:setSEP7SendError': wallets.SetSEP7SendErrorPayload
  'wallets:loadMobileOnlyMode': wallets.LoadMobileOnlyModePayload
  'wallets:loadedMobileOnlyMode': wallets.LoadedMobileOnlyModePayload
  'wallets:changeMobileOnlyMode': wallets.ChangeMobileOnlyModePayload
  'wallets:refreshTrustlineAcceptedAssets': wallets.RefreshTrustlineAcceptedAssetsPayload
  'wallets:refreshTrustlineAcceptedAssetsByUsername': wallets.RefreshTrustlineAcceptedAssetsByUsernamePayload
  'wallets:refreshTrustlinePopularAssets': wallets.RefreshTrustlinePopularAssetsPayload
  'wallets:addTrustline': wallets.AddTrustlinePayload
  'wallets:deleteTrustline': wallets.DeleteTrustlinePayload
  'wallets:changedTrustline': wallets.ChangedTrustlinePayload
  'wallets:setTrustlineAcceptedAssets': wallets.SetTrustlineAcceptedAssetsPayload
  'wallets:setTrustlineAcceptedAssetsByUsername': wallets.SetTrustlineAcceptedAssetsByUsernamePayload
  'wallets:setTrustlinePopularAssets': wallets.SetTrustlinePopularAssetsPayload
  'wallets:setTrustlineSearchText': wallets.SetTrustlineSearchTextPayload
  'wallets:setTrustlineSearchResults': wallets.SetTrustlineSearchResultsPayload
  'wallets:clearTrustlineSearchResults': wallets.ClearTrustlineSearchResultsPayload
  'wallets:setTrustlineExpanded': wallets.SetTrustlineExpandedPayload
  'wallets:staticConfigLoaded': wallets.StaticConfigLoadedPayload
  'wallets:setSEP6Message': wallets.SetSEP6MessagePayload
  'common:resetStore': {type: 'common:resetStore'; payload: {}}
}
