export declare const allowMultipleInstances: boolean
export declare const enableActionLogging: boolean
export declare const enableStoreLogging: boolean
export declare const featureFlagsOverride: boolean
export declare const filterActionLogs: boolean
export declare const forceImmediateLogging: boolean
export declare const ignoreDisconnectOverlay: boolean
export declare const immediateStateLogging: boolean
export declare const isDevApplePushToken: boolean
export declare const isTesting: boolean
export declare const printOutstandingRPCs: boolean
export declare const printOutstandingTimerListeners: boolean
export declare const printRPC: boolean
export declare const printRPCBytes: boolean
export declare const printRPCWaitingSession: boolean
export declare const printRPCStats: boolean
export declare const reduxSagaLogger: boolean
export declare const reduxSagaLoggerMasked: boolean
export declare const showDevTools: boolean
export declare const skipSecondaryDevtools: boolean
export declare const skipAppFocusActions: boolean
export declare const userTimings: boolean
export declare const virtualListMarks: boolean
export declare function updateServerConfigLastLoggedIn(): void
