version: '2'

run:
  timeout: 15m
  tests: true

formatters:
  exclusions:
    paths:
      - dokan # Windows-specific FUSE implementation, not maintained
  enable:
    - gofmt
    - gofumpt

linters:
  exclusions:
    paths:
      - dokan # Windows-specific FUSE implementation, not maintained
  enable:
    - misspell # Ready - spelling auto-fixed
    - bodyclose # HTTP response body not closed
    - gocritic # Code quality checks

  disable:
    # Explicitly disable default preset linters until we're ready
    - errcheck
    - govet
    - ineffassign
    - staticcheck
    - unused

  settings:
    gocritic:
      disabled-checks:
        - ifElseChain # Style preference - if-else is often clearer than switch

# Next steps: Enable these linters systematically:
# - errcheck        # 50 issues - Unchecked errors
# - gosec           # 21 issues - Security (G115, G404, G101, G602)
# - govet           # 9 issues - Go vet checks
# - revive          # 25 issues - Style checks
# - staticcheck     # 20 issues - Static analysis
# - unused          # 50 issues - Unused code
