platform :osx, "10.10"
use_frameworks!

target "KBKit" do
  pod "YOLayout"
  pod "GHKit"
  pod "ObjectiveSugar"
  pod "CocoaLumberjack"
  pod "AFNetworking", "~> 2.0"
  pod "GHKeychain"
  pod "Mantle"
  pod "MPMessagePack"
  pod "GHODictionary"
  #  pod "MASPreferences"
  pod "MDPSplitView"
  pod "Slash", :git => "https://github.com/chrisdevereux/Slash"
  pod "Tikppa"
end
