platform :osx, "10.8"

target "Keybase" do
  pod "Sparkle"
  pod "MASPreferences"
end

target "KBApp" do
  pod "Mantle"
  pod "GHKit"
  pod "ObjectiveSugar"
  pod "Slash"

  pod "MPMessagePack"#, :path => "~/Projects/MPMessagePack"

  pod "YOLayout"#, :path => "~/Projects/YOLayout"

  pod "ZXCVBN"
  pod "AFNetworking"

  pod "CocoaLumberjack"
  pod "GHODictionary"

  pod "KBAppKit", :path => "~/Projects/KBAppKit"

end

target "keybase.Helper" do
  pod "MPMessagePack"#, :path => "~/Projects/MPMessagePack"
end

target "Share" do
  pod "GHKit"
end

