platform :osx, "10.8"

target "Keybase" do
  pod "Sparkle"
end

# Used by Keybase.app and extensions
target "KBKit" do
  pod "GHKit"
  pod "ObjectiveSugar"
  pod "GHKeychain"#, :path => "~/Projects/GHKeychain"

  pod "Mantle"

  pod "MPMessagePack"#, :path => "~/Projects/MPMessagePack"

  pod "YOLayout"#, :path => "~/Projects/YOLayout"

  pod "ZXCVBN"
  pod "AFNetworking"

  pod "CocoaLumberjack"
  pod "GHODictionary"

  pod "MASPreferences"

  # Local pods
  pod "KBAppKit", :path => "."
end

# This runs as a privileged helper so keep dependencies
# here to a minimum.
target "keybase.Helper" do
  pod "MPMessagePack"#, :path => "~/Projects/MPMessagePack"
end

