# Do not set use_frameworks! globally otherwise the helper
# tool target binary will silently fail to load since it
# doesn't support dynamic frameworks (for security reasons).
# Also probably not a good idea to set any global options
# here at all.

target "Installer" do
  use_frameworks!
  platform :osx, "10.10"
  pod "ObjectiveSugar"
  pod "GBCli"
  pod "Slash"
  pod "MPMessagePack"
  pod "KBKit", :path => "KBKit"
end


target "Status" do
  use_frameworks!
  platform :osx, "10.10"
  pod "ObjectiveSugar"
  pod "GBCli"
  pod "Slash"
  pod "MPMessagePack"
  pod "KBKit", :path => "KBKit"
end

# This runs as a privileged helper so keep dependencies
# here to a minimum.
target "keybase.Helper" do
  platform :osx, "10.10"
  pod "MPMessagePack"
end

