import {
  ActivityIndicator as NativeActivityIndicator,
  Alert as NativeAlert,
  Animated as NativeAnimated,
  BackHandler as NativeBackHandler,
  Clipboard as NativeClipboard,
  Dimensions as NativeDimensions,
  DrawerLayoutAndroid as NativeDrawerLayoutAndroid,
  Easing as NativeEasing,
  FlatList as NativeFlatList,
  InteractionManager as NativeInteractionManager,
  Keyboard as NativeKeyboard,
  KeyboardAvoidingView as NativeKeyboardAvoidingView,
  Linking as NativeLinking,
  ListView as NativeListView,
  Modal as NativeModal,
  PanResponder as NativePanResponder,
  Picker as NativePicker,
  RefreshControl as NativeRefreshControl,
  SafeAreaView as NativeSafeAreaView,
  SectionList as NativeSectionList,
  StatusBar as NativeStatusBar,
  StyleSheet as NativeStyleSheet,
  Switch as NativeSwitch,
  Text as NativeText,
  TouchableHighlight as NativeTouchableHighlight,
  TouchableNativeFeedback as NativeTouchableNativeFeedback,
  TouchableOpacity as NativeTouchableOpacity,
  TouchableWithoutFeedback as NativeTouchableWithoutFeedback,
  View as NativeView,
} from 'react-native'
import NativeScrollView from './scroll-view.native'
import {NativeImage, FastImage as NativeFastImage} from './native-image.native'
import NativeVirtualizedList from './virtualized-list.native'
import {WebView as NativeWebView} from 'react-native-webview'
import NativeTextInput from './kb-text-input.native'

// We set some useful default here
export {
  NativeActivityIndicator,
  NativeAlert,
  NativeAnimated,
  NativeBackHandler,
  NativeClipboard,
  NativeDimensions,
  NativeDrawerLayoutAndroid,
  NativeEasing,
  NativeFastImage,
  NativeFlatList,
  NativeImage,
  NativeInteractionManager,
  NativeKeyboard,
  NativeKeyboardAvoidingView,
  NativeLinking,
  NativeListView,
  NativeModal,
  NativePanResponder,
  NativePicker,
  NativeRefreshControl,
  NativeSafeAreaView,
  NativeScrollView,
  NativeSectionList,
  NativeStatusBar,
  NativeStyleSheet,
  NativeSwitch,
  NativeText,
  NativeTextInput,
  NativeTouchableHighlight,
  NativeTouchableNativeFeedback,
  NativeTouchableOpacity,
  NativeTouchableWithoutFeedback,
  NativeView,
  NativeVirtualizedList,
  NativeWebView,
}
