import {
  ActivityIndicator as NativeActivityIndicator,
  Alert as NativeAlert,
  Animated as NativeAnimated,
  BackHandler as NativeBackHandler,
  Clipboard as NativeClipboard,
  Dimensions as NativeDimensions,
  DrawerLayoutAndroid as NativeDrawerLayoutAndroid,
  Easing as NativeEasing,
  FlatList as NativeFlatList,
  InteractionManager as NativeInteractionManager,
  Keyboard as NativeKeyboard,
  KeyboardAvoidingView as NativeKeyboardAvoidingView,
  Linking as NativeLinking,
  Modal as NativeModal,
  PanResponder as NativePanResponder,
  Pressable as NativePressable,
  RefreshControl as NativeRefreshControl,
  SectionList as NativeSectionList,
  StatusBar as NativeStatusBar,
  StyleSheet as NativeStyleSheet,
  Switch as NativeSwitch,
  Text as NativeText,
  TextInput as NativeTextInput,
  TouchableHighlight as NativeTouchableHighlight,
  TouchableNativeFeedback as NativeTouchableNativeFeedback,
  TouchableOpacity as NativeTouchableOpacity,
  TouchableWithoutFeedback as NativeTouchableWithoutFeedback,
  View as NativeView,
  VirtualizedList as NativeVirtualizedList,
} from 'react-native'
import NativeScrollView from './scroll-view.native'
import {NativeImage, FastImage as NativeFastImage} from './native-image.native'
import {WebView as NativeWebView} from 'react-native-webview'
import {Picker as NativePicker} from '@react-native-picker/picker'

// We set some useful default here
export {
  NativeActivityIndicator,
  NativeAlert,
  NativeAnimated,
  NativeBackHandler,
  NativeClipboard,
  NativeDimensions,
  NativeDrawerLayoutAndroid,
  NativeEasing,
  NativeFastImage,
  NativeFlatList,
  NativeImage,
  NativeInteractionManager,
  NativeKeyboard,
  NativeKeyboardAvoidingView,
  NativeLinking,
  NativeModal,
  NativePanResponder,
  NativePressable,
  NativePicker,
  NativeRefreshControl,
  NativeScrollView,
  NativeSectionList,
  NativeStatusBar,
  NativeStyleSheet,
  NativeSwitch,
  NativeText,
  NativeTextInput,
  NativeTouchableHighlight,
  NativeTouchableNativeFeedback,
  NativeTouchableOpacity,
  NativeTouchableWithoutFeedback,
  NativeView,
  NativeVirtualizedList,
  NativeWebView,
}
