// @flow
import {
  ActivityIndicator as NativeActivityIndicator,
  Animated as NativeAnimated,
  BackAndroid as NativeBackAndroid,
  Clipboard as NativeClipboard,
  Dimensions as NativeDimensions,
  DrawerLayoutAndroid as NativeDrawerLayoutAndroid,
  Easing as NativeEasing,
  FlatList as NativeFlatList,
  Image as NativeImage,
  KeyboardAvoidingView as NativeKeyboardAvoidingView,
  Keyboard as NativeKeyboard,
  Linking as NativeLinking,
  ListView as NativeListView,
  Modal as NativeModal,
  Navigator as NativeNavigator,
  Picker as NativePicker,
  StyleSheet as NativeStyleSheet,
  Switch as NativeSwitch,
  Text as NativeText,
  TextInput as NativeTextInput,
  TouchableNativeFeedback as NativeTouchableNativeFeedback,
  TouchableWithoutFeedback as NativeTouchableWithoutFeedback,
  TouchableHighlight as NativeTouchableHighlight,
  WebView as NativeWebView,
} from 'react-native'
import ScrollView from './scroll-view.native'

export {
  NativeActivityIndicator,
  NativeAnimated,
  NativeBackAndroid,
  NativeClipboard,
  NativeDimensions,
  NativeDrawerLayoutAndroid,
  NativeEasing,
  NativeFlatList,
  NativeImage,
  NativeKeyboard,
  NativeKeyboardAvoidingView,
  NativeLinking,
  NativeListView,
  NativeModal,
  NativeNavigator,
  NativePicker,
  ScrollView as NativeScrollView, // We set some useful default here
  NativeStyleSheet,
  NativeSwitch,
  NativeText,
  NativeTextInput,
  NativeTouchableNativeFeedback,
  NativeTouchableWithoutFeedback,
  NativeTouchableHighlight,
  NativeWebView,
}
