// @flow
import {
  ActivityIndicator as NativeActivityIndicator,
  Animated as NativeAnimated,
  BackHandler as NativeBackHandler,
  Clipboard as NativeClipboard,
  Dimensions as NativeDimensions,
  DrawerLayoutAndroid as NativeDrawerLayoutAndroid,
  Easing as NativeEasing,
  FlatList as NativeFlatList,
  KeyboardAvoidingView as NativeKeyboardAvoidingView,
  Keyboard as NativeKeyboard,
  Linking as NativeLinking,
  ListView as NativeListView,
  Modal as NativeModal,
  PanResponder as NativePanResponder,
  Picker as NativePicker,
  RefreshControl as NativeRefreshControl,
  SafeAreaView as NativeSafeAreaView,
  SectionList as NativeSectionList,
  StyleSheet as NativeStyleSheet,
  StatusBar as NativeStatusBar,
  Switch as NativeSwitch,
  Text as NativeText,
  TextInput as NativeTextInput,
  TouchableNativeFeedback as NativeTouchableNativeFeedback,
  TouchableWithoutFeedback as NativeTouchableWithoutFeedback,
  TouchableHighlight as NativeTouchableHighlight,
  TouchableOpacity as NativeTouchableOpacity,
  WebView as NativeWebView,
  View as NativeView,
} from 'react-native'
import NativeScrollView from './scroll-view.native'
import {NativeImage, FastImage as NativeFastImage} from './native-image.native'
import NativeVirtualizedList from './virtualized-list.native'

// We set some useful default here
export {
  NativeActivityIndicator,
  NativeAnimated,
  NativeClipboard,
  NativeBackHandler,
  NativeDimensions,
  NativeDrawerLayoutAndroid,
  NativeEasing,
  NativeFastImage,
  NativeFlatList,
  NativeImage,
  NativeKeyboard,
  NativeKeyboardAvoidingView,
  NativeLinking,
  NativeListView,
  NativeModal,
  NativePanResponder,
  NativePicker,
  NativeRefreshControl,
  NativeSafeAreaView,
  NativeVirtualizedList,
  NativeScrollView,
  NativeSectionList,
  NativeStyleSheet,
  NativeStatusBar,
  NativeSwitch,
  NativeText,
  NativeTextInput,
  NativeTouchableNativeFeedback,
  NativeTouchableWithoutFeedback,
  NativeTouchableHighlight,
  NativeTouchableOpacity,
  NativeWebView,
  NativeView,
}
