import * as Styles from '@/styles'
import type {TextType} from './text.shared'

export const useNegativeColors = Styles.createThemedHook((theme): {[K in TextType]: string} => ({
  Body: theme.white,
  BodyBig: theme.white,
  BodyBigExtrabold: theme.white,
  BodyBigLink: theme.white,
  BodyBold: theme.white,
  BodyExtrabold: theme.white,
  BodyItalic: theme.white,
  BodyPrimaryLink: theme.white,
  BodySecondaryLink: theme.white,
  BodySemibold: theme.white,
  BodySemiboldItalic: theme.white,
  BodySemiboldLink: theme.white,
  BodySmall: theme.white,
  BodySmallBold: theme.white,
  BodySmallError: theme.white,
  BodySmallExtrabold: theme.white,
  BodySmallExtraboldSecondaryLink: theme.white,
  BodySmallItalic: theme.white,
  BodySmallPrimaryLink: theme.white,
  BodySmallSecondaryLink: theme.white,
  BodySmallSemibold: theme.white,
  BodySmallSemiboldItalic: theme.white,
  BodySmallSemiboldPrimaryLink: theme.white,
  BodySmallSemiboldSecondaryLink: theme.white,
  BodySmallSuccess: theme.white,
  BodySmallWallet: theme.white,
  BodyTiny: theme.white,
  BodyTinyBold: theme.white,
  BodyTinyExtrabold: theme.white,
  BodyTinyLink: theme.white,
  BodyTinySemibold: theme.white,
  BodyTinySemiboldItalic: theme.white,
  Header: theme.white,
  HeaderBig: theme.white,
  HeaderBigExtrabold: theme.white,
  HeaderExtrabold: theme.white,
  HeaderItalic: theme.white,
  HeaderLink: theme.white,
  Terminal: theme.blueDarker,
  TerminalComment: theme.blueLighter_40,
  TerminalEmpty: theme.blueLighter_40,
  TerminalInline: theme.blueDarker,
}))

export const useTypeStyles = Styles.createStyleHook(theme => ({
  Body: {
    ...Styles.globalStyles.fontRegular,
    color: theme.black,
    fontSize: 16,
    lineHeight: 20,
  },
  BodyBig: {
    ...Styles.globalStyles.fontSemibold,
    color: theme.black,
    fontSize: 17,
    lineHeight: 21,
  },
  BodyBigExtrabold: {
    ...Styles.globalStyles.fontExtrabold,
    color: theme.black,
    fontSize: 17,
    lineHeight: 21,
  },
  BodyBigLink: {
    ...Styles.globalStyles.fontSemibold,
    color: theme.blueDark,
    fontSize: 17,
    lineHeight: 21,
  },
  BodyBold: {
    ...Styles.globalStyles.fontBold,
    color: theme.black,
    fontSize: 16,
    lineHeight: 20,
  },
  BodyExtrabold: {
    ...Styles.globalStyles.fontExtrabold,
    color: theme.black,
    fontSize: 16,
    lineHeight: 20,
  },
  BodyItalic: {
    ...Styles.globalStyles.fontRegular,
    color: theme.black,
    fontSize: 16,
    fontStyle: 'italic' as const,
    lineHeight: 20,
  },
  BodyPrimaryLink: {
    ...Styles.globalStyles.fontRegular,
    color: theme.blueDark,
    fontSize: 16,
    lineHeight: 20,
  },
  BodySecondaryLink: {
    ...Styles.globalStyles.fontRegular,
    color: theme.black_50,
    fontSize: 16,
    lineHeight: 20,
  },
  BodySemibold: {
    ...Styles.globalStyles.fontSemibold,
    color: theme.black,
    fontSize: 16,
    lineHeight: 20,
  },
  BodySemiboldItalic: {
    ...Styles.globalStyles.fontSemibold,
    color: theme.black,
    fontSize: 16,
    fontStyle: 'italic' as const,
    lineHeight: 20,
  },
  BodySemiboldLink: {
    ...Styles.globalStyles.fontSemibold,
    color: theme.blueDark,
    fontSize: 16,
    lineHeight: 20,
  },
  BodySmall: {
    ...Styles.globalStyles.fontRegular,
    color: theme.black_50,
    fontSize: 15,
    lineHeight: 19,
  },
  BodySmallBold: {
    ...Styles.globalStyles.fontBold,
    color: theme.black_50,
    fontSize: 15,
    lineHeight: 19,
  },
  BodySmallError: {
    ...Styles.globalStyles.fontRegular,
    color: theme.redDark,
    fontSize: 15,
    lineHeight: 19,
  },
  BodySmallExtrabold: {
    ...Styles.globalStyles.fontExtrabold,
    color: theme.black_50,
    fontSize: 15,
    lineHeight: 19,
  },
  BodySmallExtraboldSecondaryLink: {
    ...Styles.globalStyles.fontExtrabold,
    color: theme.black_50,
    fontSize: 15,
    lineHeight: 19,
  },
  BodySmallItalic: {
    ...Styles.globalStyles.fontRegular,
    color: theme.black_50,
    fontSize: 15,
    fontStyle: 'italic' as const,
    lineHeight: 19,
  },
  BodySmallPrimaryLink: {
    ...Styles.globalStyles.fontRegular,
    color: theme.blueDark,
    fontSize: 15,
    lineHeight: 19,
  },
  BodySmallSecondaryLink: {
    ...Styles.globalStyles.fontRegular,
    color: theme.black_50,
    fontSize: 15,
    lineHeight: 19,
  },
  BodySmallSemibold: {
    ...Styles.globalStyles.fontSemibold,
    color: theme.black_50,
    fontSize: 15,
    lineHeight: 19,
  },
  BodySmallSemiboldItalic: {
    ...Styles.globalStyles.fontSemibold,
    color: theme.black_50,
    fontSize: 15,
    fontStyle: 'italic' as const,
    lineHeight: 19,
  },
  BodySmallSemiboldPrimaryLink: {
    ...Styles.globalStyles.fontSemibold,
    color: theme.blueDark,
    fontSize: 15,
    lineHeight: 19,
  },
  BodySmallSemiboldSecondaryLink: {
    ...Styles.globalStyles.fontSemibold,
    color: theme.blueDark,
    fontSize: 15,
    lineHeight: 19,
  },
  BodySmallSuccess: {
    ...Styles.globalStyles.fontRegular,
    color: theme.greenDark,
    fontSize: 15,
    lineHeight: 19,
  },
  BodySmallWallet: {
    ...Styles.globalStyles.fontRegular,
    color: theme.purpleDark,
    fontSize: 15,
    lineHeight: 19,
  },
  BodyTiny: {
    ...Styles.globalStyles.fontRegular,
    color: theme.black_50,
    fontSize: 13,
    lineHeight: 17,
  },
  BodyTinyBold: {
    ...Styles.globalStyles.fontBold,
    color: theme.black_50,
    fontSize: 13,
    lineHeight: 17,
  },
  BodyTinyExtrabold: {
    ...Styles.globalStyles.fontExtrabold,
    color: theme.black_50,
    fontSize: 13,
    lineHeight: 17,
  },
  BodyTinyLink: {
    ...Styles.globalStyles.fontRegular,
    color: theme.black_50,
    fontSize: 13,
    lineHeight: 17,
  },
  BodyTinySemibold: {
    ...Styles.globalStyles.fontSemibold,
    color: theme.black_50,
    fontSize: 13,
    lineHeight: 17,
  },
  BodyTinySemiboldItalic: {
    ...Styles.globalStyles.fontSemibold,
    color: theme.black_50,
    fontSize: 13,
    fontStyle: 'italic' as const,
    lineHeight: 17,
  },
  Header: {
    ...Styles.globalStyles.fontBold,
    color: theme.black,
    fontSize: 20,
    lineHeight: 24,
  },
  HeaderBig: {
    ...Styles.globalStyles.fontBold,
    color: theme.black,
    fontSize: 28,
    lineHeight: 32,
  },
  HeaderBigExtrabold: {
    ...Styles.globalStyles.fontExtrabold,
    color: theme.black,
    fontSize: 28,
    lineHeight: 32,
  },
  HeaderExtrabold: {
    ...Styles.globalStyles.fontExtrabold,
    color: theme.black,
    fontSize: 20,
    lineHeight: 24,
  },
  HeaderItalic: {
    ...Styles.globalStyles.fontBold,
    color: theme.black,
    fontSize: 20,
    fontStyle: 'italic' as const,
    lineHeight: 24,
  },
  HeaderLink: {
    ...Styles.globalStyles.fontBold,
    color: theme.blueDark,
    fontSize: 20,
    lineHeight: 24,
  },
  Terminal: {
    ...Styles.globalStyles.fontTerminal,
    color: theme.blueLighter,
    fontSize: 15,
    lineHeight: 20,
  },
  TerminalComment: {
    ...Styles.globalStyles.fontTerminal,
    color: theme.blueLighter_40,
    fontSize: 15,
    lineHeight: 20,
  },
  TerminalEmpty: {
    ...Styles.globalStyles.fontTerminal,
    color: theme.blueLighter_40,
    fontSize: 15,
    height: 20,
    lineHeight: 20,
  },
  TerminalInline: {
    ...Styles.globalStyles.fontTerminal,
    backgroundColor: theme.blueLighter2,
    borderRadius: 2,
    color: theme.blueDarker,
    fontSize: 15,
    height: 20,
    lineHeight: 20,
    padding: 2,
  },
}) as const)
