import * as Styles from '@/styles'
import type {TextType} from './text3.shared'

export const negativeColors: {[K in TextType]: string} = {
  Body: Styles.globalColors.white,
  BodyBig: Styles.globalColors.white,
  BodyBigExtrabold: Styles.globalColors.white,
  BodyBigLink: Styles.globalColors.white,
  BodyBold: Styles.globalColors.white,
  BodyExtrabold: Styles.globalColors.white,
  BodyItalic: Styles.globalColors.white,
  BodyPrimaryLink: Styles.globalColors.white,
  BodySecondaryLink: Styles.globalColors.white,
  BodySemibold: Styles.globalColors.white,
  BodySemiboldItalic: Styles.globalColors.white,
  BodySemiboldLink: Styles.globalColors.white,
  BodySmall: Styles.globalColors.white,
  BodySmallBold: Styles.globalColors.white,
  BodySmallError: Styles.globalColors.white,
  BodySmallExtrabold: Styles.globalColors.white,
  BodySmallExtraboldSecondaryLink: Styles.globalColors.white,
  BodySmallItalic: Styles.globalColors.white,
  BodySmallPrimaryLink: Styles.globalColors.white,
  BodySmallSecondaryLink: Styles.globalColors.white,
  BodySmallSemibold: Styles.globalColors.white,
  BodySmallSemiboldItalic: Styles.globalColors.white,
  BodySmallSemiboldPrimaryLink: Styles.globalColors.white,
  BodySmallSemiboldSecondaryLink: Styles.globalColors.white,
  BodySmallSuccess: Styles.globalColors.white,
  BodySmallWallet: Styles.globalColors.white,
  BodyTiny: Styles.globalColors.white,
  BodyTinyBold: Styles.globalColors.white,
  BodyTinyExtrabold: Styles.globalColors.white,
  BodyTinyLink: Styles.globalColors.white,
  BodyTinySemibold: Styles.globalColors.white,
  BodyTinySemiboldItalic: Styles.globalColors.white,
  Header: Styles.globalColors.white,
  HeaderBig: Styles.globalColors.white,
  HeaderBigExtrabold: Styles.globalColors.white,
  HeaderExtrabold: Styles.globalColors.white,
  HeaderItalic: Styles.globalColors.white,
  HeaderLink: Styles.globalColors.white,
  Terminal: Styles.globalColors.blueDarker,
  TerminalComment: Styles.globalColors.blueLighter_40,
  TerminalEmpty: Styles.globalColors.blueLighter_40,
  TerminalInline: Styles.globalColors.blueDarker,
}

export const typeStyles = Styles.styleSheetCreate(() => ({
  Body: {
    ...Styles.globalStyles.fontRegular,
    color: Styles.globalColors.black,
    fontSize: 16,
    lineHeight: 20,
  },
  BodyBig: {
    ...Styles.globalStyles.fontSemibold,
    color: Styles.globalColors.black,
    fontSize: 17,
    lineHeight: 21,
  },
  BodyBigExtrabold: {
    ...Styles.globalStyles.fontExtrabold,
    color: Styles.globalColors.black,
    fontSize: 17,
    lineHeight: 21,
  },
  BodyBigLink: {
    ...Styles.globalStyles.fontSemibold,
    color: Styles.globalColors.blueDark,
    fontSize: 17,
    lineHeight: 21,
  },
  BodyBold: {
    ...Styles.globalStyles.fontBold,
    color: Styles.globalColors.black,
    fontSize: 16,
    lineHeight: 20,
  },
  BodyExtrabold: {
    ...Styles.globalStyles.fontExtrabold,
    color: Styles.globalColors.black,
    fontSize: 16,
    lineHeight: 20,
  },
  BodyItalic: {
    ...Styles.globalStyles.fontRegular,
    color: Styles.globalColors.black,
    fontSize: 16,
    fontStyle: 'italic' as const,
    lineHeight: 20,
  },
  BodyPrimaryLink: {
    ...Styles.globalStyles.fontRegular,
    color: Styles.globalColors.blueDark,
    fontSize: 16,
    lineHeight: 20,
  },
  BodySecondaryLink: {
    ...Styles.globalStyles.fontRegular,
    color: Styles.globalColors.black_50,
    fontSize: 16,
    lineHeight: 20,
  },
  BodySemibold: {
    ...Styles.globalStyles.fontSemibold,
    color: Styles.globalColors.black,
    fontSize: 16,
    lineHeight: 20,
  },
  BodySemiboldItalic: {
    ...Styles.globalStyles.fontSemibold,
    color: Styles.globalColors.black,
    fontSize: 16,
    fontStyle: 'italic' as const,
    lineHeight: 20,
  },
  BodySemiboldLink: {
    ...Styles.globalStyles.fontSemibold,
    color: Styles.globalColors.blueDark,
    fontSize: 16,
    lineHeight: 20,
  },
  BodySmall: {
    ...Styles.globalStyles.fontRegular,
    color: Styles.globalColors.black_50,
    fontSize: 15,
    lineHeight: 19,
  },
  BodySmallBold: {
    ...Styles.globalStyles.fontBold,
    color: Styles.globalColors.black_50,
    fontSize: 15,
    lineHeight: 19,
  },
  BodySmallError: {
    ...Styles.globalStyles.fontRegular,
    color: Styles.globalColors.redDark,
    fontSize: 15,
    lineHeight: 19,
  },
  BodySmallExtrabold: {
    ...Styles.globalStyles.fontExtrabold,
    color: Styles.globalColors.black_50,
    fontSize: 15,
    lineHeight: 19,
  },
  BodySmallExtraboldSecondaryLink: {
    ...Styles.globalStyles.fontExtrabold,
    color: Styles.globalColors.black_50,
    fontSize: 15,
    lineHeight: 19,
  },
  BodySmallItalic: {
    ...Styles.globalStyles.fontRegular,
    color: Styles.globalColors.black_50,
    fontSize: 15,
    fontStyle: 'italic' as const,
    lineHeight: 19,
  },
  BodySmallPrimaryLink: {
    ...Styles.globalStyles.fontRegular,
    color: Styles.globalColors.blueDark,
    fontSize: 15,
    lineHeight: 19,
  },
  BodySmallSecondaryLink: {
    ...Styles.globalStyles.fontRegular,
    color: Styles.globalColors.black_50,
    fontSize: 15,
    lineHeight: 19,
  },
  BodySmallSemibold: {
    ...Styles.globalStyles.fontSemibold,
    color: Styles.globalColors.black_50,
    fontSize: 15,
    lineHeight: 19,
  },
  BodySmallSemiboldItalic: {
    ...Styles.globalStyles.fontSemibold,
    color: Styles.globalColors.black_50,
    fontSize: 15,
    fontStyle: 'italic' as const,
    lineHeight: 19,
  },
  BodySmallSemiboldPrimaryLink: {
    ...Styles.globalStyles.fontSemibold,
    color: Styles.globalColors.blueDark,
    fontSize: 15,
    lineHeight: 19,
  },
  BodySmallSemiboldSecondaryLink: {
    ...Styles.globalStyles.fontSemibold,
    color: Styles.globalColors.blueDark,
    fontSize: 15,
    lineHeight: 19,
  },
  BodySmallSuccess: {
    ...Styles.globalStyles.fontRegular,
    color: Styles.globalColors.greenDark,
    fontSize: 15,
    lineHeight: 19,
  },
  BodySmallWallet: {
    ...Styles.globalStyles.fontRegular,
    color: Styles.globalColors.purpleDark,
    fontSize: 15,
    lineHeight: 19,
  },
  BodyTiny: {
    ...Styles.globalStyles.fontRegular,
    color: Styles.globalColors.black_50,
    fontSize: 13,
    lineHeight: 17,
  },
  BodyTinyBold: {
    ...Styles.globalStyles.fontBold,
    color: Styles.globalColors.black_50,
    fontSize: 13,
    lineHeight: 17,
  },
  BodyTinyExtrabold: {
    ...Styles.globalStyles.fontExtrabold,
    color: Styles.globalColors.black_50,
    fontSize: 13,
    lineHeight: 17,
  },
  BodyTinyLink: {
    ...Styles.globalStyles.fontRegular,
    color: Styles.globalColors.black_50,
    fontSize: 13,
    lineHeight: 17,
  },
  BodyTinySemibold: {
    ...Styles.globalStyles.fontSemibold,
    color: Styles.globalColors.black_50,
    fontSize: 13,
    lineHeight: 17,
  },
  BodyTinySemiboldItalic: {
    ...Styles.globalStyles.fontSemibold,
    color: Styles.globalColors.black_50,
    fontSize: 13,
    fontStyle: 'italic' as const,
    lineHeight: 17,
  },
  Header: {
    ...Styles.globalStyles.fontBold,
    color: Styles.globalColors.black,
    fontSize: 20,
    lineHeight: 24,
  },
  HeaderBig: {
    ...Styles.globalStyles.fontBold,
    color: Styles.globalColors.black,
    fontSize: 28,
    lineHeight: 32,
  },
  HeaderBigExtrabold: {
    ...Styles.globalStyles.fontExtrabold,
    color: Styles.globalColors.black,
    fontSize: 28,
    lineHeight: 32,
  },
  HeaderExtrabold: {
    ...Styles.globalStyles.fontExtrabold,
    color: Styles.globalColors.black,
    fontSize: 20,
    lineHeight: 24,
  },
  HeaderItalic: {
    ...Styles.globalStyles.fontBold,
    color: Styles.globalColors.black,
    fontSize: 20,
    fontStyle: 'italic' as const,
    lineHeight: 24,
  },
  HeaderLink: {
    ...Styles.globalStyles.fontBold,
    color: Styles.globalColors.blueDark,
    fontSize: 20,
    lineHeight: 24,
  },
  Terminal: {
    ...Styles.globalStyles.fontTerminal,
    color: Styles.globalColors.blueLighter,
    fontSize: 15,
    lineHeight: 20,
  },
  TerminalComment: {
    ...Styles.globalStyles.fontTerminal,
    color: Styles.globalColors.blueLighter_40,
    fontSize: 15,
    lineHeight: 20,
  },
  TerminalEmpty: {
    ...Styles.globalStyles.fontTerminal,
    color: Styles.globalColors.blueLighter_40,
    fontSize: 15,
    height: 20,
    lineHeight: 20,
  },
  TerminalInline: {
    ...Styles.globalStyles.fontTerminal,
    backgroundColor: Styles.globalColors.blueLighter2,
    borderRadius: 2,
    color: Styles.globalColors.blueDarker,
    fontSize: 15,
    height: 20,
    lineHeight: 20,
    padding: 2,
  },
}) as const)
