Vagrant.configure("2") do |config|
  config.vm.box = "debian/buster64"
  config.vm.synced_folder "../vagrantcommon/", "/vagrant"
  config.vm.provider "virtualbox" do |vb|
    vb.gui = true
    vb.memory = "4096"
  end
  config.vm.provision "shell", path: "../vagrantcommon/provision_deb.bash"
end
