// Auto-generated by avdl-compiler v1.3.29 (https://github.com/keybase/node-avdl-compiler)
//   Input file: avdl/keybase1/notify_email.avdl

package keybase1

import (
	"github.com/keybase/go-framed-msgpack-rpc/rpc"
	context "golang.org/x/net/context"
)

type EmailAddressVerifiedArg struct {
	EmailAddress EmailAddress `codec:"emailAddress" json:"emailAddress"`
}

type NotifyEmailAddressInterface interface {
	EmailAddressVerified(context.Context, EmailAddress) error
}

func NotifyEmailAddressProtocol(i NotifyEmailAddressInterface) rpc.Protocol {
	return rpc.Protocol{
		Name: "keybase.1.NotifyEmailAddress",
		Methods: map[string]rpc.ServeHandlerDescription{
			"emailAddressVerified": {
				MakeArg: func() interface{} {
					var ret [1]EmailAddressVerifiedArg
					return &ret
				},
				Handler: func(ctx context.Context, args interface{}) (ret interface{}, err error) {
					typedArgs, ok := args.(*[1]EmailAddressVerifiedArg)
					if !ok {
						err = rpc.NewTypeError((*[1]EmailAddressVerifiedArg)(nil), args)
						return
					}
					err = i.EmailAddressVerified(ctx, typedArgs[0].EmailAddress)
					return
				},
			},
		},
	}
}

type NotifyEmailAddressClient struct {
	Cli rpc.GenericClient
}

func (c NotifyEmailAddressClient) EmailAddressVerified(ctx context.Context, emailAddress EmailAddress) (err error) {
	__arg := EmailAddressVerifiedArg{EmailAddress: emailAddress}
	err = c.Cli.Notify(ctx, "keybase.1.NotifyEmailAddress.emailAddressVerified", []interface{}{__arg})
	return
}
