// Auto-generated by avdl-compiler v1.3.17 (https://github.com/keybase/node-avdl-compiler)
//   Input file: avdl/keybase1/notify_fs_request.avdl

package keybase1

import (
	"github.com/keybase/go-framed-msgpack-rpc/rpc"
	context "golang.org/x/net/context"
)

type FSEditListRequestArg struct {
	Req FSEditListRequest `codec:"req" json:"req"`
}

func (o FSEditListRequestArg) DeepCopy() FSEditListRequestArg {
	return FSEditListRequestArg{
		Req: o.Req.DeepCopy(),
	}
}

type FSSyncStatusRequestArg struct {
	Req FSSyncStatusRequest `codec:"req" json:"req"`
}

func (o FSSyncStatusRequestArg) DeepCopy() FSSyncStatusRequestArg {
	return FSSyncStatusRequestArg{
		Req: o.Req.DeepCopy(),
	}
}

type NotifyFSRequestInterface interface {
	FSEditListRequest(context.Context, FSEditListRequest) error
	FSSyncStatusRequest(context.Context, FSSyncStatusRequest) error
}

func NotifyFSRequestProtocol(i NotifyFSRequestInterface) rpc.Protocol {
	return rpc.Protocol{
		Name: "keybase.1.NotifyFSRequest",
		Methods: map[string]rpc.ServeHandlerDescription{
			"FSEditListRequest": {
				MakeArg: func() interface{} {
					ret := make([]FSEditListRequestArg, 1)
					return &ret
				},
				Handler: func(ctx context.Context, args interface{}) (ret interface{}, err error) {
					typedArgs, ok := args.(*[]FSEditListRequestArg)
					if !ok {
						err = rpc.NewTypeError((*[]FSEditListRequestArg)(nil), args)
						return
					}
					err = i.FSEditListRequest(ctx, (*typedArgs)[0].Req)
					return
				},
				MethodType: rpc.MethodNotify,
			},
			"FSSyncStatusRequest": {
				MakeArg: func() interface{} {
					ret := make([]FSSyncStatusRequestArg, 1)
					return &ret
				},
				Handler: func(ctx context.Context, args interface{}) (ret interface{}, err error) {
					typedArgs, ok := args.(*[]FSSyncStatusRequestArg)
					if !ok {
						err = rpc.NewTypeError((*[]FSSyncStatusRequestArg)(nil), args)
						return
					}
					err = i.FSSyncStatusRequest(ctx, (*typedArgs)[0].Req)
					return
				},
				MethodType: rpc.MethodNotify,
			},
		},
	}
}

type NotifyFSRequestClient struct {
	Cli rpc.GenericClient
}

func (c NotifyFSRequestClient) FSEditListRequest(ctx context.Context, req FSEditListRequest) (err error) {
	__arg := FSEditListRequestArg{Req: req}
	err = c.Cli.Notify(ctx, "keybase.1.NotifyFSRequest.FSEditListRequest", []interface{}{__arg})
	return
}

func (c NotifyFSRequestClient) FSSyncStatusRequest(ctx context.Context, req FSSyncStatusRequest) (err error) {
	__arg := FSSyncStatusRequestArg{Req: req}
	err = c.Cli.Notify(ctx, "keybase.1.NotifyFSRequest.FSSyncStatusRequest", []interface{}{__arg})
	return
}
