// Auto-generated by avdl-compiler v1.3.20 (https://github.com/keybase/node-avdl-compiler)
//   Input file: avdl/keybase1/teams_ui.avdl

package keybase1

import (
	"github.com/keybase/go-framed-msgpack-rpc/rpc"
	context "golang.org/x/net/context"
)

type ConfirmRootTeamDeleteArg struct {
	SessionID int    `codec:"sessionID" json:"sessionID"`
	TeamName  string `codec:"teamName" json:"teamName"`
}

func (o ConfirmRootTeamDeleteArg) DeepCopy() ConfirmRootTeamDeleteArg {
	return ConfirmRootTeamDeleteArg{
		SessionID: o.SessionID,
		TeamName:  o.TeamName,
	}
}

type ConfirmSubteamDeleteArg struct {
	SessionID int    `codec:"sessionID" json:"sessionID"`
	TeamName  string `codec:"teamName" json:"teamName"`
}

func (o ConfirmSubteamDeleteArg) DeepCopy() ConfirmSubteamDeleteArg {
	return ConfirmSubteamDeleteArg{
		SessionID: o.SessionID,
		TeamName:  o.TeamName,
	}
}

type TeamsUiInterface interface {
	ConfirmRootTeamDelete(context.Context, ConfirmRootTeamDeleteArg) (bool, error)
	ConfirmSubteamDelete(context.Context, ConfirmSubteamDeleteArg) (bool, error)
}

func TeamsUiProtocol(i TeamsUiInterface) rpc.Protocol {
	return rpc.Protocol{
		Name: "keybase.1.teamsUi",
		Methods: map[string]rpc.ServeHandlerDescription{
			"confirmRootTeamDelete": {
				MakeArg: func() interface{} {
					ret := make([]ConfirmRootTeamDeleteArg, 1)
					return &ret
				},
				Handler: func(ctx context.Context, args interface{}) (ret interface{}, err error) {
					typedArgs, ok := args.(*[]ConfirmRootTeamDeleteArg)
					if !ok {
						err = rpc.NewTypeError((*[]ConfirmRootTeamDeleteArg)(nil), args)
						return
					}
					ret, err = i.ConfirmRootTeamDelete(ctx, (*typedArgs)[0])
					return
				},
				MethodType: rpc.MethodCall,
			},
			"confirmSubteamDelete": {
				MakeArg: func() interface{} {
					ret := make([]ConfirmSubteamDeleteArg, 1)
					return &ret
				},
				Handler: func(ctx context.Context, args interface{}) (ret interface{}, err error) {
					typedArgs, ok := args.(*[]ConfirmSubteamDeleteArg)
					if !ok {
						err = rpc.NewTypeError((*[]ConfirmSubteamDeleteArg)(nil), args)
						return
					}
					ret, err = i.ConfirmSubteamDelete(ctx, (*typedArgs)[0])
					return
				},
				MethodType: rpc.MethodCall,
			},
		},
	}
}

type TeamsUiClient struct {
	Cli rpc.GenericClient
}

func (c TeamsUiClient) ConfirmRootTeamDelete(ctx context.Context, __arg ConfirmRootTeamDeleteArg) (res bool, err error) {
	err = c.Cli.Call(ctx, "keybase.1.teamsUi.confirmRootTeamDelete", []interface{}{__arg}, &res)
	return
}

func (c TeamsUiClient) ConfirmSubteamDelete(ctx context.Context, __arg ConfirmSubteamDeleteArg) (res bool, err error) {
	err = c.Cli.Call(ctx, "keybase.1.teamsUi.confirmSubteamDelete", []interface{}{__arg}, &res)
	return
}
