FROM solita/ubuntu-systemd
MAINTAINER Keybase <admin@keybase.io>

RUN apt-get update

# Install dependencies for keybase
RUN apt-get install -y fuse psmisc procps lsof

# Nice to have
RUN apt-get install -y vim less curl

